api/opensource/mfx_dispatch/include/mfx_dispatcher_defs.h, api/opensource/mfx_dispatch/src/mfx_load_plugin.cpp, api/opensource/mfx_dispatch/src/mfx_plugin_hive.cpp, api/opensource/mfx_dispatch/src/mfx_win_reg_key.cpp
This small change allows compiling mfx.lib on Windows MINGW64 with gcc-6.3.
=> fixed mfx_dispatch compilation with gcc6/MinGW64

CMakeLists.txt
Often, MFX_HOME will just point back to the source tree that
is being configured by cmake.
Thus, set MFX_HOME to CMAKE_HOME_DIRECTORY if user does not
set it.
Fixes #16
=> cmake: allow MFX_HOME to be optional

_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_cm.cpp, _studio/shared/src/libmfx_core_vaapi.cpp
Adding CFL and CNL into MSDK whitelist as exposed by Media Driver.
Signed-off-by: Raynald Lim <raynald.lim@intel.com>
=> Add CFL and CNL support.

builder/FindFunctions.cmake
Without this change, the build fails on Fedora 26 with the following messages:
../../__lib/release/libencode_hw.a(mfx_h264_scd.cpp.o): In function `MfxHwH264Encode::ASC::Get_CpuFeature_AVX2()':
/home/ddd/Work/msdk/_studio/mfx_lib/encode_hw/h264/src/mfx_h264_scd.cpp:582: undefined reference to `__cpu_model'
../../__lib/release/libencode_hw.a(mfx_h264_scd.cpp.o): In function `MfxHwH264Encode::ASC::Get_CpuFeature_SSE41()':
mfx_h264_scd.cpp:(.text+0x4f43): undefined reference to `__cpu_model'
../../__lib/release/libencode_hw.a(mfx_h264_scd.cpp.o): In function `_GLOBAL__sub_I_mfx_h264_scd.cpp':
mfx_h264_scd.cpp:(.text.startup+0x2d): undefined reference to `__cpu_model'
../../__lib/release/libvpp_hw.a(mfx_scd.cpp.o): In function `SceneChangeDetector::Init(int, int, int, unsigned int, …
=> Add -lgcc to avoid undefined __cpu_model on Fedora 26 (fixes issue #33 for me)

builder/FindPackages.cmake
Add "-Wl,--no-as-needed -ldl" to linker flags.
On Ubuntu Trusty 14.04 LTS with GCC 4.8.4, fix linker
error in vm_shared_object_linux32.c.o for libmfxhw64.so:
```
undefined reference to `dlopen'
undefined reference to `dlsym'
undefined reference to `dlclose'
```
Fixes #34
=> libmfxhw64: add -ldl to linker flags

CMakeLists.txt, api/opensource/mfx_dispatch/CMakeLists.txt, api/opensource/mfx_dispatch/pkg-config.pc.cmake, builder/FindGlobals.cmake
Use GNUInstallDirs to determine standard location to
install libraries and include headers.  This also
enables developers to override them, too.  For example,
-DCMAKE_INSTALL_LIBDIR=lib/lin_x64 will install into
$CMAKE_INSTALL_PREFIX/lib/lin_x64 and so on.
Fixes #17
=> cmake: using GNUInstallDirs for mfx libraries and headers

samples/sample_hevc_fei/include/sample_hevc_fei_defs.h, samples/sample_hevc_fei/src/fei_predictors_repaking.cpp, samples/sample_hevc_fei/src/hevc_fei_preenc.cpp, samples/sample_hevc_fei/src/pipeline_hevc_fei.cpp, samples/sample_hevc_fei/src/sample_hevc_fei.cpp
Add CL parameter to enable quality mode in repack.
Fixed repacking method.
DisableStatisticsOutput is set only once on init.
Issue: MDP-38601
=> fix HEVC FEI repack quality mode

samples/sample_hevc_fei/CMakeLists.txt
Don't hard-code -Werror into compiler flags.  Instead, use
the configured value from WARNING_FLAGS.  This allows
the user to disable -Werror if needed.
Currently, on some compiler versions there are still
some warnings being generated in samples/hevc_fei. So
remove hard-coded -Werror and use WARNING_FLAGS instead.
Fixes #48
=> samples: use WARNING_FLAGS definition

_studio/hevce_hw/h265/src/mfx_h265_encode_hw.cpp
Previous implementation had an issue in case of sts2 < 0 and sts1 == 0 (ERR_NONE)
=> [HEVCe FEI] Fixed issue with incorrect worst status detection

_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
Add check in Query() and Init() for progressive output picture structure.
This allow consistent behavior with VPP processing.
=> [VPP] Add check for progressive output in case of field weaving

api/opensource/mfx_dispatch/CMakeLists.txt, api/opensource/mfx_dispatch/pkg-config.pc.cmake
Add additional required libraries needed to link to libmfx and rename mfx.pc to libmfx.pc (with a backwards compatible symlink).
=> Package config fixes

_studio/hevce_hw/h265/include/mfx_h265_encode_hw_utils.h, _studio/hevce_hw/h265/src/mfx_h265_encode_hw_par.cpp, _studio/hevce_hw/h265/src/mfx_h265_encode_hw_utils.cpp
Issue: MDP-39596
Test: manually
1) Number of Active Reference frames
must be the same after Reset by default.
Inherit was added for
NumActiveReference parameters.
2) NumRefLX are excess. It was deleted.
3) Matching was added  between DDI.
NumActiveRef and CO3.NumRefActive
4) default NumRefFrame is calculated
with considering
NumActiveReference for B pyr now.
=> [HEVC E]: Fix for Active Reference

_studio/shared/umc/codec/h264_dec/include/umc_h264_frame_info.h, _studio/shared/umc/codec/h264_dec/src/umc_h264_dec_slice_decoder_decode_pic.cpp
H264DecoderFrame::UpdateErrorWithRefFrameStatus incorrectly propogated
curruption flags. RC is that the function operated with not an actual
m_refPicList.
The change consists of two parts:
* We need to set a null terminated element
in a ref list after calls to ReOrderRefPicList
since this function overwrites the null terminated element
* In case of PAFF the 2nd field info contains garbage.
So need to clear m_refPicList on Reset().
=> [h264d] Fix for corruption reporting

_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp, _studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp
VAEncPackedHeaderH264_SEI has been depricated so
we replace it with VAEncPackedHeaderRawData
=> [h264e, h264e fei] Removed usage of VAEncPackedHeaderH264_SEI

samples/sample_hevc_fei/src/fei_utils.cpp
When input file is coded bitstream without specified framerate,
initialization of the following components like VPP will fail.
Use user-defined framerate or set 30 fps by default.
=> [sample_hevc_fei] Specify default framerate after Decoder

_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp, _studio/mfx_lib/vpp/src/mfx_vpp_utils.cpp
Fixed a couple of issues:
1. Init returns skipped_filter warning
even if this is supported according to caps.
This is incorrect behaviour.
2. For case of unloaded cmrt libraries
horizontal mirroring is crashed with seg fault
because CmCopy device is not created.
=> [vpp] Fix issues in horizontal mirroring

_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp, _studio/shared/include/mfx_mfe_adapter.h, _studio/shared/src/mfx_mfe_adapter.cpp
Fixed performance/functional issue with SkipFrame & mfe
When nothing is sent to driver during skip frame
need to count stream as submitted without real submission
to not make other streams wait for it.
Issue: MDP-40197
Test: manual
=> [h264e][mfe] fix skip frame issue

_studio/mfx_lib/decode/h264/src/mfx_h264_dec_decode.cpp, _studio/shared/src/libmfx_core_vaapi.cpp, _studio/shared/src/mfx_vpp_vaapi.cpp, samples/sample_vpp/src/sample_vpp_parser.cpp
Added run-time check for APL to use low
power scaling mode by default due to power
consumption consideration.
Document scaling mode in sample vpp.
=> [vpp] Enable low power mode scaling

api/include/mfxfeihevc.h
Correct length for reserved fields was added to DWORD 0.
=> [HEVC FEI] Fix for alignment of the mfxFeiHevcPakCuRecordV0

_studio/mfx_lib/fei/h264_preenc/mfx_h264_preenc.cpp, _studio/mfx_lib/fei/h264_preenc/mfx_h264_preenc.h, samples/sample_fei/include/fei_preenc.h, samples/sample_fei/src/fei_preenc.cpp, samples/sample_fei/src/pipeline_fei.cpp
There is no sense of QueryIOSurf() for PreENC for current PreENC implementation, so 1) remove the declaration and implementation of this API from PreENC. 2) remove the call in sample_fei.
=> [AVC FEI PreENC] remove QueryIOSurf for PreENC.

_studio/hevc_fei/h265_fei/src/mfx_h265_fei_encode_hw.cpp, samples/sample_hevc_fei/src/sample_hevc_fei.cpp
Change the maximum available value for SearchWindow to 5, as it is the maximum supported value for this option in driver.
=> [HEVC FEI] Fix SearchWindow check to sync with the driver support

samples/sample_hevc_fei/src/fei_predictors_repaking.cpp, samples/sample_hevc_fei/src/sample_hevc_fei.cpp
Now if PREENC is being used without external MVP input file and
-MVPBlockSize is not specified, the MVPredictor FEI option will be set
to 1 (16x16 MVP block layout)
=> [sample_hevc_fei] Fix MVP block size setting for PREENC use cases

_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
Previously result returned by ValidateParams wasn't checked.
=> [vpp] Fix parameters validation in QueryIOSurf

api/opensource/mfx_dispatch/src/main.cpp
C++ reference can't be assign with nullptr. Check for pointer to not be null first.
=> Check for session validity before dereferencing

_studio/hevce_hw/h265/src/mfx_h265_encode_hw_par.cpp
Now GPB won't fall back to the default "on" value if it is
left unspecified after encoder reset, but will instead
keep the pre-reset value.
=> [HEVCe HW] Inherit GPB value during resets

_studio/hevce_hw/h265/src/mfx_h265_encode_vaapi.cpp
In case of interlace encode, mfx gop params are calculated
in pairs of fields but drivers params are in fields.
So we need to correctly calculate libva params.
=> [hevce] Fixed mapping of MFX to Libva GOP params

_studio/hevce_hw/h265/include/mfx_h265_encode_hw_utils.h, _studio/hevce_hw/h265/src/mfx_h265_encode_hw.cpp, _studio/hevce_hw/h265/src/mfx_h265_encode_hw_par.cpp, _studio/hevce_hw/h265/src/mfx_h265_encode_hw_utils.cpp
Issue: MDP-40457
Test: dev. test (quality test)
changes:
1) QP offsets were changed
2) first field is alway reference in B pyr
3) first field is always in RPL backward in B pyr
redesign:
1) native reordering (no last field class)
2) possibility to reorder fields in frame (switched off now).
3) possibility to avoid low high levels in b pyr.
=> [HEVC E] Field Bpyr Quality optimization

_studio/hevce_hw/CMakeLists.txt, _studio/mfx_lib/CMakeLists.txt, _studio/mfx_lib/plugin/CMakeLists.txt, api/opensource/mfx_dispatch/src/mfx_load_dll_linux.cpp, builder/FindPackages.cmake
Different names for targets in Release and Debug modes just complicate
the things. Usually end user will either rewrite release binaries with
the debug ones or use separate installation folders.
=> Remove mediasdk target names difference between Debug and Release

_studio/hevce_hw/h265/src/mfx_h265_encode_hw_utils.cpp, samples/sample_hevc_fei/include/ref_list_manager.h, samples/sample_hevc_fei/include/sample_hevc_fei_defs.h, samples/sample_hevc_fei/src/pipeline_hevc_fei.cpp, samples/sample_hevc_fei/src/ref_list_manager.cpp, samples/sample_hevc_fei/src/sample_hevc_fei.cpp
New CL parameter -active_ref_lists_par <file> which contains
frame and ref.list info for each frame in stream
(file is generated by ASG).
EncodeOrderExtControl inherits EncodeOrderControl.
Commit also fix frame_field_infor_present_flag and
limits max_num_reorder.
=> [HEVCe FEI] Add extern RefListCtrl from file

samples/sample_hevc_fei/src/ref_list_manager.cpp
Set external picture structure value to mfxSurface structure,
otherwise input fields are named in tff order.
=> [HEVC FEI SAMPLE] fix PictStruct for extern RefList control

api/opensource/mfx_dispatch/CMakeLists.txt, api/opensource/mfx_dispatch/pkg-config-shared.pc.cmake
- Added dispatch_shared library to installed files along with "regular" libmfx.
- Added separate pkgconfig file for dispatch_shared.
=> mfx_dispatch: Install dispatch_shared

_studio/hevc_fei/h265_fei/src/mfx_h265_fei_encode_hw.cpp
Switched mfxExtFeiHevcEncFrameCtrl field correctness check error
to MFX_ERR_INVALID_VIDEO_PARAM
=> [HEVCe FEI] Changed mfxExtFeiHevcEncFrameCtrl field check error

samples/sample_vpp/src/sample_vpp.cpp, samples/sample_vpp/src/sample_vpp_parser.cpp
Additionally, counting output surfaces to which
procamp buffer attached is fixed.
=> Clarify run-time HSBC description in sample_vpp

_studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h, _studio/shared/umc/codec/h264_dec/src/umc_h264_task_supplier.cpp
This is an error tolerance improvement.
The change consider a case when some ST has frame_num
duplicating a frame_num of new frame. This is illigal but the spec
doesn't define behavior in such case.
=> [h264d] Remove ST frames with duplicated frame_num

_studio/mfx_lib/decode/vp8/include/mfx_vp8_dec_decode_hw.h, _studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw.cpp
Changed logic of Routine process:
- Added mutex to vp8d
- Moved choosing memIdTOUnlock to Routine from DecodeFrameCheck
- Changed logic of choosing memIdToUnlock
- Syncronized surfaces for current memId
=> [vp8d] Fixed problems with system memory

_studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h, _studio/mfx_lib/shared/src/mfx_brc_common.cpp, _studio/shared/asc/src/asc.cpp
Added support for CFL in ASC::InitGPUsurf(), it was causing
mfx_err_device_failed when ran on a CFL platform.
Correct initialization of ASCVidSample in ASC::Init, which in case
of failure during initialization of GPU surfaces in InitGPUsurf()
will make Init to exit without initializing m_videoData array,
which then cause the system to crash at ASC::Close() because it
will identify m_videoData array to hold info (not NULL) and then
try to deallocate unallocated memory.
BRC LTR code now Wrapped in MFX_VERSION >= 1026, replaces
(MFX_VERSION >= MFX_VERSION_NEXT)
Issue: MDP-41086, MDP-40692
Test: h264e_extbrc_adaptive_ltr
=> [H264e HW] CFL Support, fix ASCVidSample init, MFX_VERSION >= 1026

_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
Issue: MDP-41564
Test: manual run of SMT with enabled FadeDetection
=> [h264e] Fix for leaking CmEvent objects

_studio/mfx_lib/decode/vc1/src/mfx_vc1_decode.cpp, _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp, _studio/mfx_lib/encode_hw/mjpeg/src/mfx_mjpeg_encode_hw.cpp, _studio/mfx_lib/fei/h264_common/fei_common.cpp, _studio/mfx_lib/shared/src/mfx_common_int.cpp, _studio/mfx_lib/shared/src/mfx_enc_common.cpp, _studio/mfx_lib/shared/src/mfx_mpeg2_encode_vaapi.cpp, _studio/mfx_lib/vpp/src/mfx_vpp_sw_core.cpp, _studio/shared/src/cm_mem_copy.cpp, _studio/shared/umc/codec/h264_dec/src/umc_h264_dec_bitstream_headers.cpp, _studio/shared/umc/codec/h264_dec/src/umc_h264_task_supplier.cpp, _studio/shared/umc/codec/vc1_dec/src/umc_vc1_huffman.cpp
The change addresses the following types of warnings treated as errors:
* this ‘if’ clause does not guard this statement
* ‘*’ in boolean context
* dereferencing type-punned pointer will break strict-aliasing rules
=> Fixes for compilation warnings on gcc 7.3

_studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_dec_slice_hw.cpp
It fixes debug compilation with gcc 7.3
=> [mpeg2d] q_matrix zero initilizatioin

_studio/mfx_lib/vpp/include/mfx_vpp_hw.h, _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
On Linux DoFastCopy copy works slowly then copy via driver, so make sense copy via
driver in case of VPP called without filters
Rename m_bPassThroughEnable to m_bCopyPassThroughEnable
=> [VPP][Linux]Fix performance drop

_studio/mfx_lib/vpp/src/mfx_vpp_utils.cpp
When application changes manually input picstruct in runtime
for field weaving, library incorrectly interpreted it as using
different picstructs (BFF->TFF or TFF->BFF) in non-field weaving
mode because MFX_PICSTRUCT_FIELD_TOP/BOTTOM contain
MFX_PICSTRUCT_FIELD_TFF/BFF
=> [vpp] Fix unexpected MFX_WRN_INCOMPATIBLE_PARAM in FW pipeline

samples/sample_fei/include/encoding_task.h, samples/sample_fei/include/sample_fei_defs.h, samples/sample_fei/src/pipeline_fei.cpp, samples/sample_fei/src/refListsManagement_fei.cpp, samples/sample_fei/src/sample_fei.cpp
Change the default ref list for P frames when B-Pyramid is enabled,
disable prediction of P frames from reference B.
=> [AVC FEI][sample] add one option "-noPtoBref".

_studio/hevc_fei/h265_fei/src/mfx_h265_fei_encode_hw.cpp, samples/sample_hevc_fei/src/sample_hevc_fei.cpp
SearchWindow provides predefined values for RefWidth, RefHeight, LenSP and SearchPath. AdaptiveSearch should be set separately.
=> [HEVC FEI] Remove restriction of using AdaptiveSearch with SearchWindow

_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
Fixed processing of MFX_MF_DISABLED mode
=> [mfe] fix explicit disabling multi-frame

samples/sample_hevc_fei/include/sample_hevc_fei_defs.h
The repack filenames are stored in char arrays and so should be zero-
initialized.
=> [sample_hevc_fei] Properly initialize repack filenames

_studio/shared/src/mfx_vpp_vaapi.cpp
Fixes: #236
This is misuse of vaGetConfigAttributes function. It _expects_ to get list of
attributes (i.e. types) to be queried. Instead mediasdk tried to do I don't know what.
It passed non-initialized attribute to the function and got random results. We could
hit unknown attribute and error out or we could hit known attribute and initialize to
some unpredictable behaviour.
=> [vpp] Fix random error out on VPP initialization due to non-configured attributes

_studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp
Library doesn't support SW implementation for M/JPEG decoder and
HW implementation supports only part of them. Commit restored cases
which can be executed by HW implementation.
=> [JPEGd/MJPEGd] Restore cases that can be executed by HW on BDW/SKL

_studio/mfx_lib/decode/mpeg2/include/mfx_mpeg2_decode.h, _studio/mfx_lib/decode/mpeg2/src/mfx_mpeg2_decode.cpp, _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_dec.cpp, _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_dec_pic.cpp
When picture data is extracted from bs, verifies for proper picture
type, structure and temporal order using current and next picture headers.
If corrupted picture is detected it is dropped and the next picture
will be extracted.
=> [mpeg2d] Add check for headers corruption

_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
Looks like iHD driver has fixed it and support expose QP now.
Signed-off-by: Zhong Li <zhong.li@intel.com>
=> h264enc: support expose QP value

_studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_dec_slice_hw.cpp
Valgrind check shows a possible illegal memory access out of boundary.
This change removed the illegal memory access and fixed a bug
for slice size calculation related to stuffing bytes.
=> [mpeg2d] Fix possible memory access out of boundary

samples/sample_common/src/vaapi_utils.cpp
libX11.so is a linker name so it is not available if the
libX11-dev package is not installed.
As a result, attempting to render to screen with X server
will fail (e.g. sample_decode -r ...)
This fix changes the code to dlopen the actual library name
instead: libX11.so.6
Issue: #210
Tests: remove symlink for libX11.so and run sample_decode -r
test_results.json attached.
[test_results.json.txt](https://github.com/Intel-Media-SDK/MediaSDK/files/2074198/test_results.json.txt)
=> [sample_common] Load libX11.so.6 instead of libX11.so

samples/sample_fei/src/fei_encpak.cpp
Fixed part of https://github.com/Intel-Media-SDK/MediaSDK/issues/257 related to sample_fei
=> [sample_fei] Fix initializing order

_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
Calling vaMapBuffer is enough for synchronization.
=> Fix AVC encoder performance degradation

samples/sample_hevc_fei/include/pipeline_hevc_fei.h, samples/sample_hevc_fei/src/pipeline_hevc_fei.cpp
PreENC doesn't support all the ext buffers, as Encode does.
This commit fixes the problem of getting more buffers for PreENC, than it supports.
=> [HEVC FEI] Get different videoParams for PreENC and Encode

samples/sample_multi_transcode/src/transcode_utils.cpp
This option was removed by mistake in one of the previous commits to SMT
=> [SMT] Return back no_bref option to switch off the B-pyramid

_studio/mfx_lib/decode/vc1/src/mfx_vc1_decode.cpp, _studio/mfx_lib/scheduler/include/mfx_dependency_item.h, _studio/mfx_lib/scheduler/include/mfx_scheduler_core.h, _studio/mfx_lib/scheduler/src/mfx_scheduler_core.cpp, _studio/mfx_lib/shared/include/mfx_h264_enc_common_hw.h, _studio/mfx_lib/shared/include/mfx_task.h, _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp, _studio/shared/mfx_trace/src/mfx_trace_ftrace.cpp, _studio/shared/umc/codec/h264_dec/src/umc_h264_dec_debug.cpp, _studio/shared/umc/codec/h264_dec/src/umc_h264_dec_slice_decoder_decode_pic.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_utils.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_slice_decoding.cpp, _studio/shared/umc/codec/jpeg_common/src/bitstreamin.cpp, _studio/shared/umc/codec/vc1_dec/src/umc_vc1_video_decoder.cpp, _studio/shared/umc/codec/vc1_dec/src/umc_vc1_video_decoder_hw.cpp, _studio/shared/umc/core/umc/include/umc_array.h, _studio/shared/umc/core/umc/src/umc_video_decoder.cpp, api/opensource/mfx_dispatch/include/mfx_load_plugin.h, api/opensource/mfx_dispatch/src/mfx_plugin_hive_linux.cpp
#266 Fedora28 and latest ClearLinux introduce gcc8.x, which bring more strict
check during compilation. This PR fix a bunch of errors including -Werror=paraentheses/class-memaccess/maybe-uninitilized/..
=> [gcc8.x] Fix a bunch of compilation issues from gcc8.x

_studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h, _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
Introduced some more VA sts checks for libVA calls. Only AVC and FEI Encode for now
=> [AVCe] Add missing checks of libva return statuses to AVC encoder

_studio/mfx_lib/decode/mpeg2/src/mfx_mpeg2_decode.cpp
Allow equal temporal references if second is I
when two are not paired fields
Issue: MDP-42860
Test: manual issue
=> [mpeg2d] fix verification of equal temporal refs

_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
fix regression in IntraRefresh parameters processing when MFE is not enabled.
=> [h264e] fixed IntraRefresh behavior regression

_studio/shared/src/mfx_vpp_vaapi.cpp
Fix video wall for tiles > 1; need to delete set up outputparam. It is incorrect using filter in this param it should process as common surface
=> [VPP] Fix videowall regression

_studio/mfx_lib/decode/mpeg2/src/mfx_mpeg2_decode.cpp
Heavily corrupted stream.
There are so many noise bytes between sequence header and next start code,
so it exceeds frame buffer size, after reentering FrameConstructor does the
same. Added code drops noise bytes in such situation.
=> [mpeg2d] fix hang in mpeg2d_stream_corrupter

_studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp
Decoder stucks when DPB is exhausted and submitted slices have
[SliceHeader :: pic_output_flag == 0]
Flow which cause the issue:
1. Submit 1st slice (IDR)
2. There is available data in bitstream, but there is no free frames
in allocator. This is because [async == 1] and for sys. mem an internal
allocator is used. Note, increasing async depth doesn't help, we just
move a little bit further.
3. [DecodeFrame] returns ERR_MORE_SURFACE -> no scheduler task is
created
4. Repeat 2-3 for a couple of following slices, until capacity of
internal allocator (DPB) is exhausted
6. Error above is handled in the following way - if we have enough
data to start 'decoding' (this means we have at least on full AU in
queue) - we create special 'virtual task' (if it was not scheduled yet).
7. The thing is we …
=> [h265] Fix decoder hang

_studio/shared/umc/codec/h265_dec/include/umc_h265_dec_defs.h, _studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_supplier.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp
Accord. to ITU-T H.265 7.4.2.4 "Any PPS NAL unit containing the value
of pps_pic_parameter_set_id for the active PPS RBSP for a coded
picture (and consequently for the layer containing the coded picture)
shall have the same content as that of the active PPS RBSP for the coded
picture, unless it follows the last VCL NAL unit of the coded picture
and precedes the first VCL NAL unit of another coded picture". The same
is applicable for SPS. So, we just complete current AU if we met SPS\PPS
which differ from active ones.
=> [h265] Fix GPU hang

_studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp
After elimination corrupted slices from a frame we may get a
situation when there are no slices at all. Avoid to send such frame
to HW because we can get unexpected error.
=> [h265d] Skip submitting empty (no slices) frame

_studio/mfx_lib/shared/include/mfx_brc_common.h, _studio/mfx_lib/shared/src/mfx_brc_common.cpp, samples/sample_common/include/brc_routines.h, samples/sample_common/src/brc_routines.cpp
MDP-41356
BRC_ctx::totalDiviation is defined as mfxI32,
but target frame size (inputBitsPerFrame) is defined as mfxF64.
So it is rounded before BRC_ctx::totalDiviation calculation.
Error is accumulated on long stream.
=> [sw brc] Fixed rounding error accumulated on long stream.

builder/FindFunctions.cmake
This commit will fix adding of sha for files:
`mediasdk_file_version: 1.18.6.21.27c61fb`
Fix requested by @vshalimo
=> [cmake] Add right location for sha execution

_studio/mfx_lib/decode/mpeg2/src/mfx_mpeg2_decode.cpp
When BITSTREAM_COMPLETE_FRAME flag is set for input,
decoder trusts input too much, but later it works with
short input as it is end of stream.
In added check if input data size is less than picture
header and picture coding extension, it is dropped.
And finally ERR_MORE_DATA is returned from DecodeFrameAsync.
=> [mpeg2d] check when BITSTREAM_COMPLETE_FRAME is set

_studio/mfx_lib/shared/src/mfx_common_int.cpp, _studio/mfx_lib/vpp/src/mfx_vpp_sw_core.cpp, _studio/mfx_lib/vpp/src/mfx_vpp_utils.cpp, _studio/shared/include/mfx_config.h, _studio/shared/include/mfx_vpp_interface.h, _studio/shared/include/mfxstructures-int.h, _studio/shared/src/libmfx_allocator.cpp, _studio/shared/src/libmfx_allocator_vaapi.cpp, _studio/shared/src/libmfx_core.cpp, _studio/shared/src/mfx_vpp_vaapi.cpp, api/include/mfxstructures.h, samples/sample_common/include/sample_utils.h, samples/sample_common/src/sysmem_allocator.cpp, samples/sample_common/src/vaapi_allocator.cpp, samples/sample_vpp/src/sample_vpp_parser.cpp, samples/sample_vpp/src/sample_vpp_utils.cpp
- This is 8 bit planar format without alpha channel
- RGBP supported for VPP output only
- Main usage case is NV12->RGBP conversion
- Decoders and encoders do not work with RGBP format!
=> [vpp] Added RGBP format support

builder/FindITT.cmake, builder/FindPackages.cmake
Fixes: #338
ITT name variants:
* SEAPI uses libittnotify${arch}.so
* VTUne uses libittnotify.so
This change checks for both names.
=> Support both ITT library names variants

_studio/shared/mfx_trace/src/mfx_trace_utils_linux.cpp
Issue: https://github.com/Intel-Media-SDK/MediaSDK/issues/349
=> Use of /etc/mfx_trace configuration file was missed. Fixed.

_studio/mfx_lib/shared/src/mfx_mpeg2_encode_vaapi.cpp
This change should be merged along with respective driver change [pr87](https://github.com/intel/media-driver/pull/87)
=> [mpeg2e] Change macroblock_address calculation formula

samples/sample_hevc_fei/src/sample_hevc_fei.cpp
=> [HEVCe FEI] Non-zero NumRefActiveBL0/BL1 for GPB frames

_studio/mfx_lib/decode/h264/src/mfx_h264_dec_decode.cpp
Before this patch, it would segfault if it was called before initialization. Now, it returns cleanly.
=> Prevent crash when DecodeFrameCheck is called when m_isInit is false

samples/sample_hevc_fei_abr/include/abr_brc.h, samples/sample_hevc_fei_abr/include/fei_utils.h, samples/sample_hevc_fei_abr/include/hevc_fei_encode.h, samples/sample_hevc_fei_abr/include/hevc_sw_dso.h, samples/sample_hevc_fei_abr/include/sample_hevc_fei_defs.h, samples/sample_hevc_fei_abr/include/task.h, samples/sample_hevc_fei_abr/src/abr_brc.cpp, samples/sample_hevc_fei_abr/src/cmd_processor.cpp, samples/sample_hevc_fei_abr/src/hevc_fei_encode.cpp, samples/sample_hevc_fei_abr/src/hevc_sw_dso.cpp, samples/sample_hevc_fei_abr/src/pipeline_hevc_fei.cpp
Introduced new class for Look Ahead queue (not storing all history anymore, only required frames)
Clean up variable/class names, removed dead code
Added comments
Test results for LA BRC relative to HW BRC are following:
+4.54% of BD-Rate Y for real MSE (requires original YUV)
+3.19% for algorithm which approximate distortion with number of nonzero transform coefficients
=> Sample hevc fei abr refactor

samples/sample_hevc_fei_abr/include/abr_brc.h, samples/sample_hevc_fei_abr/include/fei_utils.h, samples/sample_hevc_fei_abr/include/hevc_fei_encode.h, samples/sample_hevc_fei_abr/include/hevc_sw_dso.h, samples/sample_hevc_fei_abr/include/sample_hevc_fei_defs.h, samples/sample_hevc_fei_abr/include/task.h, samples/sample_hevc_fei_abr/src/abr_brc.cpp, samples/sample_hevc_fei_abr/src/cmd_processor.cpp, samples/sample_hevc_fei_abr/src/hevc_fei_encode.cpp, samples/sample_hevc_fei_abr/src/hevc_sw_dso.cpp, samples/sample_hevc_fei_abr/src/pipeline_hevc_fei.cpp
Introduced new class for Look Ahead queue (not storing all history anymore, only required frames)
Clean up variable/class names, removed dead code
Added comments
Test results for LA BRC relative to HW BRC are following:
+4.54% of BD-Rate Y for real MSE (requires original YUV)
+3.19% for algorithm which approximate distortion with number of nonzero transform coefficients
=> [sample_hevc_fei_abr] Refactored design of LA BRC

samples/sample_hevc_fei/src/fei_predictors_repaking.cpp, samples/sample_hevc_fei/src/hevc_fei_encode.cpp
This is MediaSDK manual limitation.
=> Pass GPB frames with MFX_FRAMETYPE_P type

samples/sample_hevc_fei/src/hevc_fei_preenc.cpp
We always need to enable statistic output even if we don't need it at
application side.
MDP-45308
=> [HEVCe FEI] Workaround for PreENC driver bug

samples/sample_hevc_fei_abr/include/dso/bs_mem+.h, samples/sample_hevc_fei_abr/include/dso/hevc2_parser.h, samples/sample_hevc_fei_abr/include/dso/hevc2_struct.h, samples/sample_hevc_fei_abr/src/dso/hevc2_ssdata.cpp
It fixes "memset() clearing an object of non-trivial type"
warring.
=> [sample FEI ABR] GCC 8.1 warning fix

samples/sample_hevc_fei_abr/include/hevc_fei_encode.h, samples/sample_hevc_fei_abr/include/hevc_sw_dso.h, samples/sample_hevc_fei_abr/include/pipeline_hevc_fei.h, samples/sample_hevc_fei_abr/include/sample_hevc_fei_defs.h, samples/sample_hevc_fei_abr/src/pipeline_hevc_fei.cpp
Do not parse luma transform coefficients if not required
Avoid several copy constructor calls
=> [sample_hevc_fei_abr] Performance improvement

samples/sample_hevc_fei/src/fei_predictors_repaking.cpp, samples/sample_hevc_fei/src/hevc_fei_encode.cpp, samples/sample_hevc_fei/src/ref_list_manager.cpp, samples/sample_hevc_fei/src/sample_hevc_fei.cpp
MediaSDK treats GPB frames as P until it submits to driver. It helps
to distinguish options for GPB and B frames: NumRefActive for L0,
BRefType, PRefType. For the same reason MFX_FRAMETYPE_P is used for
GPB frames in sample_hevc_fei.
=> [sample_hevc_fei] Revert using MFX_FRAMETYPE_B for GPB frames in sample

_studio/mfx_lib/shared/src/mfx_session.cpp
-Safe release m_pScheduler, m_pSchedulerAllocated.
these pointers should be zeroid for avoid calls of unaccesible methods
=> Fix _mfxSession::Cleanup

_studio/hevce_hw/h265/include/mfx_h265_encode_hw_brc.h, _studio/hevce_hw/h265/src/mfx_h265_encode_hw_utils.cpp, _studio/mfx_lib/shared/include/mfx_brc_common.h, _studio/mfx_lib/shared/src/mfx_brc_common.cpp
Issue: MDP-46419
Test: manually
reflist was changed if B pyramid with one forward reference. L1 is correspondence field. Needed for better quality.
SW BRC:
-changes for inner bitrate: MaxFrameSize calculation was changed for B pyr field case (reduced), GopParams changing
-changes for all SW BRC: Layer+1 for second field.
=> [HEVC E]: fix for interlace (ref list and SWBRC)

_studio/hevce_hw/h265/src/mfx_h265_encode_hw_utils.cpp, _studio/mfx_lib/shared/src/mfx_brc_common.cpp
Issue: MDP-46419
Test: manually
reflist was changed: L1 is correspondence field.
SW BRC:
-changes for inner bitrate: MaxFrameSize calculation was changed for B pyr field case (reduced), GopParams changing
-changes for all SW BRC: Layer+1 for second field.
=> [HEVC E]: fix for interlace (ref list and SWBRC) - part 2

_studio/hevce_hw/h265/src/mfx_h265_encode_hw_par.cpp
Previously this functionality was disabled by a mistake.
=> [hevce] Enabled writing vui.colour_description_present_flag into bs

_studio/hevce_hw/h265/src/mfx_h265_encode_hw_par.cpp
Previously this functionality was disabled by mistake.
=> [hevce] Writing vui video_full_range and colour_descr into bs

samples/sample_multi_transcode/src/pipeline_transcode.cpp
Previously we released FileWriter object.
This looks like a misprint.
MDP-46563
=> [smt] Fixed behavior on ResetOutput

builder/FindGlobals.cmake
CMAKE_EXEC_LINKER_FLAGS is a misprint.
=> Pass "-pie" LD flag for executables

builder/FindGlobals.cmake
CMAKE_EXEC_LINKER_FLAGS is a misprint.
=> Pass pie LD flag for executables

_studio/mfx_lib/CMakeLists.txt
Fixes #426
Setting library version properties and installing target as
a LIBRARY makes sure that cmake will create required symbolic
links automatically.
=> build: properly name and install mediasdk library on Linux

_studio/hevc_fei/h265_fei/include/mfx_h265_fei_encode_hw.h, _studio/hevce_hw/h265/include/mfx_h265_encode_plugin_hw.h, _studio/mfx_lib/plugin/include/mfx_h264la_plugin.h, _studio/mfx_lib/plugin/include/mfx_vpp_plugin.h
Plugin type can be obtained by GetPluginParam call
=> [plugins] Remove GetPluginType method as it's not part of base interface

_studio/mfx_lib/shared/src/libmfxsw_vpp.cpp
VP failed to work due to a typo in a check
=> vpp: fix a typo in a recent refactor

samples/metrics_monitor/test/igt_load.cpp
=> metrics_monitor: use stdio.h instead of libio.h in the tests

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
-MaxNum_Reference1:  Maximum number of reference per
list1 supported. If number is n, that means list 1
can have maximum n reference. If number is 0 or
bigger than MaxNum_Reference0, it shall be
treated as MaxNum_Reference0.
=> [HEVC][lib] Fix for get valid MaxNum_Reference1

samples/sample_multi_transcode/src/pipeline_transcode.cpp
The issue was the following. In transcoding pipelines we don't use SafetySurfaceBuffers at all (they are used to pass surfaces from decoder to encoder if they are in separate threads, which isn' t a trancoding case (I mean pipelines with PipelineMode::Native)). So the class is holding a null pointer to such buffers  (m_pBuffer) in described scenario. The issue ONLY takes place in case if some pipeline will receive error status, that will result in stopping all the pipelines, including transcoding pipelines. If transcoding pipeline was at decode stage it will trigger NoMoreFrames function call (this is shared code between Trancode and Decode pipelines, so this call is sufficient for Decode case) that in result will lead to null pointer (m_pBuffer) dereferencing since Trancode pipelines …
=> Fixes for SMT

_studio/mfx_lib/encode_hw/mjpeg/src/mfx_mjpeg_encode_hw.cpp
-FourCC = YUY2, CromaFormat = YUV422 is supported input fomat for HW JPEG encode on Linux
-Tested manually
=> [MJPEGe] Enable encode YUY2 422H content for Linux

samples/sample_hevc_fei/src/sample_hevc_fei.cpp, samples/sample_hevc_fei_abr/src/cmd_processor.cpp
- Restored missing AdaptiveSearch in sample_hevc_fei_abr because it should be enabled when compared to legacy
- Set SearchWindow for PreENC separately for more accurate testing of this control's influence on HEVC FEI performance and quality
=> [sample_hevc_fei] Fix missed or incorrect setting cli options

tools/bs_parser_hevc/src/hevc2_dec.cpp
Standard allows I-slices with enabled IBC, which is effectively ignored.
Skip ref-list modification for I-slices to avoid exception.
=> [bs_parser_hevc] Support for I-slices with enabled IBC

api/opensource/mfx_dispatch/CMakeLists.txt
Fixes: #524 (mss2018_r2)
We got last encounter of MFX_VERSION_MINOR parsing mfxdefs.h while
we needed the first one.
(cherry picked from commit c64a955b0a20290bd6135bde079326a27414a300)
=> build: wrong medisdk version in .pc files

CMakeLists.txt
cmake_dependent_option defines an options if and only if other option
is defined. If other option is not defined, value will be initialized
to the given default and it can _not_ be changed. As a result we lost
opportunity to use such options as ENABLE_TEXTLOG directly without
ENABLE_ALL. This change fixes the behavior. cmake_dependent_options
is not the thing to use here.
=> Fix options behavior

samples/sample_multi_transcode/src/pipeline_transcode.cpp
Print message to console if session is forced to be stopped,
that will help to treat further MFX_ERR_MEMORY_ALLOC correctly
=> [SMT] Additional logging

builder/FindFunctions.cmake
-  [make_library] produces incorrect linker flags for STATIC library.
Linker error is '/usr/bin/ld: group ended before it began'.
RC is [make_library] adds "-Xlinker --start-group" only for SHARED
target but puts "-Xlinker --end-group" for any variant.
Issue: https://github.com/Intel-Media-SDK/MediaSDK/issues/531
Test: compilation
=> [builder]: fix [make_library] linker options

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
- Delete hardcode value for VAConfigAttribRTFormat because
function vaGetConfigAttributes get valid params for
attributes.
=> Delete hardcode value for VAConfigAttribRTFormat

samples/sample_common/src/plugin_utils.cpp
Fixes 'using the result of an assignment as a condition without parentheses' in clang 6.0.
I'm not sure that I'm right. But '| = 'looks strange in this context. The condition is always true, and impl is not used in the future, so the best way will be remove second condition at all.
=> clang: fixes 'using the result of an assignment as a condition without parentheses' 

_studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_utils.cpp
ICL and above platforms support REXT formats, so mentioned restriction should be conditional depending on HW
=> ICL and above support REXT formats

api/opensource/mfx_dispatch/src/main.cpp, api/opensource/mfx_dispatch/src/mfx_function_table.cpp
Fixed clang warnings in dispatcher:
'explicitly assigning value of variable' and 'suggest braces around initialization of subobject'
gcc 8.2 checked
=> Fixed clang warnings

samples/sample_multi_transcode/include/pipeline_transcode.h, samples/sample_multi_transcode/src/pipeline_transcode.cpp, samples/sample_multi_transcode/src/sample_multi_transcode.cpp
This information helps to identify first failed pipeline during application shutdown. Massive error messages creates noise which makes hard to restore the initial sequence of fails
=> [SMT] Print session to log in case of error

_studio/mfx_lib/shared/include/mfx_h264_encode_struct_vaapi.h, _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
Hardware-type detected in CreateAuxilliaryDevice(),
than it used to switch set the frame tolerance mode in SetRateControl() function
(for APL or CFL it is a "sliding window")
=> Sliding window frame tolerance mode for BXT

api/opensource/mfx_dispatch/include/mfx_dispatcher_defs.h
Fixed gcc8 warning 'specified bound depends on the length of the source argument'
First - Why was strncpy (not memcpy) used here? We exactly knows number of bytes to copy ...
Second - code still dangerous, we rely on the fact that the callers understands what it does
Maybe it should be replaced with simple **snprintf(to, to_size, "%s", from)** ?
(And, I think, this c-style code can be removed 376a72044859cdb42ecd19f096d0f5f91936ef60 )
=> gcc8 warning 'specified bound depends on the length of the source'

_studio/shared/umc/core/umc/include/umc_defs.h
=> Fixed incorrect cast in MFX_INTERNAL_CPY_S macro

_studio/mfx_lib/vpp/src/mfx_vpp_utils.cpp
Removed API version check for AYUV color format since it
was added/supported before API 1.27
=> [vpp] Updated check for AYUV color format

_studio/shared/src/mfx_vpp_vaapi.cpp
Another one place where PLATFORM_BXT is used
The goal is to clear mfx_config.h and replace mfx_common_linux_bxtmin.h with the cmake configuration file (like fastboot.cmake)
=> Deinterlacing on APL: BXT defines replaced with run-time APL detection

_studio/shared/umc/codec/h264_dec/include/umc_h264_frame.h, _studio/shared/umc/codec/h264_dec/src/umc_h264_frame.cpp, _studio/shared/umc/codec/h264_dec/src/umc_h264_task_supplier.cpp, _studio/shared/umc/core/umc/include/umc_structures.h
Some streams have incorrect log2_max_frame_num value.
So we can't remove _at once_ ST when a gap is detected.
Instead, remove them at a next I frame(as a potential recovery point)
or at SEI recovery point.
=> [h264d] Re-worked a recent fix for frame gap handling

_studio/mfx_lib/decode/vp8/include/mfx_vp8_dec_decode_vp8_defs.h, _studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw.cpp, _studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw_vaapi.cpp
The fix is to align changes in lib and in driver, that
improve use of bitcount and 1st partion size computation.
No more special code for count==8.
Should be merged together with lakulako/media-driver#1,
or with https://github.com/intel/media-driver/pull/239
Issue: MDP-46726
Test: manual, debug with driver
=> [vp8d] fix partition size

_studio/shared/src/libmfx_allocator_vaapi.cpp
Added VP8/VP9 encoder specific code of surface/buffer allocation
what fixes encoding issue with system memory
Issue: MDP-47083
Signed-off-by: Ekaterina Shiryaeva <ekaterina.shiryaeva.alexandrovna@intel.com>
=> [VP9] Fixed memory allocation issue

_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp, _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
Intention of GetExtBufferRef is to get ext buffers
from MfxVideoParam structure which always has full set
of extension buffers ("MfxHwH264Encode::GetExtBuffer" can't return zero).
So, for MfxVideoParam it's better to use function GetExtBufferRef()
instead GetExtBuffer(), we can wrap issues from static code analyze
to one place (body of function GetExtBufferRef()) instead several
places (every calling GetExtBuffer())
=> Replace GetExtBuffer() for MfxVideoParam - mfx_lib/shared/

_studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp
=> [h265d_umc] Fixed possible nullptr dereference

_studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp
Input value "par" already checked for nullptr
before every calling function GetPlatform(...).
Also, this pointer checked inside function
IsNeedPartialAcceleration(...)
=> [JPEGd] Remove extra nullptr checking

_studio/mfx_lib/encode_hw/mjpeg/src/mfx_mjpeg_encode_hw_utils.cpp
=> [JPEGe] Moved checking "core" to the beginning of the function

_studio/mfx_lib/shared/src/libmfxsw.cpp
Using of platform definitions removed from copyright strings. Copyright strings can be defined in cmake (like it was made before for plugins)
=> Using of platform definitions removed from copyright strings

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp, _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp
Dpb index was checked against NumRefFrame instead of array size
On ICL where NumRefFrame can be > DPB_SIZE led to assertion fail.
Issue: MDP-45453
=> [HEVCE] Fix possible DPB overflow

_studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
MFX_PICSTRUCT_UNKNOWN was used which couldn't be converted to
UMC type in BRC implementation. The change sets correct frame's
picstruct for BRC.
=> [h264e] Fix assert in encoding with MaxSliceSize

_studio/mfx_lib/decode/mpeg2/include/mfx_mpeg2_decode.h, _studio/mfx_lib/decode/mpeg2/src/mfx_mpeg2_decode.cpp
=> [mpeg2d] Improved robustness for using Opaque Memory

_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp, _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils.cpp, _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
Intention of GetExtBufferRef is to get ext buffers
from MfxVideoParam structure which always has full set
of extension buffers ("MfxHwH264Encode::GetExtBuffer" can't return zero).
So, for MfxVideoParam it's better to use function GetExtBufferRef()
instead GetExtBuffer(), we can wrap issues from static code analyze
to one place (body of function GetExtBufferRef()) instead several
places (every calling GetExtBuffer())
=> [h264e] Replace GetExtBuffer() to reference for MfxVideoParam

_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
SCD kernels support only planar 8-bit formats, so msdk should report
MFX_ERR_UNSUPPORTED on FourCCs other than planar 8-bit in case of
SCENE_CHANGE_DETECTION is involved in processing
=> [VPP] Fix VPP DI MFX_DEINTERLACING_ADVANCED_SCD mode support reporting

_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils_new.cpp
We can loose more useful error status from function
GetFrameHDL() upper, also nullptr can be processed
in the upper code.
Aligned the same function GetNativeHandleToRawSurface
with h265e
=> [h264e] Removed extra check nativeHandle for nullptr

_studio/shared/umc/codec/h265_dec/src/umc_h265_frame_info.cpp
Replace GetSlice() to directly using m_pSliceQueue
inside class H265DecoderFrameInfo where it's possible
=> [h265d_umc] Use m_pSliceQueue directly w/o GetSlice

_studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp, _studio/shared/umc/codec/vp9_dec/include/umc_vp9_utils.h, _studio/shared/umc/codec/vp9_dec/src/umc_vp9_utils.cpp, _studio/shared/umc/codec/vp9_dec/src/umc_vp9_va_packer.cpp
A VP9 stream starting w/ inter frame has it intra-coded without
references. Prior code led to error since the auxiliary ref frame array
was filled with VA_INVALID_SURFACE ids, which cannot be passed
to the GetSurfaceID functions.
=> [VP9] Fix PackPicParams for streams starting w/ inter frame

samples/sample_fei/src/pipeline_fei.cpp
Checking of the index for reset point was added into ResizeFrame function.
It allows to have correct number of the resizes into encoding pipeline.
=> [MDP-50731][AVC FEI] Add correct condition for reset point in the case with frame resize

_studio/mfx_lib/vpp/src/mfx_vpp_sw_core.cpp
Wrong condition on commit 8ee12dd7c5cbb48df992c83b572343c7a2bad914 when checking if composition has been enabled/disabled.
=> Fix condition in VPP reset when checking composition enable/disable changes.

samples/sample_common/include/sample_defs.h, samples/sample_fei/src/auxiliary_interfaces.cpp, samples/sample_fei/src/fei_encode.cpp, samples/sample_fei/src/fei_encpak.cpp, samples/sample_fei/src/fei_preenc.cpp, samples/sample_multi_transcode/src/pipeline_transcode.cpp
Currently the timeout used in SMT and sample_fei is 1500 seconds.
In regular case, it's even too much for task synchronization.
However in case of driver/MSDK synchronization problems,
SyncOperation may return MFX_WRN_IN_EXECUTION which was ignored.
It leaded to undefined behavior hard to debug.
So it's better to catch synchronization issues at once.
=> Return an error on warnings from SyncOperation

api/mfx_dispatch/linux/mfxloader.cpp
This should fix cases when application initializes mediasdk
with 0 implementation, i.e. with MFX_IMPL_AUTO.
=> mfx_dispatch/linux: allow MFX_IMPL_AUTO

_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
In case of FEI single field mode, only one ext buffer is attached.
MDP-48131
=> [avc fei] Fixed PWT in FEI single field mode

_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
Current commit includes removing of the
VA_ENC_SLICE_STRUCTURE_MAX_SLICE_SIZE from slice structure
reported by driver. It should be done for correct work of the MSDK
on Linux platform.
=> [AVCe] Fix conversion of the slice structure from VAAPI to MFX

_studio/mfx_lib/decode/h264/src/mfx_h264_dec_decode.cpp, _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp, _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils_new.cpp, _studio/mfx_lib/fei/h264_la/mfx_h264_la.cpp, _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp, _studio/shared/umc/codec/h264_dec/src/umc_h264_va_packer.cpp
Replaced memcpy with std::copy / operator =
=> Replaced memcpy with std::copy / operator = in AVC components

_studio/shared/umc/codec/vc1_dec/include/umc_vc1_dec_task_store.h, _studio/shared/umc/codec/vc1_dec/include/umc_vc1_video_decoder_hw.h, _studio/shared/umc/codec/vc1_dec/src/umc_vc1_video_decoder_hw.cpp, _studio/shared/umc/core/umc/include/umc_defs.h
THROWSEXCEPTION is empty and used only in umc_vc1_dec_task_store.h
Tested on gcc 8.2 and clang 6.0, not sure about icc.
=> clang 6.0: fixed warning: 'operator delete' has a non-throwing exception specification

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
DDI.NumActiveRefBL1 was L0.
Obvious and not affecting.
=> [HEVCE] fix copy-paste typo

_studio/mfx_lib/shared/src/mfx_mpeg2_encode_vaapi.cpp
Before fix only mpeg2e on Linux used target bitrate, while
other codecs/platforms used maxBitrate, which has more sense.
Now sps structure that has single bitrate field uses maxBitrate
too.
Issue: MDP-47087
Test: manual with VBR
=> [mpeg2e][linux] use maxBitrate for VBR

api/mfx_dispatch/linux/mfxparser.cpp
Fixes: #793
For multithreaded applications it is desirable to open files with
O_CLOEXEC specifier to avoid leaking them on the fork().
=> dispatcher: open plugins.cfg with O_CLOEXEC modifier

_studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_supplier.cpp
-If RawHeader_H265::m_buffer is empty - call Resize() and copy current header
to m_buffer
=> [h265d/UMC]Fix saving SPS/PPS

_studio/shared/umc/codec/h264_dec/include/umc_h264_frame.h, _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h, _studio/shared/umc/codec/h264_dec/src/umc_h264_frame.cpp, _studio/shared/umc/codec/h264_dec/src/umc_h264_task_supplier.cpp, _studio/shared/umc/core/umc/include/umc_structures.h
Some streams have incorrect log2_max_frame_num value.
So we can't remove _at once_ ST when a gap is detected.
Instead, remove them at a next I frame(as a potential recovery point)
or at SEI recovery point.
Issue: MDP-46557
Signed-off-by: ZhiZhen Tang <zhizhen.tang@intel.com>
(cherry picked from commit 5fec4d2d3bd58d19e89e7e9cadf23b14c5be3cfe)
=> [h264d] Re-worked recent fix for frame gap handling

_studio/shared/src/mfx_vpp_vaapi.cpp
Issue #803 
Driver should not use colorfill for tiled video wall (works on APL)
Upd:
m_pipelineParam[i].pipeline_flags |= VA_PROC_PIPELINE_SUBPICTURES;
m_pipelineParam[i].filter_flags |= VA_FILTER_SCALING_HQ;
works for both: APL, CFL and SKL
=> [VPP] black tiled video wall issue

_studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_ddi.h, _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw.cpp
The source and destination static arrays must have the same type
=> [vp9e] Fix std::copy applications

_studio/mfx_lib/decode/vc1/src/mfx_vc1_decode.cpp
Return MFX_ERR_UNSUPPORTED in case of complex profile (not covered by vc1 standart)
=> [VC1d] Add check after init in case of simple/main profile

_studio/mfx_lib/decode/mpeg2/src/mfx_mpeg2_decode.cpp
At EOS when 2nd field has corrupted header appeared that
outSurface exists and syncPoint is unassigned. It led to
ERR_NULL_PTR error from decoder and last surface
was lost.
(48200)
=> [mpeg2d] Avoid null syncpoint at EOS

CMakeLists.txt, README.md
The option was deemed redundant - BUILD_TESTS does the job already.
=> [build] Remove RUN_TESTS option

_studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw_utils.h
Encoded order for next frame is increment of the one for previous.
With 0xffffffff initialization first frame has EO 0 as expected.
=> hevce: fix encoded order calculation

_studio/shared/src/libmfx_core_vaapi.cpp
0x3EA5 is the Intel Iris Plus Graphics 655 processor in
the Intel Core i7-8559U.
=> Add new CFL device ID

samples/sample_hevc_fei/src/sample_hevc_fei.cpp
For display order (e.g. pipeline w/o preenc) reordering is
performed in library and SetCtrlParams is not called, so
there is no way to use per frame type controls for setting
ForceCtuSplit and FastIntraMode. Change restores setting them
as before commit 29d17bd.
=> [sample_hevc_fei] Fix regression caused by 29d17bd

tools/asg-hevc/src/test_processor.cpp
Unsafe sscanf caused a build error on windows, it was replaced by using istringstream object for further parsing.
=> [ASG HEVC] Replaced unsafe sscanf function

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp, _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
Issue: 49068
Test:  manually (beh test is needed)
If BufferSizeInKB==0 && InitialDelayInKB!=0
then BufferSizeInKB should be set >= InitialDelayInKB
=> [AVCe, HEVCe] Fix for Default BufferSizeInKB calculation

_studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp
JPEG with CHROMAFORMAT_YUV444 and COLORFORMAT_YCbCr is being decoded by APL hardware.
Test: MDP-51112
=> [JPEG] Turning on hardware decoding with YCbCr&&YUV444 color format

_studio/mfx_lib/cmrt_cross_platform/include/cmrt_cross_platform.h, _studio/mfx_lib/cmrt_cross_platform/src/cmrt_cross_platform.cpp, _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_cm.cpp
add lookahead execution with SSEU on ICL
=> add lookahead execution with SSEU on ICL

_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
Issue: MDP-49070
Test:  manually
adding IDR or REF attribute
if it is needed.
=> [AVCe] fix for frameType in DisplayOrder

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
If NumRefFrame is not given, PPyrInterval computed with uninitialized
NumRefFrame can differ. After NumRefFrame is assigned PPyrInterval to
be updated.
PPyrInterval affects DPB control. The commit fixes RefLists in
LowPower mode.
(45453)
=> [HEVCE] update PPyrInterval after NumRefFrame change

samples/sample_encode/include/pipeline_encode.h, samples/sample_encode/src/pipeline_encode.cpp, samples/sample_encode/src/sample_encode.cpp
Usage: ./sample_encode <...> -icq N   # N=1..51
=> icq: enable support in sample_encode

samples/sample_common/src/vaapi_allocator.cpp
BGR4 was added in libmfx_allocator_vaapi.cpp (shared/src), but does not in vaapi_allocator (sample_common)
Issue: MDP-47046
=> [JPEGE] BGR4 in vaapi_allocator

samples/sample_multi_transcode/include/pipeline_transcode.h, samples/sample_multi_transcode/include/sample_multi_transcode.h, samples/sample_multi_transcode/src/pipeline_transcode.cpp, samples/sample_multi_transcode/src/sample_multi_transcode.cpp
Old mechanism used pthread_cond_timedwait()/pthread_cond_signal() to wait till end
of all threads executions. pthread_cond_signal() issued only once at the end of each
thread execution but the signal has no effect if the main thread is not blocked on
corresponding pthread_cond_timedwait. As a result smt could hang in the infinite loop.
=> [smt] fixed hang in threads waiting mechanism

_studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp
To initialize the default values, need to use m_vInitPar instead of m_vPar.
Otherwise, the new values will not be used.
=> [VP9d] Fix of AspectRatio initialization

_studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw.cpp, _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_par.cpp, _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp, api/include/mfxstructures.h, api/mediasdk_structures/ts_struct_decl.h
For now dynamic scaling is always ON so it leads to additional allocation on driver side to support such scenario. Was added key app should set if dynamic scaling feature is needed.
=> [VP9e] Added dynamic scaling flag

_studio/shared/umc/codec/vc1_dec/src/umc_vc1_video_decoder.cpp
In case of complex profile Init() will return UMC_ERR_UNSUPPORTED, but we nowhere process this situation. As a result - we get sefault.
=> vc1d: Add check after Init

tests/mfx_dispatch/linux/mfx_dispatch_test_cases_plugins.cpp, tests/mfx_dispatch/linux/mfx_dispatch_test_main.cpp, tests/mfx_dispatch/linux/mfx_dispatch_test_main.h, tests/mfx_dispatch/linux/mfx_dispatch_test_mocks.cpp, tests/mfx_dispatch/linux/mfx_dispatch_test_mocks.h
Added return status check and check the number of function calls in test of loading plugin. Before the changes in ShouldLoadFromGoodPluginsCfgCorrectly case only one function (dlopen) was called and returned error. The case was considered successful, but it is wrong.
=> [dispatcher_test] Strengthening of plugin test requirements

_studio/mfx_lib/shared/src/mfx_session.cpp
-Fix possible issue: during destroy instance of scheduler may be used m_pCore,
so need release m_pCore only after scheduler
=> CORE: Release Scheduler before Core

_studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp
Temporal layers buffer should be sent to driver before frame rate/rate control
buffers.
=> [VP9e] Fix the order of parameter buffer submission

_studio/mfx_lib/decode/mpeg2/src/mfx_mpeg2_decode.cpp, _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_dec.cpp, _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_dec_pic.cpp
Changed verification logic. During DecodePictureHeader any
error sets skip flag and keeps decoder buffers unmodified.
Also recovery logic doesn't rely on invalid parameters.
Several logic expression are simplified.
(33394)
=> [mpeg2d] improve corruption check

samples/sample_common/include/vaapi_device.h, samples/sample_common/include/vaapi_utils.h, samples/sample_common/src/vaapi_device.cpp, samples/sample_common/src/vaapi_utils_x11.cpp
Fix failure on CentOS 7.5: primary drm node was created for libdri,
but it lacks permissions required for ioctl(.., DRM_IOCTL_I915_GETPARAM)
to run.
=> Pass to libdrm render node, not primary node

_studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp
Delete bad resolution check in MFX_JPEG_Utility::IsNeedPartialAcceleration function in _studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp.
Check of resolution implemented in IsGuidSupported function.
The call functions comes from MFX_JPEG_Utility::GetPlatform.
=> Delete bad resolution check in mjpeg decode

_studio/mfx_lib/scheduler/include/mfx_scheduler_core.h, _studio/mfx_lib/scheduler/src/mfx_scheduler_core_thread.cpp, _studio/mfx_lib/shared/src/libmfxsw.cpp, _studio/mfx_lib/shared/src/libmfxsw_vpp.cpp
Some variables and parameters are created only for using
within MFX_AUTO_LTRACE, MFX_LTRACE_P, MFX_LTRACE_S and other macros.
If MFX_TRACE_ENABLE is not defined, such variables are marked
by compiler as "unused variable" and if the warnings are treated
as errors the build is failed.
The patch is one of the options how to resolve this issue.
=> Resolve "unused variable" warnings for MFX traces

_studio/mfx_lib/shared/src/mfx_common_int.cpp, _studio/mfx_lib/shared/src/mfx_vpx_dec_common.cpp
AYUV FourCC should not be guarded with MFX_VERSION >= 1027
Get rid of duplicate VP9 CheckVideoParam else branch.
=> [VP9d] Fix AYUV FourCC and CheckVideoParam

_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils.cpp, _studio/mfx_lib/shared/include/mfx_h264_encode_struct_vaapi.h, _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp, _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp, samples/sample_encode/include/pipeline_encode.h, samples/sample_encode/src/pipeline_encode.cpp, samples/sample_encode/src/sample_encode.cpp
./sample_encode h264 -i xxx.yuv -o xxx.h264 .....-avbr -b TargetBitrate
-convergence Convergence -accuracy Accuracy
Convergence is in the unit of frame
Accuracy should be in [1, 100]
Change-Id: Ic57cf2c213a9345328d2b91d9bf455bec3283360
=> AVBR: enable support for AVC in core library and sample_encode

_studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp
Fixed hardcoded caps because driver doesn't support multiple pipes scalability.
=> [VP9e] Fixed hardcoded caps for tiles

_studio/mfx_lib/mctf_package/mctf/src/mctf_common.cpp
Added check to make sure that iterator is inside mfxSurfPool
=> mctf: fixed static analysis issue

samples/sample_hevc_fei_abr/src/dso/hevc2_parser.cpp, tools/bs_parser_hevc/src/hevc2_parser.cpp
std::thread::hardware_concurrency may return 0 if it fails to get info from HW
=> hevc_parser: fixed static analysis issue

_studio/shared/umc/codec/vc1_dec/src/umc_vc1_video_decoder_hw.cpp
MediaSDK return MFX_ERR_NONE in spite of vaEndPicture return error
=> vc1d: Added check after vaEndPicture

samples/sample_common/src/vaapi_device.cpp
fixed unused variable warnings in static analysis
[test_results.json.txt](https://github.com/Intel-Media-SDK/MediaSDK/files/2651789/test_results.json.txt)
=> [samples] fixed static analysis issues

_studio/mfx_lib/vpp/src/mfx_vpp_utils.cpp
Removed platform check for AYUV color format since it
was added/supported before ICL
Signed-off-by: Wang, Chengwei C <chengwei.c.wang@intel.com>
=> [VPP] Remove platform check for AYUV color format

_studio/mfx_lib/decode/h264/include/mfx_h264_dec_decode.h, _studio/mfx_lib/decode/h264/src/mfx_h264_dec_decode.cpp, _studio/shared/umc/codec/h264_dec/src/umc_h264_task_supplier.cpp, _studio/shared/umc/codec/h264_dec/src/umc_h264_va_supplier.cpp
- Decoder triggered 'global task' not only when
it needs to force async. operation completion
but every time it needs more work surfaces.
When blocking sync. is used this leads to
[SyncOperation] call may take more time than it
really needed. In current patch we use the same
approach as it is in h265d component.
Issue: MDP-41203
Test: full decoding & transcoding validation
=> h264d: fix async model

_studio/mfx_lib/fei/h264_la/mfx_h264_la.h
Fixes: 92227f5 ("[scheduler] Replaced soft polling with events driven scheme")
=> [LA] Changed threading policy to DEDICATED

samples/sample_fei/src/fei_encode.cpp
eTask pointer is never NULL anymore. Removed logic is a leftover from times when Encode in Encoded Order didn't use eTask
=> AVC FEI: fixed pointer check logic

_studio/mfx_lib/decode/mpeg2/include/mfx_mpeg2_decode.h, _studio/mfx_lib/decode/mpeg2/src/mfx_mpeg2_decode.cpp, _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_dec_pic.cpp
Improve robustness and recovery for very corrupted content.
No error on size < init.size; accept broken SequenceHeaderExtension
in between, accept SH if next frame is invalid, returned
RestoreDecoder after early caught errors.
=> [mpeg2d] improve pipeline robustness

_studio/shared/umc/codec/h265_dec/include/umc_h265_bitstream_headers.h, _studio/shared/umc/codec/h265_dec/include/umc_h265_slice_decoding.h, _studio/shared/umc/codec/h265_dec/include/umc_h265_va_packer.h, _studio/shared/umc/codec/h265_dec/src/umc_h265_bitstream_headers.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_va_packer.cpp
Cleanup packer interface, remove redundant method args,
use unsigned types & const whenever it's possible
Issue: MDP-52201
Test: hevcd_conf, hevcd_sbe, hevcd_conf_allegro, hevcd_afl_broken
=> h265d: cleanup VA packers

_studio/mfx_lib/decode/vp9/include/mfx_vp9_dec_decode_hw.h, _studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp, _studio/mfx_lib/shared/src/mfx_vpx_dec_common.cpp
Make reference frames are locked (increase reference counter)
before UpdateRefList.
UpdateRefList prepares the references for the next frame and
removes frames from the current list, when it removes it calls
DecreaseRefCount function.
If frame refCount is zero Free function is called
this function clears Locked member and the reference frame
could be used as new target frame
while still in use by HW decoder.
Issue: MDP-52110
Test: Linux/ICL
=> [vp9d] Lock reference frames before UpdateRefList

_studio/mfx_lib/encode_hw/mpeg2/src/mfx_mpeg2_encode_utils_hw.cpp
IsGuidSupported has third parameter isEncoder need for windows only
Issue: MDP-52519
=> Update check for support mpeg2e on BXT

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
On Gen10+ VDEnc SAO for only Luma/Chroma in CQP mode
isn't supported by driver
=> [hevce] SAO luma/chroma unsupported for CQP

_studio/mfx_lib/shared/src/mfx_vpx_dec_common.cpp
If the aspect ratio is not set by the user (contains zero values)
then treat it as (1,1).
If the user set the aspect ratio
then check it is valid (AspectRatioW != 0 and AspectRatioH != 0)
Change-Id: I5007707e986d21c366a1f4e40db45fb2a1fdc077
=> Fix aspect ratio checks

_studio/shared/umc/io/umc_va/src/umc_va_linux.cpp
When MFX_VERSION < 1027 va_size is set to zero and vaCreateBuffer return error
=> hevcd: Fixed playback

_studio/shared/src/mfx_vpp_vaapi.cpp
Attempt to finish the initial thing with which the work began (remove BXT hardcoding). We have API for enable/disable colorfilling already.
=> [VPP] depricated platfrorm-dependent code removed

_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
-CheckVideoParamQueryLile() should not set default values
-Move all check to the function - CheckMaxFrameSize()
port from close source: 24e19e5
=> h264e: Rework check MaxFrameSize

CODEOWNERS
After moving source code for hevc (both legacy and FEI),
CODEOWNERS has become inaccurate and reviewers were not set
for new commits.
=> Fix CODEOWNERS for hevc component

_studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw.cpp
Fixes: 88f8b98cf0a280efb35d54da4843d713438ecf84 ("vp8: Fixed vp8 playback")
=> vp8d: Fixed incorrect computation of 1st partition size

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
SAO is enabled for ICL with CQP mode
=> HEVC VDEnc: SAO is enabled for ICL with CQP mode

_studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp, _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp, _studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp, _studio/mfx_lib/shared/src/mfx_mpeg2_encode_vaapi.cpp
Previous logic was dangerous, after vector resizing access to elements with [] could lead to out of bounds read.
Such situation appears if new buffer added without vector resize adjustment
=> Use vector in execute

_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
-Replace GetExtBuffer() by GetExtBufferRef for avoid possible
dereferencing nullptr
=> h264e: fix possible dereferencing nullptr

_studio/shared/umc/codec/h265_dec/include/umc_h265_frame.h, _studio/shared/umc/codec/h265_dec/src/umc_h265_frame.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_va_packer.cpp
frame and pSlice->GetCurrentFrame() are the same
=> hevcd: Removed deprecated logic from packer

_studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp
DRC mode may interrupt SuperFrame decoding process.
And some frames of SuperFrame may be lost.
If it happened decode the frame again.
Issue: vsmgwl-11943
Test: manual vp9d_8b_420_nv12_difresol-plugin_vp9dhw
=> [vp9d] Fix DRC and SuperFrame decoding

_studio/mfx_lib/decode/vp9/include/mfx_vp9_dec_decode_hw.h, _studio/mfx_lib/shared/src/libmfxsw_decode.cpp
MFXVideoDECODE_DecodeHeader should call VP9 specific
DecodeHeader function, to do so the function must be
static, like it was done for other decoders H264, H265.
Issue: vsmgwl-10697
Test: vp9d_*_format_change./*
=> [vp9d] Make DecodeHeader static function

_studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp, _studio/shared/src/mfx_umc_mjpeg_vpp.cpp
YUY2 is supported by HW, correct places where fallback to SW occur.
Issue: MDP-52615
=> [mjpeg] Fix HW support of YUY2

_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp, _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp, _studio/shared/include/mfx_config.h
Requires: intel/media-driver#319
(cherry picked from commit 7a1a3061d5933f30413c1b2d91f5b09a76bf016f)
=> h264e: enable QVBR rate control

_studio/mfx_lib/vpp/src/mfx_vpp_utils.cpp
Some 10b color formats (Y210) work in the shifted position.
Incorrect comments were updated.
=> [VPP][10b] Update incorrect comments

_studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp, _studio/shared/src/libmfx_allocator_vaapi.cpp, samples/sample_common/src/vaapi_allocator.cpp
Buffer for segmentation map should be created as 2D buffer with picture width/
height in MB. Picture width has to be with 64 bytes alignment.
=> [VP9e] Fixed buffer creation for segmentation map

CMakeLists.txt
Fixes: #1165
cmake option() rewrites set() without FORCE flag which we tried
to use to instuct gtest to avoid installation path.
=> build: do not install gtest

_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils.cpp, _studio/mfx_lib/shared/include/mfx_h264_encode_struct_vaapi.h, _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp, _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp, samples/sample_encode/include/pipeline_encode.h, samples/sample_encode/src/pipeline_encode.cpp, samples/sample_encode/src/sample_encode.cpp
./sample_encode h264 -i xxx.yuv -o xxx.h264 .....-avbr -b TargetBitrate
-convergence Convergence -accuracy Accuracy
Convergence is in the unit of frame
Accuracy should be in [1, 100]
Change-Id: Ic57cf2c213a9345328d2b91d9bf455bec3283360
(cherry picked from commit 0e04f5606f6cbfcbcc3c9736d40964111ba87fb7)
=> AVBR: enable support for AVC and support in sample_encode

_studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_decoder.cpp
Check status from DecodeHeaders before completion of current frame
because a new picture header can be corrupted and therefore skipped.
=> [mpeg2d] Fix for corrupted content

_studio/shared/umc/codec/h265_dec/include/umc_h265_nal_spl.h, _studio/shared/umc/codec/h265_dec/src/umc_h265_nal_spl.cpp
No sense of taking min with 0 for unsigned types (difference of two ```size_t``` is still ```size_t```)
=> Fix truncation

_studio/shared/umc/codec/mpeg2_dec/include/umc_mpeg2_decoder.h, _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_decoder.cpp
In case of absent of a free frame
we need to save current slice for later processing.
=> [mpeg2d] Fix for missing slice

samples/metrics_monitor/test/cttmetrics_gtest.cpp, samples/metrics_monitor/test/device_info.h, samples/metrics_monitor/test/i915_pciids.h, samples/metrics_monitor/test/igt_load.cpp
Earlier scheme of decoding device id to get GT size
doesn't work on some platforms anymore,
so they are were determined in platform tables.
Issue: MDP-51279
=> [test_monitor] intel_gt(dev_id) function fixed

_studio/mfx_lib/vpp/src/mfx_vpp_utils.cpp
This commit fixes previous (UYVY was disabled for any platforms except ICL by mistake)
=> [VPP] UYVY enable fix

_studio/shared/umc/codec/h265_dec/include/umc_h265_headers.h
-Add initialization HeaderSet::m_Header
=> h265d: fix static analysis warning

_studio/mfx_lib/shared/src/mfx_vpx_dec_common.cpp
-Changed MFX_VPX_Utility::QueryIOSurfInternal()
required num surfaces =  (max num references) + AsyncDepth + 1
=> vp9d: fix calculation number of required surfaces

samples/sample_common/src/plugin_utils.cpp
-On Android implementaion of HEVC encoder is placed in libmfx
That's why we don't need default plugins for this codec
=> samples: avoid loading default plugin for HEVCe on Android

_studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw_vaapi.cpp
A signed integer is required when updating loop filter level for
segmentation however picParams->loop_filter_level[i] is an unsigned
integer
=> vp8d: don't convert a signed integer to an unsigned integer

_studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp, _studio/mfx_lib/decode/vc1/src/mfx_vc1_decode.cpp, _studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw.cpp, _studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp
-Add reporting type of decoded frame via extended buffer
MFX_EXTBUFF_DECODED_FRAME_INFO
Fixes: #333
=> vp8d/vp9d/vc1d: add report decoded FrameType

_studio/mfx_lib/vpp/src/mfx_vpp_utils.cpp
This fixes the regression caused by b49b03b3.
=> vpp: UYVY can be used as output

doc/samples/Media_Samples_Guide_Linux.md, doc/samples/Media_Samples_Guide_Linux.pdf
Updates to Media Samples Guide. Note: including markdown document source to align with other repo documents and make this guide easier to maintain.
=> [samples][docs] updates to Media_Samples_Guide_Linux.pdf, adding markdown

_studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_vaapi.h, _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp, _studio/mfx_lib/encode_hw/mjpeg/include/mfx_mjpeg_encode_vaapi.h, _studio/mfx_lib/encode_hw/mjpeg/src/mfx_mjpeg_encode_vaapi.cpp, _studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_vaapi.h, _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp, _studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h, _studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp, _studio/mfx_lib/shared/src/mfx_mpeg2_encode_vaapi.cpp, _studio/shared/include/mfx_utils.h
This PR replaces macro which ignored returned status with function that handles it.
All components patched. Fixes #1065
=> Destroy va buffers correctly

samples/sample_common/src/sample_utils.cpp
m_fDestMVC is allocated as array
=> sample_common: fix mismatched new [] / delete

_studio/mfx_lib/decode/vp9/include/mfx_vp9_dec_decode_hw.h, _studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp
-Remove VideoDECODEVP9_HW::m_*_delta_q as duplicate,
current values already stored in m_frameInfo
=> vp9d: fix InitDequantizer() for DRC

_studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_vaapi.h, _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp
After reset driver keep using old temporal layers and it leads to FPE. 
Driver still using temporal layers, even we don't send them in next cycle and had cleared temporal layers structure. We can clear temporal layers structure and send it (empty) in first sequence parameters update after reset to avoid it.
MDP-52486
=> [vp9e] update temporal layers after reset

_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
This fixes latest FEI ENCPAK issues
=> h264e, avc fei: prevent shrinkage of preallocated array to 0

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp, _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp, _studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp, _studio/mfx_lib/shared/src/mfx_mpeg2_encode_vaapi.cpp
These types are defined in VA headers, so no cast is required
=> VA: remove unnecessary cast for VA buffers type

_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
Expression in assert always true, because expression's left part is 32bit type and this is less than 0x100000000 (= 2 ^ 36).
=> [h264][ENC] Fix warnings

_studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h, _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
-If UseRawRef = OFF/UNKNOWN on Init/Reset, this flag must be ignored on runtime
=> h264e: fix setting CO2::UseRawRef

_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
-AdaptiveMaxFrameSize can't be ON if MaxFrameSizeP = 0 or LowPower is ON
=> h264e: restore check adaptive max frame size

samples/sample_encode/include/pipeline_encode.h, samples/sample_encode/src/pipeline_encode.cpp, samples/sample_encode/src/sample_encode.cpp
New test suite: sample_encode_vp9e_tile
=> [sample_encode] Enable tiles for VP9 encoder

_studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp
Can been removed when VA surface reallocation patch implemented.
MDP-53745
=> [VP9D] resolution change check removed if VA used

_studio/shared/src/mfx_vpp_vaapi.cpp
```CheckAndDestroyVAbuffer``` assigns ```VA_INVALID_ID``` after buffer deallocation.
Old value should be used for buffer removing from pipe
=> vpp vaapi: Fix buffer removal from pipe

_studio/mfx_lib/cmrt_cross_platform/include/cmvm.h
-variable uint (unsigned int) always >= 0,
so assert(variable >= 0) is equal assert(1)
=> cmrt: remove useless asserts

_studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp
Current error status might be overwritten by ```CheckAndDestroyVAbuffer``` return status
=> AVC FEI PAK: Fixed possible error status loss

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
Default MBBRC behavior is restored (unknown - lin, on - win).
MBBRC is switched off on LowerPower
=> HEVCE: MBBRC fix

samples/sample_common/include/base_allocator.h, samples/sample_common/include/sample_utils.h, samples/sample_common/src/base_allocator.cpp, samples/sample_multi_transcode/include/pipeline_transcode.h, samples/sample_multi_transcode/src/pipeline_transcode.cpp, samples/sample_plugins/rotate_cpu/src/plugin_rotate.cpp
Replaced MSDKMutex with std::mutex and appropriate guards in most trivial cases
=> samples: use std syncronization primitives

_studio/mfx_lib/decode/vp9/include/mfx_vp9_dec_decode.h, _studio/mfx_lib/decode/vp9/include/mfx_vp9_dec_decode_hw.h, _studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode.cpp, _studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp
DecodeHeader and UpdateVideoParam functions
set Shift to one for planar formats
but didn't clear it for packed formats (like Y410).
Issue: vsmgwl-10697
Test: vp9d_*_format_change./*
=> [vp9d] Clear mfx.Shift for packed format

_studio/mfx_lib/shared/src/mfx_session.cpp, _studio/mfx_lib/vpp/include/mfx_vpp_hw.h, _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp, _studio/shared/include/libmfx_core_vaapi.h, _studio/shared/src/libmfx_core_vaapi.cpp
=> [vpp] Enable copy pass thru for VAAPI

samples/sample_decode/src/pipeline_decode.cpp, samples/sample_encode/src/pipeline_encode.cpp, samples/sample_multi_transcode/src/pipeline_transcode.cpp
Function 'printf' can accepts format string that may be influenced by user, causing format string vulnerability. To fix this issue a specification for character string added in 'printf' format string.
=> To fix security issue in 'printf' function call

_studio/shared/src/libmfx_core.cpp
Incorrect width was provided to CopyAndShift.
=> CopyAndShift out-of-bounds is fixed

CMakeLists.txt, tests/mfx_dispatch/linux/CMakeLists.txt
This attempts to fix:
* Avoid loading system level gtest.so if we were built against our internal copy
* Allow "blind" usage of system level gtest
=> Fix gtest usage

samples/sample_multi_transcode/include/pipeline_transcode.h, samples/sample_multi_transcode/src/pipeline_transcode.cpp, samples/sample_multi_transcode/src/transcode_utils.cpp
This is to enable tiles for HEVC encoder in sample_multi_transcode.
=> [sample_multi_transcode] Enable tiles for HEVC encoder

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
has_emulation_bytes reset to zero in all cases, it can not have other values
=> [h265e] Corrected assertion

_studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp
Size limits are driver-dependent, they are checked in
VideoDECODEMJPEGBase_HW::CheckVPPCaps().
Issue: MDP-52482
=> [jpegd] Drop hardcoded size limits for enabling software fallback

samples/sample_multi_transcode/include/pipeline_transcode.h, samples/sample_multi_transcode/src/pipeline_transcode.cpp, samples/sample_multi_transcode/src/transcode_utils.cpp
- ```mfxExtVP9Param``` was introduced in API 1.26
- added API 1.29 guards around tiles input parameters processing (since real logic in code was already covered by such guards)
=> smt: add API guards around mfxExtVP9Param usage

_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
In some cases where LookAheadDS is out of range we get MFX_ERR_NONE. For example
if LookAheadDS=4 we don't get errors because LaDSenumToFactor returns valid
value=4 as is the case MFX_LOOKAHEAD_DS_4x. But it isn't right due to
MFX_LOOKAHEAD_DS_4x=3 by enum, so we need to check LookAheadDS.
=> Added check valid value of LookAheadDS

_studio/shared/src/libmfx_allocator_vaapi.cpp
When creating a surface with fourcc setting to VA_FOURCC_P010, the format is expected to VA_RT_FORMAT_YUV420_10
Issue #906
=> [vaapi] minor update for P010 format in allocator

samples/sample_multi_transcode/include/pipeline_transcode.h, samples/sample_multi_transcode/include/transcode_utils.h, samples/sample_multi_transcode/src/pipeline_transcode.cpp, samples/sample_multi_transcode/src/transcode_utils.cpp
New test suite: smt_hevcd_to_hevce_temporal_layers
Add new switches for temporal layers
Update par file parsing to handle string literals
WA for compiler error on Windows - too many if-else
clauses in cmd-line parsing causes build error
=> sample_multi_transcode: enable HEVC encode with temporal layers

_studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_par.cpp
bufferSizeInKb is used before its default values is set, so default value of initialDelayInKb isn't set correctly.
=> [VP9e] Fix setting default value of initialDelayInKb

_studio/shared/include/mfxvideo++int.h
Fix for #1398
On Ubuntu 19.04 compiler (gcc-8.3.0) aligns GUID stucture size which
we defined internally in mediasdk by 8 and does not zero out the
structure when allocated on stack. As a result when we use current
approach to compare guids via !memcpy(a,b,sizeof(GUID)) we actually
compare unitialized regions and mistakenly think some guids not
equal which leads to runtime errors. For example, we might fail
to enable LowPower encoding on this command line:
sample_encode h264 -w 176 -h 144 -f 30 -cqp \
-qpi 30 -qpp 30 -qpb 30 -qsv-ff -nv12 -i a.yuv -o a.264
=> Make sure to compare guids correctly

samples/sample_common/include/vaapi_utils.h, samples/sample_common/src/vaapi_device.cpp, samples/sample_common/src/vaapi_utils.cpp
Fixes: #1396
In case of X11 DRI3 we try to directly render output surfaces via memory
sharing mechanism. For that we extract DMA buffer handle (file descriptor)
from video surfaces and create XCB pixmap from it, but this operation
might fail since rendering scanout might not be supported for some color
formats we use for media. For example, typically we decode into NV12 which
is not supported for scanouts. Hence the following might fail:
sample_decode h264 -i input.264 -r -f 30
Before this patch user will see the following error which is not very
descriptive:
X Error of failed request:  BadAlloc (insufficient resources for operation)
Major opcode of failed request:  149 ()
Minor opcode of failed request:  2
Serial number of failed request:  19
Current serial number in output stream:  22 …
=> sample_decode: check and report errors in case of X11 DRI3 rendering

_studio/mfx_lib/mctf_package/mctf/src/mctf_common.cpp
CreateQueue(Ex) is called at init of MCTF, but later when
the kernel has been configured for operation the code had
extra CreateQueue calls, which reset the original queue,
this is an issue on ICL because ICL requires special queue
creation by using CreateQueueEx. By removing the additional
CreateQueue calls the original queue (properly configured)
is not reset and MCTF works correctly.
Issue: MDP-48160
Test: vpp_mctf_denoise
Signed-off-by: Sebastian Possos <sebastian.possos@intel.com>
=> [MCTF - ICL] Removal of excess CreateQueue calls

_studio/shared/src/libmfx_core_vaapi.cpp
Aligned with commit https://github.com/intel/media-driver/tree/7679797bcf6ce498520f623d435577385d024b67
Including 0x8A70 removal from list.
=> Update ICL device Ids

_studio/shared/umc/codec/h265_dec/src/umc_h265_va_packer.cpp
slice params was packing incorrectly in case of rext and numSlices >1
pointers to base & rext params should be obtained after sliceParamsExt increasing, not before
=> [HEVCD] rext params multislice packing fix

_studio/mfx_lib/shared/include/mfx_h264_encode_struct_vaapi.h, _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp, _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
This reverts commit 47c6ca6da2de877f0b6b63b3c98d4c50de3de3b6,
as the state must be saved in a different place.
=> Revert "[h264e] Report/check VBR and CBR support via caps"

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw.cpp, _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw.cpp
This allow 8k encoding
Issue: MDP-52033
Test: beh_hevce_10b_444_y410_big_resolution-plugin_hevcehw-lowpower
Change-Id: I33469058589f1d01febcfeb58b04091bbf410d2c
=> [Encode] Changed rules for AYUV&Y410 reconstructed surfaces allocation

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw.cpp, _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw.cpp
Reverts Intel-Media-SDK/MediaSDK#1441
Following media-driver change: https://github.com/intel/media-driver/commit/9c32273adfd50268683b3d4658b0b143aca231e4
=> Revert "[Encode] Changed rules for AYUV&Y410 reconstructed surfaces allocation"

samples/metrics_monitor/CMakeLists.txt
Fixes: #1446
cmake-3.6 doesn't respect a minimal version specified for a component.
It doesn't work properly for constructions like:
pkg_check_modules(PKG_AAA AAA>=1.2.3)
if( PKG_AAA_FOUND)
endif()
So let's use this instead as a workaround:
if( ${PKG_XXX_VERSION} VERSION_GREATER 1.2.2 )
=> [metrics_monitor] Use VERSION_GREATER for version checking

_studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp
It is allocated through internal allocator and will be destroyed there
=> vp9e: prevent double destroy of m_segMapBufferId buffer.

_studio/mfx_lib/encode_hw/h265/include/hevce_ddi_main.h, _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw.h, _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw_ddi.h, _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw_utils.h, _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_vaapi.h, _studio/mfx_lib/encode_hw/h265/include/mfx_h265_fei_encode_hw.h, _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw.cpp, _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_ddi.cpp, _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp, _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp, _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
We can not modify ENCODE_CAPS_HEVC struct, but need to add new BRC
checks in caps. This commit contains new struct (with encode_caps_hevc
inside) and code refactor to work with it
Issue: MDP-53880
=> [hevce] Report/check VBR/CQP/CBR/ICQ support via caps

_studio/mfx_lib/Android.mk, _studio/mfx_lib/CMakeLists.txt, _studio/mfx_lib/decode/mpeg2/src/mfx_mpeg2_decode.cpp, _studio/mfx_lib/plugin/CMakeLists.txt, _studio/shared/include/libmfx_core_hw.h, _studio/shared/src/libmfx_core_hw.cpp, _studio/shared/src/libmfx_core_vaapi.cpp
- Align `ChooseProfile` function w/ current impl.
of `VAAPIVideoCORE::CreateVA`
- Remove vp9 422 chroma formats
- Reuse `ChooseProfile` for profile selection
while creating VAAPI video accel.
Test: random pick from decoders' conformance suites -
hevcd_conf, hevc10d_conf, hevcd_10b_422_y210_conf, hevcd_10b_444_y410_conf,
h264d_conf, mpeg2d_conf, jpegd_conf, mjpegd_conf,
vp9d_8b_420_nv12_conf, vp9d_10b_420_p010_conf,
vp9d_8b_444_ayuv_conf, vp9d_10b_444_y410_conf
=> core: fix HW core's ChooseProfile

_studio/shared/include/mfx_umc_alloc_wrapper.h, _studio/shared/src/mfx_umc_mjpeg_vpp.cpp
The regression was introduced in bb9a4a08, mfxVideoParam in
mfx_UMC_FrameAllocator_D3D_Converter::InitMfx() is for decoder only,
it ignores VPP step.
Issue: MDP-57600
=> [jpegd] Use correct mfxVideoParam in VideoVppJpegD3D9 initialization

_studio/shared/umc/io/umc_va/src/umc_va_linux.cpp
-1 is used to signal that whole list of profiles was processed,
but for some umc_codec-s it was never returned.
Issue: MDP-52942
=> [va] Fix finding supported profile

samples/sample_common/include/sample_defs.h, samples/sample_fei/src/fei_encpak.cpp
```MFX_VERSION``` macro should be used to track API version
=> samples: removed MSDK_API macro

_studio/mfx_lib/vpp/src/mfx_vpp_sw_core.cpp
This makes the gst pipeline below works on Linux
gst-launch-1.0 videotestsrc ! video/x-raw,format=P010_10LE ! msdkvpp ! \
video/x-raw,format=UYVY ! fakesink
Signed-off-by: Haihao Xiang <haihao.xiang@intel.com>
=> mfx_vpp: support CSC from P010 to UYVY on Linux

_studio/shared/src/mfx_umc_mjpeg_vpp.cpp
The regression was introduced in 073d8b9a, surface_work was incorrectly
used.
Issue: MDP-57678
=> [jpegd] Use correct FrameInfo while checking for progressive frame

_studio/hevc_fei/h265_fei/include/mfx_h265_fei_encode_plugin_hw.h, _studio/hevce_hw/h265/include/mfx_h265_encode_plugin_hw.h, _studio/mfx_lib/plugin/include/mfx_h264la_plugin.h, _studio/mfx_lib/plugin/include/mfx_vpp_plugin.h, _studio/mfx_lib/plugin/src/mfx_hevc_dec_plugin.cpp, _studio/mfx_lib/plugin/src/mfx_vp8_dec_plugin.cpp, _studio/mfx_lib/plugin/src/mfx_vp9_dec_plugin.cpp, _studio/mfx_lib/shared/src/libmfxsw_decode.cpp, _studio/mfx_lib/shared/src/libmfxsw_plugin.cpp, _studio/shared/include/mfx_utils.h, _studio/vp9e_hw/vp9/include/mfx_vp9_encode_plugin_hw.h
Avoid usage of low-level memory comparison in favor of operator ==
=> Fix comparison operators for plugin guids

_studio/mfx_lib/decode/mjpeg/include/mfx_mjpeg_dec_decode.h, _studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp, _studio/mfx_lib/shared/src/mfx_common_int.cpp, _studio/shared/umc/io/umc_va/src/umc_va_linux.cpp, samples/sample_decode/src/pipeline_decode.cpp
Off dy default (2-step conversion via internal VPP is used), enabled via
MFX_EXTBUFF_DEC_VIDEO_PROCESSING in prameter's extended buffer.
Issue: MDP-57617
=> [jpegd] Enable SFC for CSC to ARGB during jpeg 420 decode.

_studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_utils.h
- fix incorrect size detection
- use std::equal instead of memcmp
=> vp9e: fix comparison of segment maps

_studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw.h
"DEDICATED" reduces density for multisession workloads in join mode.
MDP-57311
=> [hevce] Use MFX_TASK_THREADING_INTRA

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp, samples/sample_decode/src/pipeline_decode.cpp
structure ENCODE_CAPS_HEVC has been refactored, but the related codes on path where VA version < 1.2 were not changed.
Signed-off-by: Zhongmin Wu <zhongmin.wu@intel.com>
=> fix complie issue when va version is less than 1.2 and reduce CPU load of sample_decode

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
If HW has less pipes than tile columns, columns number should be
reduced with warning but not UNSUPPORTED error.
=> [HEVCE] fix errorcode if tiles > NumScalablePipes

_studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_utils.h
Need extra surface for prevent situation, when we have free tasks, but
we cannot assign new one, because all surfaces are busy. For example:
mode "-async 3". On init sample_encode sets max surface count for tasks.
When encoding run we request for free surface. If surfaces run out, than
we start waiting for free surface (~10 ms) and only after that we do
SyncOperation. In hevc in "-async 3" mode we must alloc 3 surfaces, but
also we add one more extra surface, in order to get around above
situation. So, we do SyncOperation, free surface and can use it again
(in this way we have only 3 tasks in queue and do not break anything).
But in vp9 we dont alloc extra surface, and on each iteration we need
to wait, in this cause we get low FPS.
Issue: MDP-57848
=> [VP9e] Add one more surface for correct work in async mode

samples/sample_decode/src/pipeline_decode.cpp
1) Comparison JPEGColorFormat and ChromaFormat was incorrect, we
really need to know is color conversion required or not.
2) Fix POSTPROC_FORCE processing: it terminate processing when
decoder's post-processing is not enabled.
Issue: MDP-57617
=> [sample_decode] Correct decoder's post-processing enabling

samples/sample_common/src/mfx_buffering.cpp
FreeList() is not setting Tail pointer of m_OutputSurfacesPool to null.
This lead Tail pointer contains some invalid value after Reset().
Dereferencing of such pointer causes access violation.
To prevent this, for similar structures, there is a force NULL equating.
This changes is adding same equating for
m_OutputSurfacesPool Head and Tail pointers.
Issue: MDP-56738
=> [sample_decode] Fix access violation

samples/sample_decode/include/pipeline_decode.h, samples/sample_decode/src/sample_decode.cpp
Use initializer list on defenition instead of memset in constructor for POD struct.
Fixes #1547
=> build: fix gcc-9 -Wclass-memaccess warning in sample_decode

_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp, _studio/shared/src/mfx_vpp_vaapi.cpp
Before this fix, mirroring on Linux supports horizontal mirroring only when IOPattern equals d3d->d3d. In addition, mirroring can't work with other VPP features, e.g. rotation
Example:
gst-launch-1.0 videotestsrc num-buffers=10 ! video/x-raw,format=I420 ! \
msdkvpp rotation=90 mirroring=2 ! video/x-raw,format=YUY2 ! fakesink
ffmpeg -y -hwaccel qsv -c:v h264_qsv -i input.h264 -vf \
'format=qsv,vpp_qsv=transpose=vflip' -c:v h264_qsv output.h264 [*]
[*] The ffmpeg command needs two patches from Linjie
https://patchwork.ffmpeg.org/patch/13594/
https://patchwork.ffmpeg.org/patch/13595/
Signed-off-by: Haihao Xiang <haihao.xiang@intel.com>
Tested-by: Linjie Fu <linjie.fu@intel.com>
=> mfx_vpp: fix mirroring when IOPattern equals d3d->d3d on Linux

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp, _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp, _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
If VA profile/entrypoint unsupported, media-driver return appropriate status, so we can return `MFX_ERR_UNSUPPORTED` status in this case, instead of `MFX_ERR_DEVICE_FAILED`.
=> [h264][h265][vp9] Return unsupported status, if profile or entrypoint unsupported

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_ddi.cpp, _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
Updated info that driver chooses NumOfScalablePipes
depending on configuration and there are no restrictions
to tile configuration from possible scalable pipes.
MDP-58316
=> [HEVCE] update tiles independence from hw pipes

tools/asg-hevc/include/test_processor.h
Move inclusion test_processor.h above MFX_VERSION check to define global
identifiers in any case regardless of version. In other case project may not
compile.
=> [ASG-HEVC] Fix to build if not the latest mfx_version is used

_studio/mfx_lib/shared/src/mfx_vpx_dec_common.cpp
See https://github.com/intel/media-driver/blob/master/docs/media_features.md#supported-decoding-output-format-and-max-resolution
=> VP9dec: the driver may support up to 8K video

_studio/mfx_lib/shared/src/libmfxsw_decode.cpp
Currently MFX_ERR_* is passed through, but AddTask() is called. This may lead
to crash in CompleteTask() call chain.
=> [decode] Check result of DecodeFrameCheck() before adding task

samples/sample_common/src/base_allocator.cpp
The std::bind1st and bind2st were deprecated in C++11 and removed in C++17
=> [samples] Replace std::bind1st() with std::bind()

_studio/shared/umc/codec/mpeg2_dec/include/umc_mpeg2_decoder.h, _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_decoder.cpp
Correct submitting of first I-frame top part
testcase: tractor_422_1920x1080i_50f.mpg
=> [mpeg2d] Fix for a stream with invalid temporal_reference count

_studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw_utils.h, _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
1)Fix MAX_SLICES value according to codec level 6
(ITU-T H-265 02/2018, Table A.6)
2)Add assert check for slices number
=> [HEVCe] Fix max slices number

_studio/mfx_lib/encode_hw/mjpeg/src/mfx_mjpeg_encode_hw.cpp, _studio/mfx_lib/encode_hw/mpeg2/src/mfx_mpeg2_encode_utils_hw.cpp, _studio/mfx_lib/shared/include/mfx_enc_common.h
Like other CODECs, we may allow a larger surface for mpeg2/jpeg
encoding. If do so, we may use the same way to allocate surfaces for all
CODECs in user application / library.
=> Allow a larger surface for mpeg2/jpeg encoding

samples/sample_common/include/vaapi_device.h, samples/sample_decode/src/pipeline_decode.cpp, samples/sample_multi_transcode/src/sample_multi_transcode.cpp
Remove custom defined ```mfxHandleType``` for Wayland support: ```HANDLE_WAYLAND_DRIVER```
Use direct API instead
=> samples: do not abuse public API to reach Wayland device

samples/sample_common/include/sample_utils.h
The function should return valid poiner of throw an axception
=> [sample_common] Changed semantic of ExtBufHolder::AddExtBuffer

_studio/mfx_lib/decode/h264/src/mfx_h264_dec_decode.cpp, _studio/shared/umc/codec/h264_dec/include/umc_h264_frame.h, _studio/shared/umc/codec/h264_dec/include/umc_h264_slice_decoding.h, _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h, _studio/shared/umc/codec/h264_dec/src/umc_h264_dec_bitstream_headers.cpp, _studio/shared/umc/codec/h264_dec/src/umc_h264_dec_defs_yuv.cpp, _studio/shared/umc/codec/h264_dec/src/umc_h264_mfx_supplier.cpp, _studio/shared/umc/codec/h264_dec/src/umc_h264_nal_spl.cpp, _studio/shared/umc/codec/h264_dec/src/umc_h264_task_supplier.cpp, _studio/shared/umc/codec/h264_dec/src/umc_h264_va_supplier.cpp
=> AVCd: remove MFX_MIN/MAX macro

_studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_bitstream.cpp
Fix a regression introduced in commit 4f328187b7cf
(pull-request #1619) that caused output artifacts
in bottom row of decoded mpeg2 files.
=> [mpeg2d] fix regression in slice handling

_studio/mfx_lib/shared/src/libmfxsw.cpp, _studio/mfx_lib/shared/src/libmfxsw_decode.cpp
error returns replaced with equal trace statements
=> [session] errors trace in MFXClose

samples/sample_common/include/sample_utils.h, samples/sample_common/src/sample_utils.cpp, samples/sample_vpp/include/sample_vpp_utils.h, samples/sample_vpp/src/sample_vpp.cpp, samples/sample_vpp/src/sample_vpp_utils.cpp
1) Wrong variable usage;
2) Change InitParamsVPP signature
3) When we use mfxFrameSurfaceWrap and pass them to common function, we lose information about free surfaces, so change source to template
=> [sample_vpp] Fixes regressions after recent refactoring 

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp, _studio/mfx_lib/shared/include/mediasdk_version.h, doc/mediasdk-man.md, doc/samples/Media_Samples_Guide_Linux.md, doc/samples/readme-decode_linux.md, doc/samples/readme-encode_linux.md, doc/samples/readme-multi-transcode_linux.md, doc/samples/readme-vpp_linux.md, samples/sample_common/include/version.h
Just for 19.3 release. Next releases should go with https://github.com/intel/media-driver/pull/632 or analog.
=> Hevc qvbr fix

_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_cm.cpp, _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp, _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils.cpp, _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils_new.cpp, _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp, _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
=> h264e: remove MFX_MIN/MAX macro

_studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_bitstream_headers.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_utils.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_nal_spl.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_scaling_list.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_va_packer.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_va_supplier.cpp
=> HEVCd: remove MFX_MIN/MAX macro

_studio/mfx_lib/encode_hw/mpeg2/src/mfx_mpeg2_encode_utils_hw.cpp, _studio/mfx_lib/shared/include/mfx_mpeg2_enc_common.h, _studio/mfx_lib/shared/src/mfx_mpeg2_enc_common_hw.cpp, _studio/mfx_lib/shared/src/mfx_mpeg2_encode_vaapi.cpp, _studio/shared/umc/codec/brc/src/umc_mpeg2_brc.cpp
=> mpeg2e: remove MFX_MIN/MAX macro

_studio/mfx_lib/encode/mjpeg/src/mfx_mjpeg_encode.cpp, _studio/mfx_lib/encode_hw/mjpeg/src/mfx_mjpeg_encode_hw.cpp
=> mjpege: remove MFX_MIN/MAX macro

samples/sample_encode/include/pipeline_encode.h, samples/sample_encode/src/pipeline_encode.cpp, samples/sample_encode/src/pipeline_region_encode.cpp, samples/sample_encode/src/pipeline_user.cpp, samples/sample_encode/src/sample_encode.cpp
1) Option renamed to perf_opt
2) Preload buffer use until -n frames run out or if -n not specified,
until buffer ends.
=> [sample_encode] Change membuf functionality

_studio/mfx_lib/decode/vp8/include/mfx_vp8_dec_decode_hw.h, _studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw.cpp
=> vp8e: remove MFX_MIN/MAX macro

_studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_par.cpp, _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_utils.cpp
=> vp9e: remove MFX_MIN/MAX macro

_studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp
=> vp9d: remove MFX_MIN/MAX macro

_studio/mfx_lib/shared/src/mfx_common_int.cpp, _studio/shared/src/cm_mem_copy.cpp, _studio/shared/src/libmfx_core.cpp, _studio/shared/src/libmfx_core_vaapi.cpp
=> mfx common: remove MFX_MIN/MAX macro

_studio/shared/umc/core/umc/include/umc_defs.h, _studio/shared/umc/core/umc/src/umc_media_data.cpp, _studio/shared/umc/core/umc/src/umc_video_data.cpp
=> umc common: remove MFX_MIN/MAX macro

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_ddi.cpp
ICL doesn't support Main444 profile without VDEnc
=> Fix to get guid on ICL

_studio/mfx_lib/vpp/include/mfx_vpp_main.h
VPP shall not make shallow copy of ExtParam's from opaque
to native(real) surfaces. If app decides to change the opaque surface,
internal native surface can't be changed automatically.
=> [vpp] Removed shallow copy

_studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp
Decoder sets m_checkCRAInsideResetProcess flag when finds (which differs
from previous one) or invalid SPS. Before this change decoder didn't complete
decoding process and returned MFX_ERR_UNDEFINED_BEHAVIOR if couldn't find
any subsequent slice. Now it completes process skipping frames after
(invalid) SPS.
=> [HEVCd] Skip frames after new SPS without any subsequent slice

android/mfx_defs.mk
to enable feature with output decoded frames without latency regarding
SPS.VUI.max_num_reorder_frames
Signed-off-by: Ruan, Hongfu <hongfu.ruan@intel.com>
=> set ENABLE_MAX_NUM_REORDER_FRAMES_OUTPUT=true by default

_studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_decoder.cpp
This change alligns MPEG2 logic with
current internal logic of AVC/HEVC decoders.
=> [mpeg2d] Set frame PTS from PTS of the first slice

_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp, _studio/mfx_lib/vpp/src/mfx_vpp_sw_core.cpp
Sw fallback isn't supported now so return MFX_ERR_UNSUPPORTED instead of
MFX_WRN_PARTIAL_ACCELERATION.
ValidateParams func is called by Init and Query. But Init
must not return MFX_ERR_UNSUPPORTED, so it replace returned
MFX_ERR_UNSUPPORTED with MFX_ERR_INVALID_VIDEO_PARAM after caling
ValidateParams. Query must not return MFX_ERR_INVALID_VIDEO_PARAM and didn't
replace status.
=> [VPP] Changed returned statuses in ValidateParams

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
Add copying of coding option value instead of leaving this 0(UNKNOWN) in reset.
=> [HEVCe] Inherit LowPower parameter on reset

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw.cpp, _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_ddi.cpp, _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
Return MFX_ERR_INVALID_VIDEO_PARAM status, if profile/entrypoint unsupported
instead of replacing requested color format to get supported guid. Return
MFX_ERR_INVALID_VIDEO_PARAM because it is called in Init.
=> [H265] Don't change CF, if profile/entrypoint unsupported

doc/samples/readme-encode_linux.md, doc/samples/readme-multi-transcode_linux.md, samples/sample_encode/src/sample_encode.cpp, samples/sample_multi_transcode/src/transcode_utils.cpp
After this PR: https://github.com/Intel-Media-SDK/MediaSDK/pull/1668
sample_encode and sample_multi_transcode check -LADepth 0 and report error.
There is no need to check 0, it is default value,
in this case encoder will choose the value on his own.
=> samples: Change LADepth checking condition

doc/samples/readme-multi-transcode_linux.md, samples/sample_multi_transcode/src/transcode_utils.cpp
Updated sample_multi_transcode 'help' output on how to use lookahead plugin for HEVC encode. With reference to #1743
=> Updated sample_multi_transcode 'help' output for lookahead HEVC encode

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
Fix #1772.
Signed-off-by: Linjie Fu <linjie.fu@intel.com>
=> mfx_h265_encode_hw_par: Resize default slice number according to Tiles

_studio/shared/umc/io/umc_va/src/umc_va_linux.cpp
In conjunciton with 48d764d ("[va] Fix finding supported profile")
Fixes: 444ecb4 ("Add 12-bit format support")
=> Fix finding supported profile for 12-bit color formats

_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
Replaced GetExtBufferCalls in InheritDefaultValues to exclude
pointer dereferencing
=> Replaced GetExtBuffer calls with GetExtBufferRef calls

_studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw.cpp
MFX_ERR_MORE_DATA_SUBMIT_TASK must be returned when a task
ready to be submit. For other decoders MFX_ERR_MORE_DATA
means "error, no task created".
Issue: MDP-60305
=> [vp8d] Fix VideoDECODEVP8_HW::DecodeFrameCheck() return value

samples/sample_encode/src/sample_encode.cpp, samples/sample_multi_transcode/src/transcode_utils.cpp
Fixes #1778 (sample_encode and sample_multi_transcode don't support HEVC with MaxSliceSize)
=> samples: enable max slice size for H.265

_studio/mfx_lib/shared/src/mfx_vpx_dec_common.cpp
The Shift is wrong since commit 444ecb4 for VP9 10bit streams and
I saw errors below when running a gst-msdk pipeline:
gst-launch-1.0 filesrc location=input.10bit.ivf ! ivfparse ! msdkvp9dec ! fakesink
Redistribute latency...
0:00:00.021322781 15413 0x557733521050 ERROR                msdkdec gstmsdkdec.c:396:gst_msdkdec_init_decoder:<msdkvp9dec0> Init failed (invalid video parameters)
0:00:00.021337017 15413 0x557733521050 ERROR                msdkdec gstmsdkdec.c:868:gst_msdkdec_negotiate:<msdkvp9dec0> Failed to re-negotiate
Fix https://github.com/Intel-Media-SDK/MediaSDK/issues/1790
=> vp9d: fix regression caused by commit 444ecb4

api/mfx_dispatch/windows/src/mfx_dispatcher.cpp
When msdk dll is loaded, table of pointers to function implemented in this dll is filled.
The crash happens when: dll which implements MFXInitEx is loaded ->
pointer to MFXInitEx saved to the table -> dll is unloaded ->
table isn't cleaned -> dll which doesn't implement MFXInitEx is loaded ->
MFXInitEx called by the pointer that points to previous dll -> crash
=> Fix crash in dispatcher

_studio/mfx_lib/shared/include/mfx_brc_common.h, _studio/mfx_lib/shared/src/mfx_brc_common.cpp, samples/sample_common/include/brc_routines.h, samples/sample_common/src/brc_routines.cpp
if NalHrdConformance is on and VuiNalHrdParameters is off (MFX_BRC_HRD_WEAK)
then there is no need to check some hrd parameters.
This checking was disabled for this case.
=> [SW BRC][HEVCe] Disable unnecessary checking in HDRConformance case

_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
Encoder checks CBR and NalHRDConformance case and without idr
inserting on reset encoder return MFX_ERR_INCOMPATIBLE_VIDEO_PARAM.
This condition is reduntant. It was removed.
=> [AVCe] Remove unnecesary condition on reset with CBR and HRDConformance

samples/sample_decode/src/pipeline_decode.cpp
Need to add one more surface in rendering mode for correct "async 1"
behavior
Fixes: #1655
=> sample_decode: Add one more surface in rendering mode

samples/sample_encode/src/pipeline_encode.cpp
IOPattern is mandatory according to MSDK manual!
Issue: MDP-60420
Test: build,manual
=> [Samples] multiadapters: IOPattern is mandatory

_studio/shared/src/cm_mem_copy.cpp
Fixes: 9fd26ab ("API 1.31 - JSL")
=> 1.27: fix cm mem copy for icl

_studio/shared/src/libmfx_core_vaapi.cpp
Synced with:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/drm/i915_pciids.h?h=v5.4.2
Fixes: #1813
=> [code] Added missing device IDs

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_ddi.cpp, _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp, _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp
ROI priority mode is supported on platforms with corresponding caps
Otherwise it should be converted to delta QP mode
=> [hevce] fix ROI priority mode support

_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
Changed ImplementationAvc Init and Reset behavior in case of
mfxExtCodingOption2 member IntRefCycleSize equal to 1 which is invalid
value by manual. In this case methods will change intra refresh cycle size
to 1s and return MFX_WRN_VIDEO_PARAM_CHANGED.
=> [avc] Changed ImplementationAvc Init and Reset behavior to match manual

api/mfx_dispatch/windows/src/mfx_library_iterator.cpp
1. DllMain is not a mandatory, some dlls may not have it.
2. hModule is obtained via GetModuleHandleExW which sets it to NULL if fails.
Comparison with HMODULE(-1) is incorrect.
=> [disp] Fix check if current module is a dll

_studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp
Corrected setting of NumScalablePipesMinus1 caps value for TGL+ to support MxN
tiles encoding.
=> [VP9e] Corrected NumScalablePipesMinus1 caps value for TGL+

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
Revert https://github.com/Intel-Media-SDK/MediaSDK/pull/1706
Surface should be aligned by 16 according to manual
Stream's resolution determined by mfxExtHEVCParam::PicWidthInLumaSamples
and mfxExtHEVCParam::PicHeightInLumaSamples
=> [HEVCe]: Change alignment of surface

_studio/mfx_lib/encode/CMakeLists.txt
Fixes https://github.com/Intel-Media-SDK/MediaSDK/issues/1845
=> Unbreak -DMFX_ENABLE_SW_FALLBACK=OFF

_studio/mfx_lib/encode_hw/hevc/agnostic/g9/hevcehw_g9_roi.cpp, _studio/mfx_lib/encode_hw/hevc/agnostic/g9/hevcehw_g9_roi.h, _studio/mfx_lib/encode_hw/hevc/linux/g9/hevcehw_g9_roi_lin.cpp
ROI priority mode is supported on platforms with corresponding caps
Otherwise it should be converted to delta QP mode
=> refactored hevce: fix ROI priority mode support

_studio/mfx_lib/shared/include/mfx_h264_encode_struct_vaapi.h, _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp, _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
1) In 0e04f56 for MFX_RATECONTROL_AVBR mvcPerViewPar.(target|max)Kbps etc
were erroneously set to zero.
2) Move AVBRSupport to other (CQP|CBR|VBR)Support.
Issue: MDP-60700
=> [h264e] Fix AVBR MVC encoding

samples/sample_common/src/vaapi_allocator.cpp
Fixes: fcca4c ("Reallocate frame (system memory or vaapi surface) for VP9 DRC decoding.")
sample_vpp returns correct status for RGB565->* and NV12->RGBP color conversions.
=> [VPP] Fix MFX status for RGB565 and RGBP color formats

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_ddi.cpp, _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
Usage of HardcodeCaps is a temporal solution.
It will be removed when all driver caps issues are resolved
=> [HEVCe]: Move setting some caps to HardcodeCaps()

_studio/shared/umc/core/vm/src/vm_sys_info_linux32.c, tutorials/common/common_vaapi.cpp
Upstreaming some fixes from [FreeBSD package](https://www.freshports.org/multimedia/intel-media-sdk):
- libc++ (unlike libstdc++) doesn't bootleg `<string>` via `<map>`
- `sysinfo` code was converted to `sysconf`, making it portable to other Unices
=> Adjust includes in some places

_studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_utils.h, _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_par.cpp
Using the wrong constant (64 instead 128) led to overstated
acceptable number of tiles (>4)
=> [vp9e] Check for tiles group height exceeds picture height fix

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
Changed behavior for sps.QpAdjustment:
default is off for all TUs (does not depends on VME or VDENC)
=> [HEVCe] Changed behavior for sps.QpAdjustment

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp, _studio/mfx_lib/encode_hw/hevc/agnostic/g9/hevcehw_g9_legacy.cpp
If QP supplied is out of range it is clapped to the supported range now
instead of dropping to the default value
=> [HEVCe] Clapping of input QP

_studio/shared/include/mfxvideo++int.h
Compiler may insert uninitialized padding bytes inside POD structs, so it is unsafe to calculate hash across fields boundary
=> hevce: avoid possible usage of garbage padding bytes in hash calculation

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_ddi.cpp, _studio/mfx_lib/encode_hw/hevc/linux/g12/hevcehw_g12_caps_lin.h
Remove MaxPicWidth and MaxPicHeight from HardcodeCaps()
The first step in avoiding of hardcoding caps.
=> [HEVCe] Remove hardcode of resolution's caps

_studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_ddi.cpp
It is not enough mfxU8 for processing 16k streams. Therefore,
information about tiles was set incorrectly in uncompressed header
=> [VP9e] Fixed 16K corruption

samples/sample_common/src/sample_utils.cpp
When format is NV12/P010/P210, the chroma width based on
the odd output width need be aligned.
=> Fix chroma width calculation when output width is odd

_studio/mfx_lib/encode_hw/hevc/agnostic/g9/hevcehw_g9_legacy.cpp
At runtime we have to fix user provided parameters before passing to DDI
=> HEVCe-r: fixed deblocking parameters passing

_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils.cpp, _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils_new.cpp
Before it was limited to SCL and BDW only.
Issue: MDP-60832
=> [AVCe] Enable arbitrary reference field polarity starting BDW

_studio/mfx_lib/cmrt_cross_platform/include/cmrt_cross_platform.h, _studio/mfx_lib/mctf_package/mctf/include/mctf_common.h, _studio/mfx_lib/mctf_package/mctf/src/mctf_common.cpp
MCTF hangs when is used in ICL with Opensource
driver, this is because Fast Path for enqueue
was not implemented. Now Fast path is available
in opensrouce driver but it needs to be called
implicitly for ICL platform. This fix determines
based on the platform what type of enqueue function
to use, EnqueueFast for Gen11 and Enqueue for all
others.
Issue: https://hsdes.intel.com/resource/2207632605
Test: manual on SKL and ICL
=> [VPP][MCTF] Fast path feature enabled for ICL

_studio/shared/src/libmfx_core_vaapi.cpp
FEI ENC/PAK uses external allocator to retrieve memId's of surfaces
which already allocated by app
Test: few different scenarios via sample_encode/sample_decode/smt/sample_fei 
fixes: 7eb0c0b (core: Use default allocator for allocate internal resources")
=> core: Use external allocator for find FEI ENC / PAK reconstructs

_studio/shared/umc/io/umc_va/src/umc_va_linux.cpp
It should also use VAProfileHEVCSccMain444 for HEVC Main444
10bit decoding.
=> Fix HEVC SCC Main444 10bit VLD profile lookup

_studio/mfx_lib/CMakeLists.txt
mfx_enc_common.cpp is added to both mfx_common_hw and mfx_common,
but later one missed MFX_VA flag, so mfx_enc_common.cpp is build
without MFX_VA_LINUX, that is incorrect.
Issue: MDP-51482
=> [build] Drop mfx_enc_common.cpp from mfx_common

_studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw_utils.h, _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_vaapi.h, _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_ddi.cpp, _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp, _studio/mfx_lib/encode_hw/hevc/agnostic/g9/hevcehw_g9_legacy.cpp
Now MBQP block size used by HW in cuqpMap can vary according to caps.
Added cuqpMap filling for unaligned LCU, because HW averages LCU blocks to compute per LCU QP.
(61287).
Manually tested.
Backmerged fixes for windows.
=> [hevce] Fix Linux MBQP

tests/unit/suites/mfx_dispatch/linux/mfx_dispatch_test_cases_libs.cpp, tests/unit/suites/mfx_dispatch/linux/mfx_dispatch_test_cases_plugins.cpp
Add missing EXPECT_CALLs to fix gmock warnings
Closes #1167
=> Fix gmock warnings in mfx_dispatch_test

_studio/mfx_lib/encode_hw/hevc/agnostic/g12/hevcehw_g12_caps.cpp
Corrected default numbers of references calculations on TGL+ platforms.
=> [HEVCe-r] Corrected def. num. ref. list. calc. on TGL+

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp, _studio/mfx_lib/encode_hw/hevc/agnostic/g9/hevcehw_g9_legacy_defaults.cpp
Max bitrate for sliding window is equal to max kbps by default
=> [hevce] Fix sliding window parameters

samples/sample_multi_transcode/include/sample_multi_transcode.h, samples/sample_multi_transcode/src/sample_multi_transcode.cpp
for MDP-51933 issue.
Replaced pointers usage with unique_ptr in TranscodingSample::Launcher class
=> TranscodingSample::Launcher: replaced pointers to unique_ptr

_studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_common.cpp, _studio/mfx_lib/shared/src/mfx_vpx_dec_common.cpp
MFX_INTERNAL_CPY uses buffer size in bytes
=> [vpx] correct buffer size in copy operation

_studio/mfx_lib/encode_hw/hevc/agnostic/g9/hevcehw_g9_legacy.cpp
Legacy have same behavior.
Note! Query/Init allow IOPattern=0! (same behavior for Legacy & refactored)
=> [HEVCe R] Disallow IOPattern=0 at QueryIOSurf

samples/sample_common/src/sample_utils.cpp
Fixes #1750
This is the AYUV Windows color format, and it is already defined in MFX color formats.
=> [sample_common] Remove unnecessary hardcoded color format

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp, _studio/mfx_lib/encode_hw/hevc/agnostic/g9/hevcehw_g9_dirty_rect.cpp
1. (0,0,0,0) is valid, that frame is not changed;
2. fixed 'changed' when invalid dirty rects are removed from the list in refactored code
=> [hevce][hevce r] Fix checks for dirty rectangle

samples/sample_encode/src/pipeline_encode.cpp
We print parameters not get them previously
Signed-off-by: egorovdanil <danil.egorov@intel.com>
=> [sample_encode] Print real encode params

samples/sample_common/src/sample_utils.cpp
Without this patch, GetChromaSize() returns MFX_ERR_UNSUPPORTED for Y410
and Y416 frames, and sample_decode fails to write Y410 and Y416 frames
for VAProfileHEVCMain444_10 and VAProfileHEVCMain444_12 videos
example:
sample_decode  h265 -i input.10b.444.hevc -o output.yuv
[ERROR], sts=MFX_ERR_UNKNOWN(-1), RunDecoding, Unexpected error!!
=> sample: fix chroma size for Y410 and Y416

_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
Return MFX_ERR_UNSUPPORTED, as the feature really can't be
supported.
Issue: VSMGWL-21261
=> [AVCe] Correct badarg processing for MaxSliceSize

_studio/mfx_lib/encode_hw/hevc/linux/g12/hevcehw_g12_lin.cpp
FeatureBlocks queue is reordered to set Gen12 caps after Gen9
=> [hevce] Fix Gen12 caps

samples/sample_common/include/sample_utils.h, samples/sample_common/src/sample_utils.cpp
Issue:MDP-62025
Test:manual
Win validations get MFX_ERR_NOT_ENOUGH_BUFFER for VP8 and VP9 codecs. Next frame data was read wrong (read head again)
=> [sample_decode] VP8, VP9 reading were fixed (backmerge)

_studio/mfx_lib/encode_hw/hevc/agnostic/g12/hevcehw_g12_sao.h
Removed obsolete rule to disable SAO when WeightedPrediction is enabled
=> [hevce] allow SAO with WP

_studio/mfx_lib/encode_hw/hevc/linux/g9/hevcehw_g9_va_packer_lin.cpp
QP values should be averaged within LCU.
For non LCU aligned resolutions
QP averaging on frame borders was observed.
=> [HEVCe] Fix MBQP averaging on frame borders

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp, _studio/mfx_lib/encode_hw/hevc/agnostic/g9/hevcehw_g9_legacy.cpp
First frame in Intrarefresh cycle can have more than one references
All other frames in Intrarefresh cycle should have only one reference
First frame after Intrarefresh cycle should have only one reference
Other frames outside IntraRefresh cycle can have more than one reference
=> [HEVCe] Fix IntraRefresh with multiref issue

samples/sample_decode/src/pipeline_decode.cpp
After commit 757ea7 we don't need this shift settings,
because it's already filled in mfxVideoParams by
DecodeHeader.
Fixes #1988
=> [sample_decode] Remove unnecessary shift settings

samples/sample_encode/src/sample_encode.cpp
By default BufferSizeInKB is wrongly set to 8 sec (since bitrate is in Kilobits not KiloBytes). This fix sets it to 1 sec as intended.
=> sample_encode: fix BufferSizeInKB initialization

samples/sample_multi_transcode/include/pipeline_transcode.h, samples/sample_multi_transcode/src/pipeline_transcode.cpp, samples/sample_multi_transcode/src/transcode_utils.cpp
Add flags for selection of AVBR, QVBR, ICQ rate control methods to sample_multi_transcode.
Closes #1641
=> Add AVBR, QVBR, ICQ to sample_multi_transcode

_studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp, _studio/mfx_lib/encode/mjpeg/src/mfx_mjpeg_encode.cpp, contrib/ipp/include/ippcore.h, contrib/ipp/src/ippinit.c
jpeg software fallback is supported starting SSE4.2.
=> [jpegd][jpege] Check that SW fallback is supported before using it

_studio/mfx_lib/vpp/src/mfx_vpp_utils.cpp
UYVY is only supported by driver as input format on Linux
=> [VPP] Fix caps issue with UYVY format

_studio/mfx_lib/encode_hw/hevc/agnostic/g9/hevcehw_g9_legacy_defaults.cpp
ExtCO3.NumRefActive values were discarded
because when NumRefFrame is not set maxDBP
became like 0.
Now maxDBP is set to default in this case.
[62088]
Test: manual check logs and encoded stream
=> [hevce] Fix NumRefActive

builder/ConfTargets.cmake
Fixes: #2047
We should not enforce specific instruction set target (-m<inst-set>
option) since end-users might experience crashes with sigill at
least for the following reasons:
1. msdk lib might be probed at runtime even on non-intel CPUs if it
is included into some plugin based framework (like gstreamer)
2. unit tests included into build system might be run on the system
where build had happenned which might be non-intel
So, this change remove msdk global instruction set flags. We still
have few places in the library tight to the particular instruction
set. These are optimization specific algorithms such as ipp, asc
(scene change detection) and memory copy operations. In these cases
we use runtime checks to detect underlying instruction sets. If we
don't support particular one - we are …
=> build: do not enforce specific instruction set

_studio/shared/umc/codec/h265_dec/include/platform/umc_h265_va_packer_vaapi_g12.hpp, _studio/shared/umc/codec/h265_dec/include/umc_h265_va_supplier.h, _studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_va_supplier.cpp
There two changes are all cherry-picked from internal branch.
1) For 16k wpp stream,  it has up to 300 bytes' prevention, so increase 300 bytes here. Meanwhile, 300 bytes is the  biggest size we met till now.
=> 1) fix small buffer for 16k wpp stream;  2)  clear vector when re-allocate buffer

builder/FindPackages.cmake
libva >= 2.5.0 (VA_API_VERSION>=1.5.0) required for build current version.
On prior version we get compilation errors on undefined constants.
=> cmake: Updated livba requirements

samples/sample_decode/src/pipeline_decode.cpp
m_bVppIsUsed should be defined after the InitMfxParams call
=> [sample_decode] Fix wrong m_bVppIsUsed

_studio/mfx_lib/shared/include/mfx_utils_extbuf.h
Solution proposed by @eistarov and pull requested by @dmitryermilov 
Fix below allow to build successfully using a gcc 4.93 compiler.
=> gcc 4.93 build fix for issue #2100

_studio/mfx_lib/shared/src/mfx_vpx_dec_common.cpp
commit dc8ed84 removed the resolution limitation for vp9 decoder,
however commit 444ecb4 added this limitation back, which results in
regression with 8K decoding
=> vp9d: fix 8K regression

api/mfx_dispatch/windows/src/main.cpp
Change the API version verification condition in MFXJoinSession
function from the desired version of the library implementation
to loaded SDK implementation version.
=> [DISP]: Change the API version verification

_studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h, _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
rc_flags.bits.reset is used inside vaRenderPicture(), but it's value was
lost on VAEncMiscParameterBufferType buffer's recreation.
Issue: MDP-61317
=> [h264e] Pass BRC reset flag to driver

samples/sample_decode/src/pipeline_decode.cpp
In the commits 113614a and 83cbfa6, I repeatedly moved the IsVppRequired() call, and I missed the fact that it's needed in InitMfxParams() to set m_bVppIsUsed.
=> [sample_decode] Set m_bVppIsUsed before using

_studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw_utils.h, _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp, _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp, _studio/shared/include/mfx_ext_buffers.h
LCUSize is removed from mfxExtCodingOptionDDI buffer since
it was moved to mfxExtHEVCParam (official API)
=> [hevce] remove usage of extddi buffer for LCUSize

_studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_va_packer_lin.cpp
vaInitPar contains buffer data. Pushed buffs in blocks before VAPacker Reset were erased.
=> [hevce r] Fix reset on Linux

_studio/mfx_lib/encode_hw/mjpeg/include/mfx_mjpeg_encode_vaapi.h, _studio/mfx_lib/encode_hw/mjpeg/src/mfx_mjpeg_encode_hw_utils.cpp, _studio/mfx_lib/encode_hw/mjpeg/src/mfx_mjpeg_encode_vaapi.cpp
1) Cache jpege caps, not ask them at every EncodeFrameAsync.
2) Request some encoding limitation from driver, not use hardcoded values.
=> [jpege] Improve caps usage

_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp, _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils_new.cpp, _studio/mfx_lib/shared/include/mfx_h264_enc_common_hw.h, _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp, _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
1) Previously combined values leads to creation of single slice.
2) enum is used instead of magic numbers.
Issue: MDP-61999
=> [h264e] VA may return multiple values in VAConfigAttribEncSliceStructure

samples/sample_decode/src/pipeline_decode.cpp
Attach of this buffer lead to unsupported error on old win MediaSDK
releases
=> sample_decode: Attach mfxExtThreadsParam only if it required

_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
Before MBQP was treated as always supported.
Issue: VSMGWL-26248
=> [avce] Check VAConfigAttribQPBlockSize to get MBQP support status

_studio/shared/umc/codec/h265_dec/include/umc_h265_dec_defs.h, _studio/shared/umc/codec/h265_dec/include/umc_h265_va_supplier.h, _studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp
When reallocate slice header buffer because large entry point offset,
1. Enlarge the base size for slice header.
2. Make the data size matched between nalUnit and slice->m_source.
3. User macro definition calculation instead of "2860" and "512" hard code.
Issue: MDP-62068
Test: hevcd_func
Change-Id: I754ab9f263c18b9e2f350e22f3764c435b0453e4
=> [hevcd] Fix slice header buffer size for large entry point offset count

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_ext_brc.cpp, _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy.cpp
Cleared bSkip flag to avoid infinite skip
and changed frame copy mode to match
allocation type and legacy mode
=> [hevce] Fix ExtBRC panic

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp, _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp
Smaller POC is closer to current frame
=> [hevce] L1 should be sorted in ascending POC order

_studio/mfx_lib/vpp/include/mfx_vpp_utils.h, _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp, _studio/mfx_lib/vpp/src/mfx_vpp_sw_internal.cpp, _studio/mfx_lib/vpp/src/mfx_vpp_utils.cpp, _studio/shared/include/mfx_vpp_interface.h, api/include/mfxdefs.h, api/include/mfxstructures.h, doc/header-template.md, doc/mediasdk-man.md
Adding 4 interpolation method definition and implementation: Default, Nearest Neighborhood, Bilinear and Advanced. Provide the flexiblity to API user.
=> [API] Adding Scaling Interpolation Method

_studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_utils.cpp
Before check both width and height are
either 0 or not 0. If 0 then check is skipped
(63413)
=> [hevcd] Fix Query to pass Crops

samples/sample_encode/src/pipeline_encode.cpp
if EncodeFrameAsync return device_busy,
nEncSurfIdx will switched to next surface,
in the case of perf_opt option.
=> [samples] Fix potential issue in device_busy case

_studio/mfx_lib/encode_hw/mpeg2/src/mfx_mpeg2_encode_utils_hw.cpp
Added missed CodecProfile/Level checking in Query.
It failed before if CodecProfile and CodecLevel were inconsistent.
=> [mpeg2e] Add CodecProfile/Level checking in Query

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy.cpp, _studio/mfx_lib/encode_hw/hevc/agnostic/g12/hevcehw_g12_rext.cpp
Fix recons format for specific cases when input format differs
from the output. For example, for HEVCe VDENC
Y210 format is supported as input while the output is P010
=> [hevce] fix recon format for specific cases

samples/sample_plugins/rotate_opencl/include/opencl_filter.h, samples/sample_plugins/rotate_opencl/src/sample_opencl_plugin.cpp
Since [v2.0.12](https://github.com/KhronosGroup/OpenCL-CLHPP/tree/v2.0.12/include/CL) KronosGroup removed outdated cl.h header.
This change introduce minimal compatibility fix. According to https://github.com/intel/compute-runtime/blob/master/README.md
supported OpenCL API version on Apollo Lake and Gemini Lake platforms is 1.2
Fixes #2190
=> Use CL/cl2.hpp for rotate_opencl_plugin

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw.cpp, _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_encoded_frame_info.cpp
m_frameorder is set to 0 after Reset.
User applications cannot match the encoded frame to the bitstream
during encode using mfxExtAVCEncodedFrameInfo.FrameOrder.
=> [hevce] Fix reported frame order

samples/sample_multi_transcode/src/sample_multi_transcode.cpp
Based on MediaSDK manual
https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/mediasdk-man.md#MFXClose
fixes: 7815801(TranscodingSample::Launcher: replaced pointers to unique_ptr)
=> smt:all child sessions must be disjoined before closing a parent session

_studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h, _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils.cpp, _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils_new.cpp, _studio/mfx_lib/fei/h264_common/fei_common.cpp, _studio/mfx_lib/shared/include/mfx_h264_enc_common_hw.h, _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
- In CQP mode and GopRefDist 1 case
PRefType is set to MFX_P_REF_PYRAMID by default.
- EnableQPOffset is on by default, QPOffset is added in CQP mode.
=> [h264e] Enable QPOffset by default

_studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_par.cpp
Only 1 reference frame is supported for TargetUsage 7.
=> [VP9e] Added check on max number of reference frames for TU7

_studio/mfx_lib/shared/include/mfx_h264_encode_struct_vaapi.h, _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp, _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
=> [h264e] AdaptiveMaxFrameSize is unsupported under libva

_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp, _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_data.h, _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy.cpp, _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy.h, _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp, _studio/mfx_lib/encode_hw/hevc/agnostic/g12/hevcehw_g12_caps.cpp
GetMaxNumRef now distinguishes P or LDB with RAB
when returns MaxNumRefActive. In the result LDB
can have different NumRef with RAB L0.
Implemented in both R and legacy.
=> [hevce] Separate P and BL0 in GetMaxNumRef

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_ext_brc.cpp
The unit of MinFrameSize is bytes rather than bits. So modify it.
=> [HEVCe] Fix the unit difference between bytes and bits in external BRC

_studio/shared/include/cm_mem_copy.h, _studio/shared/src/cm_mem_copy.cpp
This check disables CM usage if surface planes
are not allocated as one memory block.
This is must-condition for CM usage.
=> [Core] Check if planes are continuously allocated

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp
After GetMaxNumRef was separated for LDB and RAB,
for LDB on VDEnc L1 became different with L0.
This commit fixes it.
=> [hevce] Fix vdenc LDB L1 after separation

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp
Addition to commits 2219 and 2229.
After GetMaxNumRef was separated for LDB and RAB,
for LDB on VDEnc L1 became different with L0.
2229 fixed for P, but didn't after change P to LDB.
NumRefs code now works both for P and LDB.
Fix: #2236
=> [hevce] Fix vdenc LDB L1 part2

samples/sample_common/src/sample_utils.cpp
Without this patch, GetChromaSize() returns MFX_ERR_UNSUPPORTED for Y210
and Y216 frames, hence sample_decode fails to dump YUV data to a file
for a 422 video
Example:
sample_decode h265 -i input.12b.422.hevc -o output.yuv
[WARNING], sts=MFX_ERR_UNKNOWN(-1), RunDecoding, SyncOutputSurface failed
=> Sample: fix chroma size for Y210 and Y216

_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp, _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_ext_brc.cpp, _studio/mfx_lib/shared/src/mfx_brc_common.cpp, samples/sample_common/src/brc_routines.cpp
Repeat +7 when calculating the MinFrameSize in legacy 265 and mpeg2. Unify the
conversion way that the MinFrameSize is added 7 when bits are converted to bytes.
=> [Encode] Unify conversion way from bits to bytes in external BRC

_studio/mfx_lib/encode_hw/hevc/agnostic/g12/hevcehw_g12_caps.cpp
For LowPower Encoding, since TU6 is mapped into TU7, caps.IPSliceOnly should also be set as 1.
=> [HEVCe] Fix issues for TU6

_studio/shared/src/libmfx_core.cpp, _studio/shared/src/libmfx_core_vaapi.cpp
To avoid potential memory leak if FastCopy fails
=> [core] Unlock frames before checking fast copy status

_studio/shared/umc/codec/av1_dec/include/umc_av1_frame.h
=> Fix return type of AV1DecoderFrame::FrameOrder()

api/include/mfxplugin++.h
=> Fix build warnings when included in clang-based project

_studio/mfx_lib/shared/src/mfx_vpx_dec_common.cpp
=> Copy AV1 codec level in MFX_VPX_Utility::Query()

_studio/shared/umc/codec/av1_dec/src/umc_av1_va_packer_vaapi.cpp, _studio/shared/umc/io/umc_va/src/umc_va_linux.cpp
The type of ref_frame_map is VASurfaceID, not FrameMemID, so we should
assign a VA surface ID to ref_frame_map
In addition, return VA_INVALID_SURFACE from
LinuxVideoAccelerator::GetSurfaceID() once catching an exception
=> av1d: assign a VA surface ID to ref_frame_map

_studio/mfx_lib/shared/src/mfx_vpx_dec_common.cpp
VP9 decode support up to 16K.
Signed-off-by: Li Shawn <shawn,li@intel.com>
=> [VP9d] update max width/height

api/mfx_dispatch/windows/src/main.cpp
To prevent errors when cross-compiling
from Linux to Windows.
windows.h is all lowercase in mingw.
=> Use lowercase for windows.h

_studio/shared/src/cm_mem_copy.cpp
This change fixes incorrect behavior of
CheckSurfaceContinuouslyAllocated()
in case of 2160x3840 stream size.
Change was tested with streams with
different resolutions - works as expected.
=> [CM][Core] Fix stride alignment

doc/samples/readme-multi-transcode_linux.md, samples/sample_multi_transcode/include/pipeline_transcode.h, samples/sample_multi_transcode/src/pipeline_transcode.cpp, samples/sample_multi_transcode/src/transcode_utils.cpp
Current flag helps to build pipeline with system memory from
decoder output and vpp input + video memory from vpp output
and encoder input as example.
Issue: n/a
=> Add -dec::sys flag for setting of the output memory to system type

_studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h
This fixes an infinite loop when an AVC stream has
4 ref frames and level 5.2... regression introduced
by:
```
commit e126273431b470a738e4c26896b829a6801cb455
Author: Guo, Will <will.guo@intel.com>
Date:   Sun Apr 26 19:22:34 2020 +0800
Support AVC Level 6/6.1/6.2
Support Decode AVC Level 6/6.1/6.2
Issue: MDP-47088
Change-Id: I42aa5f67b7480a264f86822d5e5e3cd750d8d090
```
Fixes #2325
=> Fix infinite loop for Ref 4 @ L5.2

_studio/mfx_lib/shared/src/libmfxsw_decode.cpp
It includes MFX_ERR_MORE_(DATA|SURFACE).
Issue: MDP-63939
=> [decode] Add task if DecodeFrameCheck() not aborted operation 

_studio/mfx_lib/vpp/src/mfx_vpp_utils.cpp
This reverts commit 9d67819f720e660c9538bbc6299c7acbe2d41266.
This fixes https://github.com/Intel-Media-SDK/MediaSDK/issues/2336
=> Revert "[VPP] Fix caps issue with UYVY format"

_studio/mfx_lib/vpp/src/mfx_vpp_sw_core.cpp
YUV 16bit color formats are not supported on ICL and platforms below
=> [vpp] Add platform check for YUV 16bit color formats (backmerge)

api/mfx_dispatch/windows/include/mfx_dispatcher.h, api/mfx_dispatch/windows/include/mfx_dispatcher_uwp.h, api/mfx_dispatch/windows/include/mfx_driver_store_loader.h, api/mfx_dispatch/windows/include/mfx_library_iterator.h, api/mfx_dispatch/windows/libmfx_uwp.vcxproj, api/mfx_dispatch/windows/libmfx_uwp.vcxproj.filters, api/mfx_dispatch/windows/libmfx_vs2015.vcxproj, api/mfx_dispatch/windows/mfx_prefixed_dispatch_trace_lib.vcxproj, api/mfx_dispatch/windows/src/main.cpp, api/mfx_dispatch/windows/src/mfx_dispatcher.cpp, api/mfx_dispatch/windows/src/mfx_dispatcher_uwp.cpp, api/mfx_dispatch/windows/src/mfx_driver_store_loader.cpp, api/mfx_dispatch/windows/src/mfx_library_iterator.cpp
Added search of HW library in adapter's DriverStore folder.
Changed preference conditions for found libraries.
Added workaround to keep MSDK tracer workable with DriverStore loading.
Increased dispatcher version 1.2 -> 1.3.
=> [Disp] MSDK HW library loading from DriverStore

_studio/mfx_lib/mctf_package/mctf/include/mctf_common.h, _studio/mfx_lib/mctf_package/mctf/src/mctf_common.cpp
When strength zero is selected for MCTF in VPP, the
denoising path was not being executed after the fourth
frame because settings from the inEnc-pipeline operation
which is not active were disabling it.
Issue: Regression detected
Tests: vpp_mctf_denoise (all test passed)
Manual testing for in-encoding pipeline
=> [VPP][MCTF] Not inEnc-pipeline zero strength fix

doc/mediasdk_release_notes.md
Limitation for frame size is absent in swbrc:
"The sum of the NumBytesInNalUnit variables for access unit 0
shall be less than or equal to:
FormatCapabilityFactor * ( Max( PicSizeInSamplesY, fR * MaxLumaSr[CodecLevel]) + MaxLumaSr[CodecLevel] * ( AuCpbRemovalTime[ 0 ] − AuNominalRemovalTime[ 0 ] ) ) / MinCr"
=> Update Release Notes

CODEOWNERS
=> av1d: add AV1 decoder code owners

_studio/mfx_lib/shared/src/mfx_vpx_dec_common.cpp, _studio/shared/umc/codec/av1_dec/src/umc_av1_decoder_va.cpp
For current AV1's DPB implementation, after decoding a frame, Output
frame will be saved in a temporary variable for DPB update when next
frame coming. Need to give one more buffer to save temporary frame
for DPB update.
For this stream, it has 8 reference frames in DPB, if we only
allocate 8 + 1 + async_depth buffers, DPB is not update immediately
so no output, in app side, it can't get any more free buffer to
feed next frame, then deadlock.
Issue: MDP-63996
Tests: ./sample_decode -hw av1 -i ./test_stream_av1.ivf -o 0001.yuv
-async 1  -vaapi
Change-Id: I10ab4b697cd392b76068e4e83935688fa1279ee8
=> increase decode picture buffer

_studio/mfx_lib/shared/src/mfx_vpx_dec_common.cpp, _studio/shared/umc/codec/av1_dec/src/umc_av1_decoder_va.cpp
For current AV1's DPB implementation, after decoding a frame, Output
frame will be saved in a temporary variable for DPB update when next
frame coming. Need to give one more buffer to save temporary frame
for DPB update.
For this stream, it has 8 reference frames in DPB, if we only
allocate 8 + 1 + async_depth buffers, DPB is not update immediately
so no output, in app side, it can't get any more free buffer to
feed next frame, then deadlock.
Issue: MDP-63996
Tests: ./sample_decode -hw av1 -i ./test_stream_av1.ivf -o 0001.yuv
-async 1  -vaapi
Change-Id: I10ab4b697cd392b76068e4e83935688fa1279ee8
=> [av1d]: increase decode picture buffer

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy.cpp
Issue: https://github.com/Intel-Media-SDK/MediaSDK/issues/2316#issuecomment-691084502
=> Fix floating point exception in case of AvcTemporalLayers "0 1 2 4 0 0 0 0"

_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
1) Sliding window for MFX_RATECONTROL_LA* doesn't require driver
support. It was broken in 9188b153c.
2) Sliding window for VBR and QVBR requires driver support along with
CBR.
3) WinBRCSize==0 better matches unsupported, not changed, as the
functionality is not supported.
Issue: MDP-62514
=> [h264e] Fix sliding window for MFX_RATECONTROL_LA*

_studio/shared/asc/src/asc.cpp
Regressed by #2319. From [error log](https://github.com/Intel-Media-SDK/MediaSDK/files/5328380/intel-media-sdk-20.3.0.log):
```c++
_studio/shared/asc/src/asc.cpp:1129:26: error: no member named 'log' in namespace 'std'
result = ((c1 * std::log(x)) + c0) >= y;
~~~~~^
```
=> [ASC] Unbreak build with libc++ after [AVC][MCFT]

api/mfx_dispatch/windows/src/mfx_dispatcher.cpp, doc/mediasdk-man.md
In current behavior of QueryAdapterInfo, it always reports
VID/DID values filled from DX9 data. On multiadapter systems,
enumeration for DX9/DX11 adapters may be different, so this may
lead to error when no adapter is reported but some DX11 adapters
are available. This fix makes QueryAdapterInfo to report only
adapters available for DX11. Doc is also updated.
=> [Disp] Fix QueryAdapterInfo to report DX11 adapters only

_studio/shared/src/mfx_vpp_vaapi.cpp
set output_background_color to fix RGB32->RGB32 composition with tile
incorrect output issue
Signed-off-by: Yuqin Wei <yuqin.wei@intel.com>
=> fix RGB32->RGB32 composition with tile issue

doc/mediasdk-man.md
Currently MFXQueryAdapter* functions results corresponds to
DX11 adapters enumeration only. Added note about that to
make it more clear for user. Multiple Monitors section
is referenced for more explanation.
=> [doc] Add note for MFXQueryAdapter* functions

_studio/shared/include/libmfx_core.h, _studio/shared/include/libmfx_core_vaapi.h, _studio/shared/include/mfx_utils.h, _studio/shared/src/libmfx_core.cpp, _studio/shared/src/libmfx_core_vaapi.cpp
Part of core refactored:
- improved sts checks
- added explicit override specifiers
- clean up in checking macro
- added templatized inheritance  for future flexible integration of oneVPL cores
- more clear areas of responsibilities for each core established, reduced abstraction leaks from HW core to SW core
- multiple minor code style changes
- some alignment between OS and CS codebases done
- missing mutexes added
=> core: refactored part of core as prerequisite for future oneVPL changes

_studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h, _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp, _studio/mfx_lib/mctf_package/mctf/src/mctf_common.cpp, _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp, _studio/shared/include/mfx_config.h
A segmentation faul was happening because the ouput pointer was not
being assigned when the previous frame was assigned as a P frame to
be denoised and the next frame happened to be and I frame which
also needed to be denoised. The second frame (I frame) was not able
to get the actual output pointer for itself and that caused the
segmentation fault.
The next part addresses the DEVICE_FAILED issue, for this system
checks what is the platform using the filter and based on that
compares if the input width and height are supported, if not
then MCTF disables itself.
Issue: https://github.com/Intel-Media-SDK/MediaSDK/issues/2412
Test:  Manual testing based on MDP-64761
=> [MCTF] Segmentation fault bug fix related to missing output pointer

_studio/shared/src/libmfx_core_vaapi.cpp
According to standard explicit template instantiation will
instantiate only members already declared at the point of
this explicit instantiation
fixes #2418
=> core: fix clang 11 build

samples/sample_multi_transcode/src/pipeline_transcode.cpp
Enable MBQP for all encoders in sample_multi_transcode
Application should not know where mbqp is supported.
=> [samples] Enable MBQP for all codecs in SMT

_studio/mfx_lib/mctf_package/mctf/src/mctf_common.cpp
Prior to gcc-11 various C++ headers in gcc included `<limits>` even though
it was not strictly necessary; this results in the compiler having to
parse unnecessary code and thus slows down compilation for everyone. 
Those unnecessary #includes of `<limits>` have been removed and
applications which need the `<limits>` header file need to explicitly
include it.
Without the patch, when compiling with gcc-11 you will get this error:
```
/builddir/build/BUILD/MediaSDK-intel-mediasdk-20.3.0/_studio/mfx_lib/mctf_package/mctf/src/mctf_common.cpp:
In function 'mfxU16 CalcNoiseStrength(double, double)':
/builddir/build/BUILD/MediaSDK-intel-mediasdk-20.3.0/_studio/mfx_lib/mctf_package/mctf/src/mctf_common.cpp:2302:37:
error: 'numeric_limits' is not a member of 'std'
 2302 |     if (std::fabs(NSC) <= …
```
=> fix compilation errors with GCC-11

_studio/shared/umc/io/umc_va/src/umc_va_linux.cpp
VAProfileAV1Profile1 is removed on gen12.
Signed-off-by: Li Zefu <zefu.li@intel.com>
=> [AV1d] Correct AV1 decode profile usage, VAProfileAV1Profile0 is used for 420 8 bit and 10 bit

_studio/mfx_lib/cmrt_cross_platform/include/cmrt_cross_platform.h, _studio/mfx_lib/mctf_package/mctf/src/mctf_common.cpp, _studio/shared/asc/src/asc.cpp
External BRC for AVC depends on some CM programs which are not loaded on
RKL, so the encoder can't be setup for AVC external BRC on RKL
Example:
ffmpeg -hwaccel qsv -c:v h264_qsv -i input.h264 -c:v h264_qsv -extbrc 1
output.h264
[h264_qsv @ 0x5643f4c60010] Error initializing the encoder: device
failed (-17)
Error initializing output stream 0:0 -- Error while opening encoder for
output stream #0:0 - maybe incorrect parameters such as bit_rate, rate,
width or height
Conversion failed!
=> [avce] Fix external BRC for AVC on RKL

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy.cpp
Fix issue that pushing frames with temporal_layer_id > 0 to DPB when
Rolling I is enabled. Because Rolling I is only expected on the frames
which temporal_layer_id is 0, and its reference frame should be layer 0
as well.
=> [HEVCe] Fix DPB handling issue when RollingI is enabled

samples/sample_vpp/src/sample_vpp_parser.cpp
When we use pipeline with reset, for example:
```
sample_vpp.exe -i hevc.yuv -sw 1920 -sh 1080 -dw 720 -dh 480 -scc nv12 -dcc nv12 -o 720x480_vpp.yuv -d3d \ 
-iopattern d3d_to_d3d  -reset_start 50 -dw 720 -dh 480 -denoise 32 -reset_end
```
We access to a non-existed vector element pParams->colorfillParam[paramID]
https://github.com/Intel-Media-SDK/MediaSDK/blob/3a7ed88055b8d1bbe7812c29a51758a9b319f7c8/samples/sample_vpp/src/sample_vpp_config.cpp#L117
=> sample_vpp: fix reset with colorfillParam

_studio/mfx_lib/encode_hw/hevc/agnostic/g12/hevcehw_g12_caps.cpp
Reverts Intel-Media-SDK/MediaSDK#2440
MDP-65024
=> Revert "[HEVCe] Support B frames for all target usage with LowPower on"

_studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h, _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp, _studio/mfx_lib/mctf_package/mctf/include/mctf_common.h, _studio/mfx_lib/mctf_package/mctf/src/mctf_common.cpp, _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp, _studio/shared/asc/src/asc.cpp, _studio/shared/include/mfx_config.h
In-place denoising is not appropriate as input frames
still used by decoder for frame decoding/generation,
changed current approach with new encoder internal 2
frame buffer for denoising frame generation, then that
frame is used to intercept the input frame at the
encoder execute call
Issue: MDP-64761
Test:  Manual testing
=> MCTF: Substitute in-place filtering with intercepting output

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_roi.cpp
Fixes [#2013](https://github.com/Intel-Media-SDK/MediaSDK/issues/2013).
Change (0 0 0 0) ROIs instead of removing them.
=> [hevce] Expand zero ROI to minimum supported size

_studio/shared/include/cm_mem_copy.h, _studio/shared/src/cm_mem_copy.cpp
Issue: MDP-64809 VSMGWL-33362
Test: manual test
=> [core] Use typed arguments instead of void* in gpu_copy

_studio/mfx_lib/shared/src/mfx_common_int.cpp
The framerate check logic was incorrectly translated to
the MFX_CHECK trace in commit 2f54a3458c5b (#2397).
That is, the previous logic allowed 0/1 and 0/0 as valid
framerates.  The only disallowed framerate is when the
denominator is zero (0) with a non-zero numerator (e.g. 30/0).
Fixes #2489
=> Fix framerate check in frame info

_studio/mfx_lib/encode_hw/hevc/agnostic/g12/hevcehw_g12_caps.cpp
Previously #2440 got regression due to media driver's change to support B frame
for speed mode was not been merged into master branch yet at that moment. Since
media driver's related change has been merged into mater branch as
intel/media-driver@63ff905, this corresponding MSDK's change can work
functionally on speed mode.
Signed-off-by: Jeremy Shang <jeremy.shang@intel.com>
=> [HEVCe] Support B frames for all target usage with LowPower on

_studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp
This reverts commit fa8db613c8ec13fdf572777436b330138cf8ccb6.
=> Revert "[VP9e] Use vaSyncBuffer in VAAPIEncoder::QueryStatus"

_studio/shared/src/libmfx_core_vaapi.cpp, doc/mediasdk-man.md
=> [core] SetHandle returns DEVICE_FAILED on unsupported systems

_studio/shared/umc/codec/av1_dec/include/umc_av1_decoder.h, _studio/shared/umc/codec/av1_dec/src/umc_av1_decoder.cpp, _studio/shared/umc/codec/av1_dec/src/umc_av1_frame.cpp
Following 3 issues are fixed in this PR:
1) error buffer status, which cause buffer be unmmaped twice.
2) For all key frame stream,  buffer be overwrited when it is still be used by APP side.
3) When non display frame be repeated, frame should wait for it be repeated, then release.
=> Fix  3 AV1 decode issues with system memory

_studio/mfx_lib/shared/src/mfx_vpx_dec_common.cpp
Currently the film grain synthesis is always disabled when apply_grain
is 1, the reason is p_in->mfx.FilmGrain is ignored when getting the
video parameters
=> av1d: fix film grain

_studio/shared/umc/codec/av1_dec/include/umc_av1_dec_defs.h
The mininal OBU FRAME HEADER size is 3 when showing an existing frame.
The repeated frame will be ignored if not set MINIMAL_DATA_SIZE to 3
when running a command below:
ffmpeg -hwaccel qsv -c:v av1_qsv -i av1-show-existing-frame.ivf -vf
'hwdownload,format=nv12' output.yuv
=> av1d: set MINIMAL_DATA_SIZE to 3

samples/sample_common/src/vaapi_device.cpp, samples/sample_misc/wayland/include/class_wayland.h, samples/sample_misc/wayland/src/class_wayland.cpp, samples/sample_misc/wayland/src/listener_wayland.cpp
The issue at here when RenderFrame exits, does not mean
corresponding wl_buffer is not used anymore by weston.
So, the wl_buffer has be wait until buffer_release function
call out under wl_buffer_listener get trigger. Than only
consider wl_buffer is no longer used anymore by weston and
safe to use by previous upper component like vpp csc.
The implementation code fixed at here is to prevent surface
get overwrite and used back by vpp csc inside sample_decode
when wl_buffer still not yet release when RenderFrame exits.
Platform: EHL, TGL-U, TGL-H
OS: Yocto native wayland weston
Tested:
./sample_decode h264 -i Puppies_1920x1080.h264 -rwld -rgb4 -f 30
Signed-off-by: Lim Siew Hoon <siew.hoon.lim@intel.com>
=> [sample_misc] Fix video stuttering during wayland rendering

doc/mediasdk-man.md
EndOfStream field was deprecated since API 1.17
=> Updated information about EndOfStream field in manual

samples/sample_decode/include/pipeline_decode.h, samples/sample_decode/src/pipeline_decode.cpp, samples/sample_decode/src/sample_decode.cpp
Option -disable_film_grain is added to disable film grain application
even if apply_grain is 1 in a stream
Example:
sample_decode av1 -hw -vaapi -disable_film_grain -i av1-film_grain.ivf
-o /dev/null
=> sample_decode:av1 add option to disable film grain application

_studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_va_packer_lin.cpp, _studio/mfx_lib/encode_hw/shared/ehw_utils_vaapi.cpp
To enable dynamic slice size, use MaxSliceSize to specify maximum slice size in bytes.
Signed-off-by: Jeremy Shang <jeremy.shang@intel.com>
=> [HEVCe] Support Dynamic Slice Size in refactor code

samples/sample_multi_transcode/src/pipeline_transcode.cpp
According to MediaSDK man SetHandle should be performed before any actual library usage: https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/mediasdk-man.md#working-with-va-api-applications
=> [smt] Move SetFrameAllocator call according to MediaSDK manual

_studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h, _studio/shared/umc/codec/h264_dec/src/umc_h264_task_supplier.cpp
Fix the issue about some h264 streams which have a wrong way to calculate frame_num.
Issue: MDP-64211, MDP-48207
=> [h264d] Unmark the duplicated frame_num with the coming frame in DPB

_studio/mfx_lib/shared/src/mfx_common_decode_int.cpp
There is only the conversion from MFX_FOURCC_YUV444 to UMC::GRAY.
It will cause UMC:GRAY is converted to MFX_FOURCC_NV12 and fire
the assertion in debug build.
=> Add the conversion from UMC::GRAY to MFX_FOURCC_YUV444

.github/workflows/ubuntu.yml
Run on my side (you need to merge in PR to see it triggerred): https://github.com/dvrogozh/MediaSDK/actions/runs/429344132
As of now runs ~10 mins. Covers gcc-10 and clang-10 on ubuntu 20.04. Misses build of sample_opencl_plugin.
=> ci: enable github actions

samples/sample_multi_transcode/src/pipeline_transcode.cpp
Currently loop in CTranscodingPipeline::Decode() ignores m_bForceStop
flag.
Issue: MDP-65336
=> [smt] Process StopSession when timeout is set

_studio/mfx_lib/mctf_package/mctf/src/mctf_common.cpp
It didn't work in joined sessions because
opaqueu handles search wasn't done across all sessions.
=> [AVCe] Fixed broken opaque memory support in MCTF

_studio/mfx_lib/decode/av1/src/mfx_av1_dec_decode.cpp, _studio/shared/umc/codec/av1_dec/include/umc_av1_decoder.h, _studio/shared/umc/codec/av1_dec/include/umc_av1_va_packer_vaapi.h, _studio/shared/umc/codec/av1_dec/src/umc_av1_va_packer_vaapi.cpp, _studio/shared/umc/codec/vp9_dec/src/umc_vp9_va_packer.cpp
Enable dynamic gpu session priority feature for av1 decoder.
=> [AV1d] Enable dynamic gpu session priority for av1 decoder

samples/sample_multi_transcode/src/pipeline_transcode.cpp
1. MFX_ERR_UNSUPPORTED will be reported when transcoding from I420/nv12 to HEVC.
2. It will print MFX_ERR_MORE_DATA, but this error doesn't effect the result, So fix it.
Issue: VCD-2398, VCD-2486
=> [smt] Fix the unsupported issue of transcoding from I420/nv12 to HEVC

.github/workflows/ubuntu.yml
Github images added clang-11 package, but somehow /usr/bin/clang-11
is missed. So, we better check that target is available rather than
package.
=> ci: fix detection of clang-11

doc/samples/readme-encode_linux.md, samples/sample_encode/src/sample_encode.cpp
Issue: MDP-65302
Test: manually
./sample_encode h265 -i in.yuv -o out_y210.h265 -w 1920 -h 1080 -p010 -n 200 -ec::y210
./sample_encode h265 -i in.yuv -o out_nv12.h265 -w 1920 -h 1080 -p010 -n 200 -ec::nv12
and others
=> [sample_encode] Add flags for forcing output color format

samples/sample_multi_transcode/include/sample_multi_transcode.h, samples/sample_multi_transcode/src/sample_multi_transcode.cpp
Since the allocator parameters (including device handle) for all
sessions were taken from the 0th session, the smt options -iGfx
and -dGfx for the 1st and subsequent sessions were ignoring
=> [smt] Fix ext allocator parameters for multi GPUs case

_studio/mfx_lib/plugin/CMakeLists.txt
Runtime libraries should not depend on the
dispatcher library.
Thus, don't link h264la runtime plugin library to the
dispatcher.
This fixes a compile error when compiling only the runtime
libraries and no dispatcher is installed yet.
-DBUILD_RUNTIME=ON -DBUILD_DISPATCHER=OFF
=> [h264la]: do not link to dispatcher (libmfx)

_studio/mfx_lib/encode_hw/hevc/agnostic/g12/hevcehw_g12_rext.cpp
In case of HEVC REXT format, HEVC encoder with LowPower ON cannot support
target bitDepth bigger than 10.
=> [HEVCe] Change supported target bitdepth with LowPower ON

_studio/mfx_lib/decode/av1/src/mfx_av1_dec_decode.cpp, _studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp, _studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp, _studio/shared/src/mfx_umc_alloc_wrapper.cpp
Fixes Intel-Media-SDK#2580
HEVC/AV1/JPEG SFC CSC is supported
Signed-off-by: Shawn Li <shawn.li@intel.com>
=> [Decode]Enable CSC via sfc pipeline

_studio/mfx_lib/decode/h264/src/mfx_h264_dec_decode.cpp, _studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp, _studio/shared/src/mfx_umc_alloc_wrapper.cpp, doc/samples/readme-multi-transcode_linux.md, samples/sample_common/include/sample_utils.h, samples/sample_multi_transcode/src/pipeline_transcode.cpp, samples/sample_multi_transcode/src/transcode_utils.cpp
The changes introduces supports of 1->1, 1->N transcode with SFC (previously
only N->1 was supported).
Plus it fixes the bug on library side where decoders couldn't accept surfaces
allocated in addition to what decoder::QueryIOSurf() requested.
Test: ./sample_multi_transcode -dec_postproc -i::h264 in.h264 -o::h264 out.h264 -w 1280 -h 720 -hw
or via par file
-dec_postproc -i::h264 in.h264 -o::h264 out.h264 -w 1280 -h 720 -hw -o::sink
-i::source -o::h265 o1.h265
-i::source -o::h265 o2.h265
=> VDBOX+SFC for 1->1 transcode scenarios

_studio/shared/src/libmfx_allocator_vaapi.cpp
It is to test the FourCC code of a VA Image in the switch statement
=> vaapi: use VA FourCC codes

_studio/mfx_lib/decode/av1/src/mfx_av1_dec_decode.cpp, _studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp, _studio/mfx_lib/shared/include/mfx_common_int.h, _studio/mfx_lib/shared/src/mfx_common_int.cpp
Update output params in QueryIOSurf when output color format changed;
enable for AV1/HEVC
Issue: MDP-65929
Test: manually
=> Update output params in QueryIOSurf for VDBX SFC CSC

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp
VME driver doesn't support 10b->8b and 8b->10b conversions.
Issue: MDP-65185
Test: manually
=> [hevce] Disable bit depth conversion

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp, _studio/mfx_lib/encode_hw/hevc/agnostic/g12/hevcehw_g12_caps.cpp
Remove vdenc422 restriction here, maxChroma can be controlled
by platform caps YUV422ReconSupport reported from driver.
=> [hevce/lib] Remove 422 VDEnc restriction

_studio/shared/umc/codec/h264_dec/src/umc_h264_va_packer.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_va_packer_vaapi.cpp
value of chroma sample location was not set in lib
Issue: MDP-66020
Test: manually
=> Fix VDSFC bit mismatch for vaapi

_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
AdaptiveMaxFrameSize should be inherited from init to reset
=> Inherit AdaptiveMaxFrameSize from init to reset

_studio/mfx_lib/shared/src/mfx_common_int.cpp
When SW decode, MFX_DEC_VIDEO_POSTPROCESS_DISABLE should defined, there is no
SFC usage, should skip this function.
=> [Decode]Optimize function handle when disable hw dec vedio postprocess

_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
Previously DDI caps for interlace were confused, for VA_ENC_INTERLACED_FIELD (==2) ddi_caps.NoInterlacedField was set to 1, which means that interlaced field IS NOT supported, and vice versa, for VA_ENC_INTERLACED_NONE (==0) or VA_ATTRIB_NOT_SUPPORTED ddi_caps.NoInterlacedField was set to 0, which means that interlaced field IS supported.
Fixed this logic.
=> [AVCe] Correct VA Interlaced caps reading

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp
Reverts Intel-Media-SDK/MediaSDK#2635 because internal beh_hevce_sei_hdr-plugin_hevcehw test fails
=> Revert "[hevce] Disable bit depth conversion"

doc/samples/readme-encode_linux.md, doc/samples/readme-multi-transcode_linux.md, samples/sample_common/src/parameters_dumper.cpp, samples/sample_encode/include/pipeline_encode.h, samples/sample_encode/src/pipeline_encode.cpp, samples/sample_encode/src/sample_encode.cpp, samples/sample_multi_transcode/include/pipeline_transcode.h, samples/sample_multi_transcode/src/pipeline_transcode.cpp, samples/sample_multi_transcode/src/transcode_utils.cpp
Issue: MDP-66051
Test: manually
Usage examples:
sample_encode.exe:
VPP based bit-depth conversion (the conversion will be done due to the different forсс):
h265 -i Cactus_ProRes_1280x720_50f.p010.yuv -o out.hevc -w 1280 -h 720  -lowpower:off -p010 -ec::nv12
Encoder internal bit-depth conversion:
h265 -i Cactus_ProRes_1280x720_50f.p010.yuv -o out.hevc -w 1280 -h 720  -lowpower:on -TargetBitDepthLuma 8 -TargetBitDepthChroma 8 -p010
sample_multi_transcode.exe:
VPP based bit-depth conversion (the conversion will be done due to the different forсс):
-i::h265 off.hevc -f 60 -h 720 -lowpower:off -n 10  -w 1280 -hw_d3d11 -o::h265 out_out_off.h265 -ec::nv12 -dc::p010
Encoder internal bit-depth conversion:
-i::h265 on.hevc -f 60 -w 1280 -h 720 -lowpower:on -n 10 -hw_d3d11 -o::h265 out_out_on.h265 …
=> [HEVC][10bit] Support encode 8bit from 10bit for sampe_encode and sample_multitranscode

doc/samples/readme-multi-transcode_linux.md, samples/sample_decode/src/pipeline_decode.cpp, samples/sample_multi_transcode/src/transcode_utils.cpp
Issue: None
Test: manually
Note: there where the system memory was by default, it remained as is
=> Move default memType for win from d3d9 to d3d11

_studio/mfx_lib/encode_hw/hevc/agnostic/g12/hevcehw_g12_scc.cpp
Correct VPS header for SCC according to HEVC Spec
Issue: MDP-66321
Test: Manually
=> [HEVCe] Correct VPS header for SCC

samples/sample_misc/wayland/src/class_wayland.cpp
Replicate similar libVA wayland change.
https://github.com/intel/libva/commit/283f776a9649dcef58b47958c1269499adfa1cd4
Platform: ADL-S, EHL, TGL
OS: Yocto native wayland weston
Tested:
./sample_decode h265 -i Puppies_3840x2160.265 -rwld -rgb4
Issue: #2592
Signed-off-by: Cheah, Vincent Beng Keat <vincent.beng.keat.cheah@intel.com>
=> Don't try to autheticate with render node

samples/sample_common/src/d3d11_device.cpp
Due to https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/for-best-performance--use-dxgi-flip-model
=> Use DXGI_SWAP_EFFECT_FLIP_DISCARD for rendering

_studio/shared/umc/codec/jpeg_enc/src/jpegenc.cpp
Before for non-zero colMCU ptr was set without taking into account
size of macropixel.
Issue: MDP-66145
=> [jpege] Fix color conversion for BGRA

_studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp, _studio/shared/umc/codec/jpeg_dec/include/umc_mjpeg_mfx_decode_base.h, _studio/shared/umc/codec/jpeg_dec/src/umc_mjpeg_mfx_decode_base.cpp
1) Invalid input produces error codes, not asserts.
2) DecodeHeader() to use documented return status.
=> [jpegd] Improve processing of invalid headers

_studio/mfx_lib/encode_hw/shared/ehw_task_manager.cpp, _studio/mfx_lib/encode_hw/shared/ehw_task_manager.h
Frame skip after recode in parallel submit leads to getting stuck
in Prepare stage for one task and losing parallel submit.
Issue: MDP-62789
Test: manual, hevce_swbrc_slw_interlaced-plugin_hevcehw
=> [HEVCe/AV1e] Fix parallel submission in task manager

_studio/shared/umc/codec/jpeg_dec/src/umc_jpeg_frame_constructor.cpp
This is to fix a potetial issue when decoding fuzzer clip, if OxFF exists in
SOS segment, will cause calculation error, lead to incorrect memcpy call
=> [jpegd] Skip searching segment mark among JM-SOS according to the length

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_impl.cpp, _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_interlace.cpp, _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_interlace.h, _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy.cpp
When the 1st field is skipped the 2nd one must be skipped too.
In this case the 2nd field should take the 1st one as a reference.
Issue: MDP-62788
Tested: manual
=> [hevce/swbrc] Fix the skipping of second fields

_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
MSDK switches to HORIZONTAL w/ warning
=> [AVCe] Non-overlapping Rolling-I is not supported

_studio/shared/umc/codec/h264_dec/src/umc_h264_mfx_supplier.cpp
"Height" was writen as "Width" by mistake.
=> [AVCd] fix one Vdbox SFC coding issue

api/mfx_dispatch/windows/src/mfx_dxva2_device.cpp, api/mfx_dispatch/windows/src/mfx_load_dll.cpp
Win7 is minimum supported version for SetThreadErrorMode
=> [win][disp] Fix win version from vista to win7

.github/workflows/ubuntu.yml
clang-13 got dedidated apt repo. Main llvm repo now has clang-14.
=> ci: switch to clang-13 dedicated apt repo

api/mfx_dispatch/linux/mfxloader.cpp
Regressed by #2692. From [error log](https://github.com/Intel-Media-SDK/MediaSDK/files/6949089/intel-media-sdk-21.3.1.log):
```c++
api/mfx_dispatch/linux/mfxloader.cpp:193:23: error: use of undeclared identifier 'ONEVPLRT'
libs.emplace_back(ONEVPLRT);
^
api/mfx_dispatch/linux/mfxloader.cpp:194:43: error: expected ')'
libs.emplace_back(MFX_MODULES_DIR "/" ONEVPLRT);
^
api/mfx_dispatch/linux/mfxloader.cpp:194:22: note: to match this '('
libs.emplace_back(MFX_MODULES_DIR "/" ONEVPLRT);
^
api/mfx_dispatch/linux/mfxloader.cpp:213:23: error: use of undeclared identifier 'ONEVPLRT'
libs.emplace_back(ONEVPLRT);
^
api/mfx_dispatch/linux/mfxloader.cpp:214:43: error: expected ')'
libs.emplace_back(MFX_MODULES_DIR "/" ONEVPLRT);
^
api/mfx_dispatch/linux/mfxloader.cpp:214:22: note: to match this '(' …
```
=> [21.3.0 vs. 21.3.1 regression] Unbreak build on IA32

samples/sample_encode/src/pipeline_encode.cpp
=> Avoid calling V4L2 method if it's not enabled for the pipeline

samples/sample_common/src/vaapi_utils_drm.cpp
If we are using I915_FORMAT_MOD_Y_TILED which is needed for
NV12 format then modifiers need to be enabled which can be passed
as flags argument to ioctl.
Issue: None
Test: Manually
Signed-off-by: Sodhi, Vunny <vunny.sodhi@intel.com>
=> Fixed tile modifier issue for NV12 format

_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp, _studio/shared/include/mfx_vpp_interface.h
Fix: https://github.com/Intel-Media-SDK/MediaSDK/issues/2721
Number of input composite layers can be dynamically changed at runtime, but should not exceed the initial counts.
Signed off by: jay.yang@intel.com
=> [VPP] Fix increasing num of input channels doesn't work

_studio/shared/src/mfx_vpp_vaapi.cpp
1. Modify JPEG RGB444 from partial acceleration to hardware
acceleration decode
2. Modify output format’s color_range to VA_SOURCE_RANGE_FULL
Cmd:./sample_decode jpeg -i /home/gta/IMG_0425.bmp_RGB_444_100.jpg -o test.yuv -hw
Issue: MDP-66601 & MDP-66823
Test: manually
=> [Jpegd]Enable HW to decode jpeg rgb444 on Linux

_studio/mfx_lib/shared/src/mfx_common_int.cpp
MFX_EMFX_ERR_INVALID_VIDEO_PARAM seems to be incorrect status;
return MFX_ERR_UNSUPPORTED when output format is unsupported.
request from: #2780
=> [Decode CSC] return unsupport status when query unsupport output format

_studio/shared/umc/codec/h264_dec/src/umc_h264_dec_slice_decoder_decode_pic.cpp
The bitstream shall not contain data that result in picViewIdxLX
less than 0.
Test: manually
=> [H264d] check the index of view reference

_studio/shared/umc/codec/jpeg_dec/src/jpegdec.cpp
pDst ptr should not exceed destination buffer size
Test: manually
=> [Jpegd] check the pointer of sampled up output row

tutorials/simple_2_decode/src/simple_decode.cpp
if bEnableOutput==true -> Decoded frames will be written to the output file
if bEnableOutput==false-> Decoded frames will NOT be written to the output file
=> Comment regarding frames writing to disc changed

builder/FindPackages.cmake, samples/sample_common/CMakeLists.txt, samples/sample_decode/CMakeLists.txt, samples/sample_misc/wayland/CMakeLists.txt, samples/sample_misc/wayland/include/class_wayland.h, samples/sample_misc/wayland/src/class_wayland.cpp, samples/sample_multi_transcode/CMakeLists.txt
Similar fix for [this](https://github.com/Intel-Media-SDK/MediaSDK/pull/2803).
However, this version will use wayland-scanner to auto generate the wayland binding code.
=> sample_misc: Addin WAYLAND DMABUF support to render NV12 on Wayland.

_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
SelectThreadDependencyPattern is very CPU time expensive on dGPU.
CM_NONE_DEPENDENCY is a default mode so we can just drop the call.
=> [vpp] Removed SelectThreadDependencyPattern call

samples/sample_encode/src/pipeline_encode.cpp
Without this patch, -trows and -tcols are ignored actually
$ sample_encode vp9 -i input.yuv -w 3840 -h 2160 -trows 2 -tcols 2 -o \
out.ivf
=> sample_encode: vp9 supports tile encoding from mfx version 1029

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_packer.cpp
This reverts commit cf9a1927289ae1133df768d06677d8c477555fd4.
=> Revert "[HEVCe] Use long start code for IDR frame"

_studio/shared/umc/codec/h265_dec/include/umc_h265_dec_defs.h, _studio/shared/umc/codec/h265_dec/include/umc_h265_mfx_utils.h, _studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_supplier.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_utils.cpp
In HEVC MFXVideoDECODE_DecodeHeader(), the framerate is calculated from SPS, but the framerate should combine the info from VPS and SPS according to the spec. This PR fixes this.
=> [Decode][hevcd] Add hevc FrameRate parameters parsing from VideoParamSet

_studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp, _studio/shared/umc/codec/h265_dec/include/umc_h265_bitstream_headers.h, _studio/shared/umc/codec/h265_dec/include/umc_h265_dec_defs.h, _studio/shared/umc/codec/h265_dec/include/umc_h265_frame.h, _studio/shared/umc/codec/h265_dec/src/umc_h265_sei.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp
For #2597 
Attach the **MFX_EXTBUFF_MASTERING_DISPLAY_COLOUR_VOLUME**  and **MFX_EXTBUFF_CONTENT_LIGHT_LEVEL_INFO** to outputSurface when you need this info for HEVC HDR transfer.
``` 
mfxFrameSurface1& surf;
// Mastering Display Colour Volume SEI info
mfxExtMasteringDisplayColourVolume* pExtPar_MasteringDisplay = new mfxExtMasteringDisplayColourVolume{};
pExtPar_MasteringDisplay->Header.BufferId = MFX_EXTBUFF_MASTERING_DISPLAY_COLOUR_VOLUME;
pExtPar_MasteringDisplay->Header.BufferSz = sizeof(mfxExtMasteringDisplayColourVolume);
// Mastering Content Light Level info
mfxExtContentLightLevelInfo* pExtPar_ContentLight = new mfxExtContentLightLevelInfo{};
pExtPar_ContentLight->Header.BufferId = MFX_EXTBUFF_CONTENT_LIGHT_LEVEL_INFO;
pExtPar_ContentLight->Header.BufferSz = …
```
=> [HEVCd] Added HDR SEI info parsing for HEVC decoding

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp
The SDK always use VDEnc mode for AVC & VP9 encoding on JSL & EHL by
default. To keep the hehavior consistent across codecs, use VDEnc mode
by default for HEVC encoding as well
=> [hevce] Only VDEnc mode is available on JSL & EHL

_studio/mfx_lib/decode/av1/src/mfx_av1_dec_decode.cpp, _studio/shared/umc/codec/av1_dec/src/umc_av1_decoder.cpp
If there is a new av1 sequence header connected to old one with different resolution, MSDK lib will return MFX_ERR_INCOMPATIBLE_VIDEO_PARAM.
Signed-off-by: ZefuLI <zefu.li@intel.com>
=> [av1d] add support av1d multiple sequence headers with different resolution

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp
VME doesn't support A2RGB10 input
=> [hevce] Use VDEnc by default for A2RGB10 input

_studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_utils.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp, _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_decoder.cpp
Report CropW/CropH using conformance crops, and display crops.
[Internal]
OSPR: Auto
Commit_Type: Bugfix
Platforms: N/A
OS: N/A
Feature impact: N/A
Resolves: MDP-63613
Related-to: MDP-63613
Klocwork: N/A
TP_Passed: N/A
IP Scan: N/A
Open/Embargo Dependency: N/A
=> [PATCH] [HEVCd] disp win offset should be added to crop (#4398)

_studio/shared/umc/codec/av1_dec/include/umc_av1_decoder.h, _studio/shared/umc/codec/av1_dec/src/umc_av1_decoder.cpp, _studio/shared/umc/codec/av1_dec/src/umc_av1_decoder_va.cpp, _studio/shared/umc/codec/av1_dec/src/umc_av1_va_packer_vaapi.cpp
This PR fix two issues caused by samll decbufsize:
1. Frame_id check failed in ReadUncompressedHeader.
2. Duplicate submission of the decode buffer in va Execute.
=> [Decode] Fix av1d issue with small decbufsize

_studio/mfx_lib/decode/vc1/src/mfx_vc1_decode.cpp
FFMpeg-qsv splits the bitstream into AVpackets, the small AVpackets may
cause this issue.
=> [Decode] Fix VC1d issue when frame_type is NONE_PICTURE.

tests/unit/suites/mfx_dispatch/linux/mfx_dispatch_test_main.h, tests/unit/suites/tracer/linux/mfx_tracer_test_main.h
gcc 12 changed header dependencies. It now requires to explicitly include the `<memory>` C++ header for using `std::unique_ptr`. 
Otherwise, the following build error will occur: `‘unique_ptr’ in namespace ‘std’ does not name a template type`.
See documentation about [porting to gcc 12](https://gcc.gnu.org/gcc-12/porting_to.html).
Fixes #2940
=> Fix build with gcc 12

_studio/shared/umc/codec/h265_dec/include/umc_h265_bitstream_headers.h, _studio/shared/umc/codec/h265_dec/src/umc_h265_bitstream_headers.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_supplier.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_sei.cpp, _studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp
HEVC has VLC coding which cannot get bitsteram header size.
To avoid get bits operation out of bound ,need to check remaining
bits size before reading.
=> Fix HEVC bitstream buffer overflow issue

_studio/shared/umc/codec/h264_dec/include/umc_h264_bitstream_headers.h, _studio/shared/umc/codec/h264_dec/src/umc_h264_dec_bitstream_headers.cpp, _studio/shared/umc/codec/h264_dec/src/umc_h264_mfx_supplier.cpp, _studio/shared/umc/codec/h264_dec/src/umc_h264_task_supplier.cpp
AVC has VLC coding which cannot get bitsteram header size.
To avoid get bits operation out of bound ,need to check remaining
bits size before reading.
=> fix AVC bitstream buffer overflow issue

tutorials/simple_5_transcode/src/simple_transcode.cpp
This is a PSIRT issue caused by the memory leak from app.
=> [Deocde] Fix Memory leak in simple_5_transcode app

_studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp, doc/mediasdk-man.md
This PR was used to discuss the HEVCd HDR SEI flag issue which discussed in https://github.com/Intel-Media-SDK/MediaSDK/issues/2597
*   Option 1: Add a new API.
*   Concern: 1.x API is frozen, so this would limit usage to oneVPL POR HW (>= Gen12).
*   Option 2: Overload existing field InsertPayloadToggle. (used in this PR)
*    Concern: "InsertPayload" doesn't make much sense when decoding. These extBufs were defined with encoding in mind.
=> [Decode] Add flag for HEVCd HDR SEI parsing result

samples/sample_common/src/vaapi_utils.cpp
fix: remove the invalid close fd, AcquireVASurface is used for surface to surface. no fd is needed.
=> fix: remove the invalid close fd

_studio/shared/src/libmfx_allocator_vaapi.cpp
In FFmpeg, VA_FOURCC_XYUV is used for 4:4:4 8bit content when vaapi is
used for hardware acceleration, hence we will have to use VA_FOURCC_XYUV too
for 4:4:4 8bit content when qsv is used on Linux because qsv is based on
vaapi, and map VA_FOURCC_XYUV to MFX_FOURCC_AYUV in FFmpeg. So mapping
VA_FOURCC_XYUV is needed in the SDK.
$ ffmpeg -y -hwaccel qsv -i in444.mp4 -vf "hwdownload,format=vuyx" -f
null -
=> vaapi: recognize VA_FOURCC_XYUV VAImage

_studio/shared/src/libmfx_allocator_vaapi.cpp
In FFmpeg VAAPI path, the following fourcc codes are used for 12bit contents
VA_FOURCC_P012 4:2:0 12bit
VA_FOURCC_Y212 4:2:2 12bit
VA_FOURCC_Y412 4:4:4 12bit
We should use these codes too in FFmpeg QSV path, hence add mapping P012/Y212/Y412 here
=> vaapi: recognize P012, Y212, and Y412 VAImages (#2768)

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp
According to: https://github.com/intel/media-driver/blob/master/docs/media_features.md, Only VDENC supports RGB encoding, so use lowpower when input RGB data.
=> hevce: use Low Power mode for RGB encoding by default

_studio/shared/umc/codec/h265_dec/include/umc_h265_bitstream_headers.h
The “m_maxBsSize” is data of type “int”, and BitsDecoded() returns data of type “unsigned long long”, when the latter is large enough, the former minus the latter may get a positive number, although the former is smaller than the latter, which will causes no exception to be thrown(even if there is not enough data to read).
=> [Decode]Fix hevc decode issue

_studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp
The data length exceeding the max length of data.
Add data length of bitstream check.
=> [Decode] Fix memory out-of-bounds issue for VP9

CMakeLists.txt
=> [Media Common] Bump up version to 23.2.2
