- _studio/shared/src/mfx_vpp_vaapi.cpp
> [vpp] Add P010 to RGB4 conversion support

- samples/sample_fei/include/auxiliary_interfaces.h
- samples/sample_fei/include/encoding_task.h
- samples/sample_fei/include/encoding_task_pool.h
- samples/sample_fei/include/fei_encode.h
- samples/sample_fei/include/fei_encpak.h
- samples/sample_fei/include/fei_preenc.h
- samples/sample_fei/include/pipeline_fei.h
- samples/sample_fei/include/predictors_repacking.h
- samples/sample_fei/include/refListsManagement_fei.h
- samples/sample_fei/include/sample_fei_defs.h
- samples/sample_fei/src/auxiliary_interfaces.cpp
- samples/sample_fei/src/fei_encode.cpp
- samples/sample_fei/src/fei_encpak.cpp
- samples/sample_fei/src/fei_preenc.cpp
- samples/sample_fei/src/fei_streamout_pak_repacking.cpp
- samples/sample_fei/src/pipeline_fei.cpp
- samples/sample_fei/src/refListsManagement_fei.cpp
- samples/sample_fei/src/sample_fei.cpp
Multisession NN support
MFE support
build check for MFX_VESION
> sample_fei changes merge from internal

- samples/sample_hevc_fei/src/hevc_fei_preenc.cpp
- samples/sample_hevc_fei/src/pipeline_hevc_fei.cpp
- samples/sample_hevc_fei/src/sample_hevc_fei.cpp
Valid lower bound for active references for HW HEVC is 1
> [sample_hevc_fei] Fix allowed range for number of active references

- _studio/shared/include/fast_copy.h
- _studio/shared/umc/core/umc/include/umc_structures.h
The commit addresses CPU utilization regression
> Make FastCopy an atomic function

- _studio/shared/umc/codec/vc1_common/include/umc_vc1_common_defs.h
- _studio/shared/umc/codec/vc1_common/include/umc_vc1_common_tables.h
- _studio/shared/umc/codec/vc1_common/src/umc_vc1_common_tables.cpp
- _studio/shared/umc/codec/vc1_dec/src/umc_vc1_dec_bpic_adv.cpp
- _studio/shared/umc/codec/vc1_dec/src/umc_vc1_dec_frame_va.cpp
- _studio/shared/umc/codec/vc1_dec/src/umc_vc1_dec_pic_com.cpp
- _studio/shared/umc/codec/vc1_dec/src/umc_vc1_dec_pic_com_adv.cpp
Fix for b_picture_fraction usage
> [vc1d] Fix for b_picture_fraction usage

- samples/sample_hevc_fei/src/ref_list_manager.cpp
> [sample_hevc_fei] Fix unsigned type usage in std::abs function

- _studio/hevce_hw/h265/include/mfx_h265_encode_hw_utils.h
- _studio/hevce_hw/h265/src/mfx_h265_encode_hw_par.cpp
- _studio/hevce_hw/h265/src/mfx_h265_encode_hw_utils.cpp
Issue: 39880
Test: manually
Changed P Pyramid interval if
Active Reference is defined by
application.
> [HEVC E]: Fix for P pyramid

- samples/sample_hevc_fei/include/fei_buffer_allocator.h
- samples/sample_hevc_fei/include/ref_list_manager.h
- samples/sample_hevc_fei/include/sample_hevc_fei_defs.h
- samples/sample_hevc_fei/src/fei_buffer_allocator.cpp
- samples/sample_hevc_fei/src/fei_utils.cpp
- samples/sample_hevc_fei/src/ref_list_manager.cpp
Fix align() to work with static assert, fixed assert.
Also fix potential signed/unsigned compilation issues.
> [HEVC FEI SAMPLE] fix align() and compile issues

- samples/sample_hevc_fei/include/fei_utils.h
- samples/sample_hevc_fei/include/hevc_fei_encode.h
- samples/sample_hevc_fei/include/hevc_fei_preenc.h
- samples/sample_hevc_fei/include/pipeline_hevc_fei.h
- samples/sample_hevc_fei/include/sample_hevc_fei_defs.h
- samples/sample_hevc_fei/src/fei_utils.cpp
- samples/sample_hevc_fei/src/hevc_fei_encode.cpp
- samples/sample_hevc_fei/src/hevc_fei_preenc.cpp
- samples/sample_hevc_fei/src/pipeline_hevc_fei.cpp
- samples/sample_hevc_fei/src/sample_hevc_fei.cpp
Added timeout option for HEVC FEI testing and made changes required for enabling this option.
> Timeout option in sample_hevc_fei

- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
Disable MFE 4K due to performance issues
> [h264e]Disable MFE 4K

- samples/sample_hevc_fei/src/ref_list_manager.cpp
- samples/sample_hevc_fei/src/sample_hevc_fei.cpp
Fix sorting RPL candidates due to issue revealed by 38856c9.
> Fix RPL construction in sample_hevc_fei

- _studio/mfx_lib/vpp/src/mfx_vpp_sw_core.cpp
- _studio/mfx_lib/vpp/src/mfx_vpp_utils.cpp
- _studio/shared/include/mfx_vpp_interface.h
- _studio/shared/src/libmfx_allocator.cpp
- _studio/shared/src/libmfx_allocator_vaapi.cpp
- _studio/shared/src/libmfx_core.cpp
- _studio/shared/src/mfx_vpp_vaapi.cpp
- api/include/mfxstructures.h
- samples/sample_common/src/sysmem_allocator.cpp
- samples/sample_common/src/vaapi_allocator.cpp
- samples/sample_vpp/src/sample_vpp_parser.cpp
- samples/sample_vpp/src/sample_vpp_utils.cpp
Successfully run sample_vpp for validation on SKL.
> [vpp] Enable RGB565 to YUY2 color conversion

- _studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils_new.cpp
- _studio/mfx_lib/shared/include/mfx_h264_enc_common_hw.h
- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
- _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
- _studio/shared/src/mfx_static_assert_structs.cpp
Signed-off-by: Nabiullin, Oleg <oleg.nabiullin@intel.com>
> Add missed NAL units size handling

- _studio/mfx_lib/cmrt_cross_platform/src/cmrt_cross_platform.cpp
> Fix for issue #97 related to virtual destructor

- _studio/shared/src/libmfx_allocator_vaapi.cpp
- _studio/shared/src/mfx_vpp_vaapi.cpp
- samples/sample_common/src/vaapi_allocator.cpp
- samples/sample_vpp/src/sample_vpp_parser.cpp
> Add support for P010 to A2RGB10 conversion

- samples/sample_multi_transcode/src/transcode_utils.cpp
Introduced option to disable B-pyramid from CLI
> [sample_multi_transcode] Add -nobref option

- _studio/mfx_lib/CMakeLists.txt
Adjust file names in /opt/intel/mediasdk/lib64 to match MSS naming scheme.
> Fix 'make install'

- _studio/mfx_lib/decode/CMakeLists.txt
- _studio/mfx_lib/decode/vp9/include/mfx_vp9_dec_decode.h
- _studio/mfx_lib/decode/vp9/include/mfx_vp9_dec_decode_hw.h
- _studio/mfx_lib/decode/vp9/include/mfx_vp9_dec_decode_utils.h
- _studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode.cpp
- _studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp
- _studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_utils.cpp
- _studio/mfx_lib/plugin/CMakeLists.txt
- _studio/mfx_lib/plugin/include/mfx_vp9_dec_plugin.h
- _studio/mfx_lib/plugin/src/mfx_vp9_dec_plugin.cpp
- _studio/mfx_lib/shared/src/libmfxsw_decode.cpp
- _studio/mfx_lib/shared/src/mfx_vpx_dec_common.cpp
- _studio/shared/include/mfx_common_linux_bdw.h
- _studio/shared/include/mfx_common_linux_bxt.h
- _studio/shared/include/mfx_common_linux_bxtmin.h
- _studio/shared/include/mfx_common_linux_cfl.h
- _studio/shared/src/libmfx_core_vaapi.cpp
- _studio/shared/umc/codec/vp9_dec/include/umc_vp9_bitstream.h
- _studio/shared/umc/codec/vp9_dec/include/umc_vp9_dec_defs.h
- _studio/shared/umc/codec/vp9_dec/include/umc_vp9_frame.h
- _studio/shared/umc/codec/vp9_dec/include/umc_vp9_utils.h
- _studio/shared/umc/codec/vp9_dec/include/umc_vp9_va_packer.h
- _studio/shared/umc/codec/vp9_dec/src/umc_vp9_bitstream.cpp
- _studio/shared/umc/codec/vp9_dec/src/umc_vp9_utils.cpp
- _studio/shared/umc/codec/vp9_dec/src/umc_vp9_va_packer.cpp
- _studio/shared/umc/io/umc_va/src/umc_va_linux.cpp
- samples/sample_decode/src/pipeline_decode.cpp
> Vp9d enabling

- _studio/mfx_lib/decode/vp9/include/mfx_vp9_dec_decode_hw.h
- _studio/mfx_lib/plugin/include/mfx_vp9_dec_plugin.h
> [VP9d] auto_ptr changed to unique_ptr

- _studio/hevc_fei/h265_fei/src/mfx_h265_fei_encode_hw.cpp
- _studio/hevc_fei/h265_fei/src/mfx_h265_fei_encode_vaapi.cpp
- api/include/mfxfeihevc.h
- api/mediasdk_structures/ts_struct_decl.h
- samples/sample_hevc_fei/src/sample_hevc_fei.cpp
Added FastIntraMode flag support in the library and HEVC FEI sample
> [HEVCe FEI] Introduced FastIntraMode perf. control

- _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
- _studio/shared/include/mfx_config.h
- samples/sample_common/include/sample_defs.h
- samples/sample_vpp/include/sample_vpp_utils.h
- samples/sample_vpp/src/sample_vpp.cpp
- samples/sample_vpp/src/sample_vpp_parser.cpp
> [vpp] Implement run-time HSBC

- samples/sample_fei/src/sample_fei.cpp
Improved memory management for cmd parser; fixed compilation warnings
> sample_fei KW fixes

- _studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode.cpp
- _studio/mfx_lib/shared/src/mfx_common_decode_int.cpp
- _studio/mfx_lib/shared/src/mfx_common_int.cpp
- _studio/mfx_lib/shared/src/mfx_vpx_dec_common.cpp
- _studio/shared/src/libmfx_allocator_vaapi.cpp
- _studio/shared/umc/io/umc_va/src/umc_va_linux.cpp
- samples/sample_common/include/plugin_loader.h
> Enable VP9 codec profile1 support for decoding 8-bit 444

- samples/sample_common/src/brc_routines.cpp
Issue: MDP-40642
Test: manually
> [SAMPLES]: SW BRC regression fix

- _studio/shared/src/cm_mem_copy.cpp
> [vpp] Added loading of mirroring kernel on BDW

- samples/sample_hevc_fei/include/sample_hevc_fei_defs.h
- samples/sample_hevc_fei/src/pipeline_hevc_fei.cpp
- samples/sample_hevc_fei/src/sample_hevc_fei.cpp
> [HEVC FEI SAMPLE] Profile/level command-line options

- _studio/hevc_fei/h265_fei/include/mfx_h265_fei_encode_hw.h
- _studio/hevc_fei/h265_fei/include/mfx_h265_fei_encode_vaapi.h
- _studio/hevc_fei/h265_fei/src/mfx_h265_fei_encode_hw.cpp
- _studio/hevc_fei/h265_fei/src/mfx_h265_fei_encode_vaapi.cpp
- _studio/hevce_hw/h265/include/mfx_h265_encode_hw_ddi.h
- _studio/hevce_hw/h265/src/mfx_h265_encode_vaapi.cpp
- api/include/mfxfeihevc.h
- samples/sample_hevc_fei/include/hevc_fei_encode.h
- samples/sample_hevc_fei/include/sample_hevc_fei_defs.h
- samples/sample_hevc_fei/src/hevc_fei_encode.cpp
- samples/sample_hevc_fei/src/pipeline_hevc_fei.cpp
- samples/sample_hevc_fei/src/sample_hevc_fei.cpp
Signed-off-by: Jing SUN <jing.a.sun@intel.com>
> [HEVC FEI ENCODE] Add repackctrl & repackstat supports

- _studio/mfx_lib/mctf_package/mctf/src/mctf_common.cpp
Added support for platforms above SKL, by loading
SKL kernels as default.
Issue: MDP-41158
Test: beh_vpp_mctf_douse
> [MCTF HW] Support for CFL, GLK and other platforms

- _studio/mfx_lib/mctf_package/mctf/src/mctf_common.cpp
- _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
Fix VPP issue reported by Clockwork for PV5 release.
> [VPP] KW fixes

- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils_new.cpp
- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
Fix for issues reported by KlockWork for PV5 release.
Issue: MDP-42116
> [H264e HW] KW hits in Opensource

- _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
- _studio/shared/include/mfx_mfe_adapter.h
- _studio/shared/src/mfx_mfe_adapter.cpp
fix performance for ABR workloads with different framerates
> [MFE] fix multi-framerate performance

- _studio/shared/asc/src/asc_sse4_impl.cpp
- _studio/shared/asc/src/iofunctions.cpp
Fix Klockwork issue for PV5 open source seen in scene change detection.
> [VPP] fix KW PV5 issue for asc

- doc/samples/readme-metrics_monitor_linux.pdf
> metrics_monitor documentation update

- CODEOWNERS
Reviewers added by request of Oleg Nabiullin.
> [codeowners] Add reviewers for /api/include/

- _studio/mfx_lib/decode/mpeg2/src/mfx_mpeg2_decode.cpp
If error occured in case of field parity loss
we can recover on I field. So, return MFX_ERR_INCOMPATIBLE_VIDEO_PARAM
to make application reset decoder.
> [mpeg2d] Recovery on I field

- _studio/mfx_lib/decode/mpeg2/src/mfx_mpeg2_decode.cpp
Reverts Intel-Media-SDK/MediaSDK#211 - too early to merge
> Revert "[mpeg2d] Recovery on I field"

- samples/sample_hevc_fei_abr/src/dso/hevc2_ssdata.cpp
> Variable default initialization to avoid gcc warnings

- Android.mk
- _studio/hevce_hw/Android.mk
- _studio/mfx_lib/Android.mk
- _studio/shared/asc/Android.mk
- _studio/shared/mfx_trace/Android.mk
- _studio/shared/umc/codec/Android.mk
- _studio/shared/umc/core/Android.mk
- _studio/shared/umc/io/Android.mk
- android/Android.mk
- android/build/mfx_android_os.mk
- android/build/mfx_stl.mk
- android/mfx_defs.mk
- android/mfx_defs_internal.mk
- contrib/SafeStringStaticLibrary/Android.mk
> Android make files clean-up + refactoring

- _studio/hevce_hw/h265/src/mfx_h265_encode_hw_ddi.cpp
> [KW, HEVCe] Removed unused variables

- _studio/shared/src/mfx_vpp_vaapi.cpp
> [vpp] Replaced a magic number by VA_DEINTERLACING_SCD_ENABLE flag

- samples/sample_fei/src/sample_fei.cpp
fixed resource leak in sample_fei due to wrong order of joined sessions destruction
> [mfe, fei] fix resource leak

- samples/sample_hevc_fei_abr/include/buffer_pool.h
- samples/sample_hevc_fei_abr/src/pipeline_hevc_fei.cpp
Prevent memory leak during buffers allocation in case of thrown exception
> [sample_hevc_fei_abr] Make buffer allocation exception safe

- samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp
- samples/metrics_monitor/src/cttmetrics_utils.cpp
Issue: MDP-42112
Test: test_monitor
> [samples][metrics_monitor] KW fixes

- _studio/mfx_lib/shared/src/mfx_brc_common.cpp
- samples/sample_common/src/brc_routines.cpp
> [SW BRC] Fix for buffer overflow

- _studio/shared/umc/codec/h264_dec/src/umc_h264_mfx_supplier.cpp
During init h264 decoder wiped crop info in provided params structure.
Added code to keep and verify the info.
Now sample_decode prints proper Crops.
(output color format to be corrected in sample)
Issue: MDP-42346
Test: sample_decode with cropped h264 streams
> [h264d] Prevent crop info to be printed in sample_decode

- samples/sample_hevc_fei/src/pipeline_hevc_fei.cpp
Condition and comment is unrelated to real purpose of this buffer
> [sample_hevc_fei] Minor correction of mfxExtHEVCParam usage

- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
App fails on low bitrate streams with error buffer size not enough for encode
> Fixed getting enough buffer size for encode

- _studio/mfx_lib/decode/mpeg2/src/mfx_mpeg2_decode.cpp
In picture verification if invalid picture header is
found, it is ignored and search continues for next PH.
Issue: MDP-42872
Test: mpeg2d_common and few manual
> [mpeg2d] improve headers check

- README.md
> Document direct cmake configure build in README

- samples/sample_common/include/parameters_dumper.h
- samples/sample_common/src/parameters_dumper.cpp
- samples/sample_multi_transcode/src/pipeline_transcode.cpp
Display what changes to what when
Query() returns MFX_WRN_INCOMPATIBLE_PARAMS
> Display enc config changes

- samples/metrics_monitor/test/cttmetrics_gtest.cpp
> Fix gcc-6.3.1 warnings for metrics_monitor

- _studio/hevc_fei/h265_fei/include/mfx_h265_fei_encode_hw.h
- _studio/hevc_fei/h265_fei/include/mfx_h265_fei_encode_vaapi.h
- _studio/hevce_hw/h265/include/mfx_h265_encode_hw.h
- _studio/hevce_hw/h265/include/mfx_h265_encode_plugin_hw.h
Take advantage of c++11 override specifier to make sure that inheritance takes place
> [HEVC FEI] Added override specifier, removed redundant methods

- _studio/mfx_lib/mctf_package/mctf/src/mctf_common.cpp
Fixing 2 hits found during KW scan.
Issue: MDP-42117
Test: manual
> [vpp] asc klockwork fix

- samples/sample_encode/include/pipeline_encode.h
- samples/sample_encode/src/pipeline_encode.cpp
- samples/sample_encode/src/sample_encode.cpp
this PR  depends on PR #221:
https://github.com/Intel-Media-SDK/MediaSDK/pull/221
> add rounding offset support for sample encode

- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
- _studio/mfx_lib/shared/include/mfx_h264_enc_common_hw.h
- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
- _studio/shared/include/libmfx_core_interface.h
- _studio/shared/include/libmfx_core_vaapi.h
- _studio/shared/include/mfxstructures-int.h
- _studio/shared/src/libmfx_core_vaapi.cpp
Added GT config reporting from Core
Added GT2 path for MaxNumFrame default settings
> [h264e, core, mfe] improve GT2 performance.

- _studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp
Reverted part of change in the original commit.
> [h265] Fix GPU hang part #2

- samples/sample_hevc_fei/src/fei_predictors_repaking.cpp
> [HEVCe FEI] Zero all MVP before filling loop

- samples/sample_hevc_fei/src/ref_list_manager.cpp
> [HEVCe FEI] Encode P frames as GPB

- _studio/shared/src/cm_mem_copy.cpp
> Fix missing GPU copy on CFL

- samples/sample_encode/src/pipeline_encode.cpp
Issue: MDP-40580
Test: manual
Change-Id: I68f558d2c12dc38da3f2c100469d4140b27052f8
> [samples][draft] Fix for field splitting Full HD

- android/include/mfx_config.h
> Add Android P support

- _studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp
> [h265d] Fixed potential null dereference

- samples/sample_fei/include/sample_fei_defs.h
> [sample_fei] Fixed gcc-8.1 warnings related to memset in constructors

- samples/sample_hevc_fei/src/ref_list_manager.cpp
> [HEVCe FEI] Use closest reference in L1 ref list for GPB frames

- _studio/hevce_hw/h265/include/mfx_h265_encode_hw_utils.h
- _studio/hevce_hw/h265/src/mfx_h265_encode_hw_par.cpp
- _studio/hevce_hw/h265/src/mfx_h265_encode_hw_utils.cpp
[Issue]: MDP-42904
[Test]: manually
> [HEVC E] NumRefFrame check was corrected for Encoding Order

- _studio/hevce_hw/h265/src/mfx_h265_encode_hw_utils.cpp
Issue: MDP-41090
Test: manually
> [HEVC E]: fix for interlace reordering (last frames)

- samples/sample_hevc_fei_abr/include/abr_brc.h
- samples/sample_hevc_fei_abr/src/hevc_sw_dso.cpp
Fixed static analysis issues
Some code improvements in DSO part
> Hevc fei abr improvements

- samples/sample_hevc_fei_abr/include/abr_brc.h
- samples/sample_hevc_fei_abr/include/task.h
- samples/sample_hevc_fei_abr/src/abr_brc.cpp
Use scoped lock for mutex
Added missed initialization
> Sample_hevc_fei_abr minor improvements

- android/mfx_defs.mk
> Add version detection for Android P

- samples/sample_hevc_fei_abr/src/abr_brc.cpp
> [sample_hevc_fei_abr] Fix for clang compiler

- samples/sample_hevc_fei_abr/include/hevc_fei_encode.h
- samples/sample_hevc_fei_abr/include/pipeline_hevc_fei.h
- samples/sample_hevc_fei_abr/src/pipeline_hevc_fei.cpp
> [sample_hevc_fei_abr] Handle errors from encoders

- _studio/hevce_hw/h265/src/mfx_h265_encode_hw_par.cpp
> [HEVC E] MaxFrameSize must be allowed for SWBRC

- samples/sample_fei/src/pipeline_fei.cpp
This lead to segfault in destructor for some MFE pipelines on ubuntu
> [sample_fei] Fix unitialized variables

- _studio/hevce_hw/h265/include/mfx_h265_encode_hw.h
- _studio/hevce_hw/h265/include/mfx_h265_encode_hw_brc.h
- _studio/hevce_hw/h265/include/mfx_h265_encode_hw_ddi.h
- _studio/hevce_hw/h265/include/mfx_h265_encode_hw_ddi_trace.h
- _studio/hevce_hw/h265/src/mfx_h265_encode_hw_brc.cpp
- _studio/hevce_hw/h265/src/mfx_h265_encode_hw_bs.cpp
- _studio/hevce_hw/h265/src/mfx_h265_encode_hw_ddi.cpp
- _studio/hevce_hw/h265/src/mfx_h265_encode_hw_par.cpp
- _studio/hevce_hw/h265/src/mfx_h265_encode_hw_utils.cpp
- _studio/hevce_hw/h265/src/mfx_h265_encode_vaapi.cpp
-Remove unused variables/funcion for HEVCe HW
> Fix Android Warnings (1.0)

- samples/sample_multi_transcode/src/pipeline_transcode.cpp
Previously we released FileWriter object.
This looks like a misprint.
MDP-46563
> [smt] Fixed behavior on ResetOutput

- _studio/mfx_lib/shared/include/mfx_brc_common.h
- samples/sample_common/include/brc_routines.h
Issue: panic after static scene
Test: manually
> [hevce] Fix for sliding window in SW BRC

- _studio/mfx_lib/decode/mpeg2/src/mfx_mpeg2_decode.cpp
Added picture type check for new frame
and field counter reset on error.
(40947)
> [mpeg2d] improve robustness

- _studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_utils.cpp
> [h265d] Removed out of date HEVC MAIN10 limitation

- _studio/mfx_lib/cmrt_cross_platform/include/cmvm.h
-Remove unused defines
-Remove unused functios
-Replace assert to static_assert if possible
-Replace magic with conformable variables to static_assert
> [CMRT]Move to static_assert

- _studio/mfx_lib/shared/src/mfx_session.cpp
-Add waitong for task complation for all registred components
> [core] fix MFXClose()

- _studio/shared/asc/include/asc.h
- _studio/shared/asc/include/asc_structures.h
- _studio/shared/asc/include/me_asc.h
- _studio/shared/asc/src/asc.cpp
- _studio/shared/asc/src/motion_estimation_engine.cpp
Integration of two new descriptors for ASC module, which
is preliminary work for implementation of fade detection
new feature in ASC. The new descriptors are 1) temporal
correlation and 2) motion compensated temporal correlation
Issue: -
Test: Manual test
> [ASC] New descriptors integration

- _studio/mfx_lib/shared/src/libmfxsw.cpp
- _studio/mfx_lib/shared/src/mfx_session.cpp
> core: treat zero impl as MFX_IMPL_VIA_ANY

- _studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw.cpp
- _studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp
- _studio/shared/include/libmfx_core_vaapi.h
- _studio/shared/include/mfx_utils.h
- _studio/shared/include/mfxvideo++int.h
- _studio/shared/src/libmfx_core_vaapi.cpp
New implementation of the function VAAPIVideoCore::IsGuidSupported uses driver's functions to detect supported codec profile and entrypoint and resolution.
> [CORE] Improve function IsGuidSupported

- samples/sample_hevc_fei_abr/src/fei_utils.cpp
This fixes possible synchronization issues in situations when decoder is too fast and actually consumes all surfaces from pool
> [sample_hevc_fei_abr] Added wait in GetSurface

- _studio/mfx_lib/Android.mk
> Fix Android build (add mfx_umc_mjpeg_vpp.cpp to build)

- android/mfx_defs.mk
- api/Android.mk
- api/opensource/Android.mk
- api/opensource/mfx_dispatch/Android.mk
- samples/Android.mk
- samples/sample_common/Android.mk
- samples/sample_decode/Android.mk
- samples/sample_encode/Android.mk
- samples/sample_multi_transcode/Android.mk
- samples/sample_plugins/Android.mk
- samples/sample_plugins/vpp_plugin/Android.mk
- samples/sample_vpp/Android.mk
sample_decode
sample_encode
sample_vpp
sample_multi_transcode
> [Android] Added Android.mk files for building samples

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
- we can get correct value for RollingIntraRefresh
from driver
> Delete hardcode value for RollingIntraRefresh

- samples/sample_fei/include/pipeline_fei.h
Required for satisfying static analysis
> [sample_fei] make CEncodingPipeline non-copyable

- _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h
> [h264d] Fixed SIGFPE when (width = 0) or (height = 0)

- samples/sample_hevc_fei_abr/src/dso/hevc2_dec.cpp
- tools/bs_parser_hevc/include/bs_mem+.h
- tools/bs_parser_hevc/include/hevc2_struct.h
These two code bases should fully match
> [BS parser HEVC] Aligned code in tools and sample_hevc_fei_abr

- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_utils.cpp
> [VP9e] Fixed segmentation fault issue

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp
- _studio/shared/include/mfx_utils.h
- _studio/shared/src/libmfx_core.cpp
- _studio/shared/src/libmfx_core_vaapi.cpp
Zero Y pointer in Y410 case handling
> Y410 HEVCe fix

- _studio/shared/src/libmfx_core.cpp
> Fixed possible segmentation fault

- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_cm.cpp
> Fixed uninitialized fields for CmContext

- _studio/mfx_lib/shared/src/libmfxsw.cpp
- android/mfx_defs.mk
strings libmfxhw32.so | grep mediasdk
> [Android] Added identify information to Media SDK library

- _studio/mfx_lib/decode/vp8/include/mfx_vp8_dec_decode_hw.h
- _studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw.cpp
> Fixed android warning Wunused-function in vp8_dec

- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_cm.cpp
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils.cpp
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils_new.cpp
This change fix possible problem with nullptr buffer
> [h264e] Replace GetExtBuffer() to GetExtBufferRef() for MfxVideoParam

- _studio/shared/asc/include/asc_common_impl.h
- _studio/shared/asc/include/cpu_detect.h
- _studio/shared/asc/include/iofunctions.h
- _studio/shared/include/mfxvideo++int.h
Warnings: Wunused-function, Wexceptions, Wunneeded-internal-declaration
> Fixed android warnings

- _studio/mfx_lib/decode/h264/src/mfx_h264_dec_decode.cpp
- _studio/shared/src/libmfx_core_vaapi.cpp
> [H264d] Enabled VD+SFC usage on SKL

- _studio/mfx_lib/shared/include/mfx_h264_enc_common_hw.h
> Added comment about using GetExtBufferRef()

- _studio/shared/umc/codec/h264_dec/src/umc_h264_frame_list.cpp
> [h264d_umc] Fixed possible nullptr dereference

- tools/asg-hevc/CMakeLists.txt
- tools/bs_parser_hevc/tools/hevc_fei_extractor/CMakeLists.txt
Commit includes enabling make install option for HEVC FEI validation tools.
> [ASG-HEVC][TOOLS] make install option was added to the asg-hevc and hevc_fei_extractor tools.

- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw.h
- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw_ddi.h
- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_vaapi.h
- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_fei_encode_hw.h
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_ddi.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_fei_encode_hw.cpp
- _studio/mfx_lib/shared/src/libmfxsw_encode.cpp
> Switch HEVC to use internal Core interfaces

- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
- _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
> h264e: enable ICQ rate control

- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_vaapi.h
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp
- _studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h
- _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
- _studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp
- _studio/mfx_lib/shared/src/mfx_mpeg2_encode_vaapi.cpp
That's an extract of #656 (which can't be yet merged without fixing CI).
> Fix va attributes

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
I really hope now all is fine with request)
> LINUX_TARGET_PLATFORM_BXT was removed from mfx_h265_encode_hw_par.cpp

- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_vaapi.h
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
- implemented Rolling-I feature
for HEVC
> [HEVCE] Implemented Rolling-I for HEVCe

- _studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_vaapi.h
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp
> [VP9e] Added support of temporal scalability for Linux

- _studio/mfx_lib/Android.mk
- _studio/mfx_lib/cmrt_cross_platform/src/cmrt_cross_platform.cpp
- android/include/mfx_android_defs.h
-Enable CM kernels for the latest Android
-Defined name of CMRT .so for Android
> [Android]Enable CM operations

- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp
Fixed assert issue with different sizes of frame rate and rate control vectors.
Signed-off-by: Ekaterina Shiryaeva <ekaterina.shiryaeva.alexandrovna@intel.com>
> [VP9e] Fixed assert issue

- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp
Signed-off-by: Ekaterina Shiryaeva <ekaterina.shiryaeva.alexandrovna@intel.com>
> [VP9e] Fixed issue with wrong buffer creation

- _studio/shared/umc/codec/h264_dec/src/umc_h264_au_splitter.cpp
GetSliceRef(pos), GetLayerRef(pos), GetPayloadRef(pos).
These functions don't check input value "pos",
they will be used ONLY when 100% sure
that 0 <= pos < array (vector) size.
> [h264d_umc] Remove part of Get functions inside classes

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw.cpp
Invalid argument after copy-paste
> [HEVCE] fix typo in AcquireResource call

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
This reverts commit 16800aecce0d3ae37f30249ae576093b2aa54727.
> Revert "Added internal sync for HEVCe"

- _studio/mfx_lib/vpp/include/mfx_vpp_hw.h
- _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
Add DdiTask::bCopyPassThroug flag for define that task should be execute in CopyPassThrough mode
> [VPP]Fix CopyPassThrough mode

- _studio/shared/mfx_trace/src/mfx_trace_utils_linux.cpp
Used c++11 approach to parse file, get rid of dependency from SafeStrings lib
> [mfx_trace] Refactored file parsing, removed dependency from SafeStrings lib

- _studio/mfx_lib/encode_hw/mjpeg/src/mfx_mjpeg_encode_hw_utils.cpp
Signed-off-by: tkuzne1x <tatyanax.kuznetsova@intel.com>
> MJPEGe - use C++ primitives (memcpy => std::copy)

- _studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp
> h265d - use C++ primitives (memcpy => std::copy)

- _studio/mfx_lib/encode_hw/mpeg2/include/mfx_mpeg2_encode_utils_hw.h
- _studio/mfx_lib/encode_hw/mpeg2/src/mfx_mpeg2_encode_full_hw.cpp
- _studio/mfx_lib/encode_hw/mpeg2/src/mfx_mpeg2_encode_utils_hw.cpp
> Mpeg2e - use C++ primitives (memcpy => std::copy)

- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_bs.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp
> h265e- use C++ primitives (memcpy => std::copy)

- _studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_ddi.h
- _studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw.cpp
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_ddi.cpp
> VP9e - use C++ primitives (memcpy => std::copy)

- api/mfx_dispatch/linux/mfxloader.h
Courtesy of mfx_dispatch_test unit tests still in development.
> [mfx_dispatch] Fix relation operator for mfxVersion

- _studio/mfx_lib/fei/h264_enc/mfx_h264_enc.cpp
- _studio/mfx_lib/fei/h264_la/mfx_h264_la.cpp
- _studio/mfx_lib/fei/h264_pak/mfx_h264_fei_pak.cpp
- _studio/mfx_lib/fei/h264_preenc/mfx_h264_preenc.cpp
zero initialization, that not causes clang 6.0 warnings
> clang 6.0: zero initialization warnings in fei

- CMakeLists.txt
- builder/FindMFX.cmake
- builder/FindPackages.cmake
> Fix build-time Dispatcher discovery

- tests/mfx_dispatch/linux/CMakeLists.txt
Component: mfx_dispatch_test
Fixes: #839
> Disable FORTIFY_SOURCE for mfx_dispatch_test

- _studio/shared/umc/io/umc_va/src/umc_va_linux.cpp
> Removed redundant VA_RT_FORMAT_YUV420 check

- samples/metrics_monitor/CMakeLists.txt
> Fixed metrics_monitor related stuff installation (through 'make install')

- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
Issue: MDP-50659
Test: manually
> [AVCe] fix for SW BRC

- _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
> Remove unnecessary cast

- _studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils.cpp
> [AVC E]: MinMaxQp support was added for LA BRC

- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
> disable ICQ/VCM/QVBR for MFE due to issues with driver support

- _studio/mfx_lib/encode_hw/mpeg2/src/mfx_mpeg2_encode_full_hw.cpp
- _studio/mfx_lib/scheduler/src/mfx_scheduler_core.cpp
- _studio/mfx_lib/scheduler/src/mfx_scheduler_core_task_management.cpp
> [scheduler] replaced soft polling with events driven scheme

- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
> h264e: Replace GetExtBuffer on GetExtBufferRef

- _studio/shared/umc/codec/h265_dec/src/umc_h265_frame_info.cpp
check slice ptr before acces
Issue: MDP-51108
> [hevcd] hevcd_afl_broken-plugin_hevcdhw segfault

- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
Signed-off-by: Hu Kelvin <kelvin.hu@intel.com>
> [AVCe] Fix for Paff SingleFieldMode

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
Issue: MDP-50776
Test:  manually (behavior is needed)
> [AVCe, HEVCe] Fix for default MaxQPI, MaxQPP, MaxQPB

- _studio/shared/src/libmfx_core_vaapi.cpp
- samples/metrics_monitor/test/i915_pciids.h
Issue: VIZ-15366
Signed-off-by: fuweitax <fuweix.tang@intel.com>
> Add WHL device IDs support.

- _studio/mfx_lib/decode/mpeg2/src/mfx_mpeg2_decode.cpp
> Remove unnecessary define

- tests/mfx_dispatch/linux/mfx_dispatch_test_cases_libs.cpp
- tests/mfx_dispatch/linux/mfx_dispatch_test_cases_plugins.cpp
Corrected parameters in test cases for properly work.
> [dispatcher_test] Strengthen the test requirements

- _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
> Fixed possible nullptr dereference

- _studio/shared/umc/codec/h265_dec/src/umc_h265_bitstream_headers.cpp
> h265d: add NumPicTotalCurr sanity check

- _studio/shared/src/mfx_vpp_vaapi.cpp
#907 reopened from fork
Issue: MDP-51946
> [VPP] check pipeline caps before params setting

- CMakeLists.txt
- api/mfx_dispatch/linux/CMakeLists.txt
> Increase cmake_minimum_required up to 3.6

- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils.cpp
- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
> h264e: Fixed possible dereference task.m_ctrl.Payload

- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
> [HEVCe] Encoded frame info support was added in hevc encoder

- samples/sample_multi_transcode/include/pipeline_transcode.h
- samples/sample_multi_transcode/src/sample_multi_transcode.cpp
- correct printf option
- fix possible memory leak
> smt: fixed static analysis issues

- android/mfx_defs.mk
> Fix Android O build

- api/mfx_dispatch/linux/Android.mk
> Fix mfx_dispatch build on Android

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_par.cpp
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_utils.cpp
- _studio/shared/src/libmfx_core_vaapi.cpp
- _studio/shared/umc/codec/h264_dec/include/umc_h264_slice_decoding.h
- _studio/shared/umc/codec/h265_dec/include/umc_h265_slice_decoding.h
- _studio/shared/umc/codec/h265_dec/src/umc_h265_slice_decoding.cpp
> Code clean up

- api/mfx_dispatch/linux/mfxloader.cpp
> Change MFX libraries names for Android mfx_dispatch

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_par.cpp
- _studio/mfx_lib/shared/include/mfx_h264_enc_common_hw.h
- _studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h
- _studio/mfx_lib/shared/src/libmfxsw_plugin.cpp
- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
- _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
- _studio/mfx_lib/shared/src/mfx_vpx_dec_common.cpp
- _studio/shared/include/mfx_config.h
- _studio/shared/include/mfx_utils.h
- _studio/shared/src/libmfx_allocator_vaapi.cpp
- _studio/shared/src/libmfx_core.cpp
- _studio/shared/src/libmfx_core_vaapi.cpp
- _studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_utils.cpp
- _studio/shared/umc/codec/h265_dec/src/umc_h265_va_packer.cpp
- _studio/shared/umc/io/umc_va/src/umc_va_linux.cpp
- samples/sample_encode/include/pipeline_encode.h
- samples/sample_encode/src/pipeline_encode.cpp
- samples/sample_encode/src/sample_encode.cpp
> Wrap API<1.27 specific code by appropriate defines

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp
This is alignment with closed source code
> h265e: Simplified code. Using less SFINAE

- _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
> Fix Android build for AVBR

- _studio/mfx_lib/decode/mpeg2/src/mfx_mpeg2_decode.cpp
- _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_dec_pic.cpp
Added check for picture_structure in progressive sequence
and for nonzero slice count.
> [mpeg2d] improve robustness in DecodePicHeader

- samples/sample_encode/src/pipeline_encode.cpp
- samples/sample_encode/src/sample_encode.cpp
./sample_encode h264 -i xxx.yuv -o xxx.h264 ...... -icq ICQQualityFactor -la
or
./sample_encode h264 -i xxx.yuv -o xxx.h264 ...... -icq ICQQualityFactor -la -lad LookAheadDepth
or
./sample_encode h264 -i xxx.yuv -o xxx.h264 ...... -icq ICQQualityFactor -lad LookAheadDepth
ICQQualityFactor should be in [0, 51]
LookAheadDepth should be in [10, 100]
Change-Id: I84cc422460dbfc9dc1b0023265aec0e37e17da01
> LA_ICQ: enable support in sample_encode

- _studio/mfx_lib/scheduler/src/mfx_scheduler_core.cpp
> [scheduler] Wake up threads strictly according to task types

- _studio/mfx_lib/scheduler/src/mfx_scheduler_core.cpp
> Reverted "scheduler] Wake up threads strictly according to task types"

- samples/sample_fei/src/fei_encode.cpp
- samples/sample_fei/src/fei_encpak.cpp
- samples/sample_fei/src/fei_preenc.cpp
- samples/sample_fei/src/sample_fei.cpp
Signed-off-by: Kelvin Hu <kelvin.hu@intel.com>
> [AVCe] Fix Sample_fei for Paff SingleFieldMode

- api/mfx_dispatch/linux/mfxloader.h
- api/mfx_dispatch/linux/mfxparser.cpp
Use std::strings in most dangerous operations
> dispatcher: fix static analysis issues in parser

- _studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
> H264 encode: fix static analysis issue

- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp
Corrected setting framerates for VP9 encoder according to the libva
> [VP9e] Correct setting framerates

- _studio/mfx_lib/cmrt_cross_platform/src/cmrt_cross_platform.cpp
Fixes: #971 
Should be merged along with https://github.com/intel/media-driver/pull/413
> Update cmrt library name

- _studio/mfx_lib/encode_hw/mpeg2/src/mfx_mpeg2_encode_utils_hw.cpp
> MPEG2e should return unsupported on BXT

- _studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw.h
- _studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_ddi.h
- _studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_par.h
- _studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_vaapi.h
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw.cpp
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_ddi.cpp
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_par.cpp
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_utils.cpp
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp
- _studio/mfx_lib/shared/src/libmfxsw_encode.cpp
[1] The change was checked on Windows for no regressions.
[2] For Linux only compiling and building possibility was checked.
> [VP9e] Plugin interface replaced by the core interface

- _studio/mfx_lib/vpp/include/mfx_vpp_hw.h
- _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
Choosing of background color moved into separate function.
> [VPP] code cleanup for further background color functions

- _studio/mfx_lib/Android.mk
> Android build fix

- samples/sample_common/src/vaapi_utils_drm.cpp
Current mechanism to detect Intel drm drivers uses the following schema:
1) Walk through the list of PCI devices, get device properties
(Vendor ID) and calculate number of PCI devices  that corresponds
to ‘DISPLAY_CONTROLLER_CLASS’ (adapters_num)
2) Use adapters_num to get path to /dev/dri/cardN and /dev/dri/renderDN
with checking for Vendor ID.
But this approach is not working in some cases. For example, if PCI device
is present but corresponding driver is not set up. So it can be attempt to
open wrong /dev/dri/renderN and /dev/dri/cardN  paths.
New approach is based on checking for /dev/dri/renderD<N> (N=0..15) with
drm request for driver name.
> [samples] fix drm drivers detection

- samples/sample_multi_transcode/src/sample_multi_transcode.cpp
> [smt] cpu usage grow fix

- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
Disable MFE in case of VDEnc request
Fixes #1010
> Silently Disable MFE for VDEnc

- _studio/mfx_lib/decode/vp9/include/mfx_vp9_dec_decode_hw.h
- _studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp
- _studio/mfx_lib/shared/src/mfx_vpx_dec_common.cpp
This reverts commit 4d413905bf5c50ed339ffa315de242d439eb52ae.
Commit caused "GPU hang" MDP-52517
> Revert "[vp9d] Lock reference frames before UpdateRefList"

- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils.cpp
- Added missing if statement
- Little code readability improvement
> Fix for AVC brc

- _studio/mfx_lib/vpp/include/mfx_vpp_utils.h
- _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
- samples/sample_vpp/include/sample_vpp_config.h
- samples/sample_vpp/include/sample_vpp_utils.h
- samples/sample_vpp/src/sample_vpp.cpp
- samples/sample_vpp/src/sample_vpp_config.cpp
- samples/sample_vpp/src/sample_vpp_parser.cpp
#605 was splitted into #891 and this one
> [VPP] colorfill disable option

- contrib/ipp/src/pccjoin422pxca.c
> IPP build fix

- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_vaapi.h
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
enable control for max slice size
> hevce: enable control for max slice size

- _studio/shared/src/libmfx_core_vaapi.cpp
> Actualize CFL device IDs

- _studio/mfx_lib/genx/h264_encode/src/genx_simple_me.cpp
Fixes #1104 
BDW kernels currently can't be built - requires fixes in compiler
> Clean up obsololete code from LA kernels(failing kernels build)

- _studio/mfx_lib/vpp/src/mfx_vpp_sw_core.cpp
- _studio/mfx_lib/vpp/src/mfx_vpp_utils.cpp
- _studio/shared/src/mfx_vpp_vaapi.cpp
- samples/sample_decode/src/sample_decode.cpp
> [VPP] reopen Format for YUV2 and UYVY was enabled.

- _studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw.cpp
On Android O we use old version of driver and should use
special code for 1st partition size computation (for count == 8)
> vp8d: Fixed playback

- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
> [AVCe] Fix for slice header packing

- samples/sample_common/src/vaapi_allocator.cpp
As it was done previously in lib version of vaapi allocator.
> [samples] vaapi allocator surfaces attribs fixed

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
This commit is prerequisite for enabling weighted prediction,
but support for all platforms is still disabled, because
driver doesn't have capability reporting for this functionality.
> hevce: add setting weights/offsets for driver

- samples/sample_common/src/vaapi_allocator.cpp
- samples/sample_encode/src/pipeline_encode.cpp
- samples/sample_multi_transcode/src/sample_multi_transcode.cpp
> Moving m_export_mode flag definition on application level.

- _studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp
- _studio/shared/umc/codec/h264_dec/src/umc_h264_mfx_supplier.cpp
> Static analysis issues fixes

- _studio/mfx_lib/encode/mjpeg/src/mfx_mjpeg_encode.cpp
- _studio/mfx_lib/encode_hw/mjpeg/src/mfx_mjpeg_encode_hw.cpp
> mjpege: change frame type to MFX_FRAMETYPE_I from MFX_FRAMETYPE_UNKNOWN

- _studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
- samples/sample_common/src/vaapi_allocator.cpp
- samples/sample_encode/src/pipeline_encode.cpp
- samples/sample_multi_transcode/src/sample_multi_transcode.cpp
These fixes ought to be part q4 release (or update).
> Release scope

- _studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp
> [VP9D] VideoDECODEVP9_HW::Reset Y410 on ICL error

- _studio/shared/include/libmfx_core.h
- _studio/shared/include/libmfx_core_vaapi.h
- _studio/shared/src/libmfx_core.cpp
- _studio/shared/src/libmfx_core_vaapi.cpp
- samples/sample_multi_transcode/include/transcode_utils.h
- samples/sample_multi_transcode/src/transcode_utils.cpp
Replace self-written unique_ptr with implementation from std
> Remove s_ptr

- _studio/shared/umc/codec/jpeg_dec/src/jpegdec.cpp
> Valgrind issue fix: Mismatched free() / delete / delete [] in jpeg decode

- _studio/mfx_lib/decode/vp8/include/mfx_vp8_dec_decode_vp8_defs.h
- _studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw.cpp
- _studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils.cpp
- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_brc.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_bs.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_ddi.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp
- _studio/mfx_lib/mctf_package/mctf/include/mctf_common.h
- _studio/mfx_lib/shared/src/mfx_brc_common.cpp
- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
- _studio/mfx_lib/vpp/include/mfx_vpp_defs.h
- _studio/mfx_lib/vpp/src/mfx_denoise_vpp.cpp
- _studio/mfx_lib/vpp/src/mfx_detail_enhancement_vpp.cpp
- _studio/mfx_lib/vpp/src/mfx_procamp_vpp.cpp
- _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
- _studio/shared/include/mfx_utils.h
- _studio/shared/umc/codec/brc/include/umc_brc.h
- _studio/shared/umc/codec/brc/include/umc_h264_brc.h
- _studio/shared/umc/codec/brc/src/umc_h264_brc.cpp
- _studio/shared/umc/codec/brc/src/umc_mpeg2_brc.cpp
- _studio/shared/umc/codec/h265_dec/include/umc_h265_dec_defs.h
- _studio/shared/umc/codec/h265_dec/src/umc_h265_bitstream_headers.cpp
- _studio/shared/umc/codec/vc1_common/include/umc_vc1_common_macros_defs.h
- samples/sample_common/include/sample_defs.h
- samples/sample_common/src/brc_routines.cpp
- Introduce mfx::clamp
- Clean up code from multiple self-written clamps
Fixes #926
> Clamp utility function

- _studio/mfx_lib/decode/vp9/include/mfx_vp9_dec_decode_hw.h
- _studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp
- _studio/shared/umc/codec/vp9_dec/include/umc_vp9_frame.h
- _studio/shared/umc/codec/vp9_dec/include/umc_vp9_utils.h
-Return locked surfcae and sync point if input bs = 0:
actuall in case of latest frame is not  "show frame"
> vp9d: add flushing

- _studio/shared/umc/codec/h264_dec/src/umc_h264_va_packer.cpp
Moved to structure-wise copy instead of byte-wise
> AVC FEI DSO: fixed high CPU usage of std::copy

- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
Fixes #863
(cherry picked from commit 745cdce31796d01c5d04c8262b0eb190ec22fdf3)
> disable ICQ/VCM/QVBR for MFE due to ssues with driver support

- _studio/shared/include/mfx_utils.h
> Clean up utility macro

- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
-Fix wrong condition for supported rate controls
> h264e: fix check MaxFrameSize

- _studio/shared/umc/codec/mpeg2_dec/include/umc_mpeg2_decoder.h
- _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_decoder.cpp
> [mpeg2d] Small refactoring

- _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
This make the gst pipeline below works:
gst-launch-1.0 videotestsrc ! msdkvpp ! video/x-raw,format=UYVY ! \
filesink location=out.yuv
> mfx_vpp_hw: support UYVY with background color

- _studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp
-In case of DRC: currFrameInBS may be increased or set 0 by
DecodeFrameHeader().
If required reallocation surface decoder should restore previous
state of frameInfo.
So added local copy, sate of frameInfo should be change only if
not need reallocation.
> vp9d: fix update frameInfo

- samples/sample_fei/src/fei_encode.cpp
Fixed the null-pointer check for sample_fei
> [samples][AVC FEI] Fix the logic of null-pointer check.

- _studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp
checkInfoCodecs function was moved into decoder and error codes were corrected
MDP-50900
> [VP9D] params checking function was made codec-specific

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw.cpp
If incoming frame in EncodedOrder mode has frame order corresponding to some of the previously encoded GOPs, return error
> h265e: added check for frames from past

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
> [hevce] Tile column width/height fix

- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
-LowDelayBRC not need setting MaxFrameSize:
if MaxFrameSize not specified
Query() should returns ERR_NONE
Init() should set MaxFrameSize = AVG frame size
> h264e: fix check LowDelayBRC

- _studio/shared/src/mfx_umc_mjpeg_vpp.cpp
> jpeg: width and height were mixed up during vpp rotation

- CMakeLists.txt
- _studio/shared/src/mfx_static_assert_structs.cpp
- builder/ConfTargets.cmake
- contrib/ipp/CMakeLists.txt
- samples/sample_common/src/vaapi_utils.cpp
This just made build possible with -DMFX_ENABLE_SW_FALLBACK=OFF
Functionality not tested.
Partially addresses #1195
> Restore 32-bit build

- _studio/mfx_lib/decode/vc1/src/mfx_vc1_decode.cpp
- _studio/shared/umc/codec/vc1_common/include/umc_vc1_common_defs.h
- _studio/shared/umc/codec/vc1_dec/include/umc_vc1_dec_frame_descr_va.h
- _studio/shared/umc/codec/vc1_dec/include/umc_vc1_video_decoder.h
- _studio/shared/umc/codec/vc1_dec/include/umc_vc1_video_decoder_hw.h
- _studio/shared/umc/codec/vc1_dec/src/umc_vc1_dec_frame_descr.cpp
- _studio/shared/umc/codec/vc1_dec/src/umc_vc1_dec_frame_va.cpp
- _studio/shared/umc/codec/vc1_dec/src/umc_vc1_dec_pic_com.cpp
- _studio/shared/umc/codec/vc1_dec/src/umc_vc1_dec_pic_com_adv.cpp
- _studio/shared/umc/codec/vc1_dec/src/umc_vc1_video_decoder.cpp
- _studio/shared/umc/codec/vc1_dec/src/umc_vc1_video_decoder_hw.cpp
> vc1d: fix frame type reporting

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
> hevce: implement mbbrc for HEVCe

- _studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp
vaSyncSurface guarantees that task is completed upon its return.
We don't need to recheck surface status.
Fixes #603
> AVC FEI: remove redundant sync for PreENC, ENC, PAK

- _studio/shared/umc/codec/h264_dec/include/umc_h264_bitstream_headers.h
- _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h
- _studio/shared/umc/codec/h264_dec/src/umc_h264_dec_bitstream_headers.cpp
> [H264][Dec] Fix for h264 decode

- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp
- _studio/shared/include/mfx_vpp_vaapi.h
- _studio/shared/src/libmfx_allocator_vaapi.cpp
- _studio/shared/src/mfx_vpp_vaapi.cpp
- _studio/shared/umc/io/umc_va/src/umc_va_fei.cpp
- _studio/shared/umc/io/umc_va/src/umc_va_linux.cpp
This PR adds missed status check for VA functions
> Add va status check

- _studio/mfx_lib/fei/h264_la/mfx_h264_la.cpp
Issue found by static analysis scan
> LA: Fix possible null pointer dereferencing

- _studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp
1) Image size checks are done via CAPs.
2) Enable HW/image combinations that are working.
Issue: MDP-52482
> [jpegd] fix HW jped decoding support

- _studio/mfx_lib/decode/vc1/src/mfx_vc1_decode.cpp
-In case of reordering m_InternMediaDataOut.GetFrameType() may be not
actual.
So set correct value immediately after decode frame header
Fixes #1239
> vc1d: fix reporting frame type for buffered frames

- samples/sample_multi_transcode/include/pipeline_transcode.h
- samples/sample_multi_transcode/src/pipeline_transcode.cpp
- samples/sample_multi_transcode/src/transcode_utils.cpp
> [sample_multi_transcode] Enable tiles for VP9 encoder

- samples/sample_vpp/src/sample_vpp_parser.cpp
According to the doc for sample_vpp, ayuv is supported
Signed-off-by: Haihao Xiang <haihao.xiang@intel.com>
> sample_vpp: recognize ayuv

- _studio/shared/src/libmfx_core_vaapi.cpp
This function work correctly since libva 1.2
> vaapi core: Corrected IsGuidSupported function

- _studio/shared/src/libmfx_allocator_vaapi.cpp
In case of error temporary allocated memory need to be deleted
> vaapi allocator: fix possible memory leak

- README.md
- api/include/mfxcommon.h
- api/include/mfxdefs.h
- api/mfx_dispatch/windows/include/mfx_critical_section.h
- api/mfx_dispatch/windows/include/mfx_dispatcher.h
- api/mfx_dispatch/windows/include/mfx_dispatcher_defs.h
- api/mfx_dispatch/windows/include/mfx_dispatcher_log.h
- api/mfx_dispatch/windows/include/mfx_dxva2_device.h
- api/mfx_dispatch/windows/include/mfx_exposed_functions_list.h
- api/mfx_dispatch/windows/include/mfx_library_iterator.h
- api/mfx_dispatch/windows/include/mfx_load_dll.h
- api/mfx_dispatch/windows/include/mfx_load_plugin.h
- api/mfx_dispatch/windows/include/mfx_plugin_hive.h
- api/mfx_dispatch/windows/include/mfx_vector.h
- api/mfx_dispatch/windows/include/mfx_win_reg_key.h
- api/mfx_dispatch/windows/include/mfxaudio_exposed_functions_list.h
- api/mfx_dispatch/windows/libmfx_vs2015.sln
- api/mfx_dispatch/windows/libmfx_vs2015.vcxproj
- api/mfx_dispatch/windows/libmfx_vs2015.vcxproj.user
- api/mfx_dispatch/windows/src/main.cpp
- api/mfx_dispatch/windows/src/mfx_critical_section.cpp
- api/mfx_dispatch/windows/src/mfx_dispatcher.cpp
- api/mfx_dispatch/windows/src/mfx_dispatcher_log.cpp
- api/mfx_dispatch/windows/src/mfx_dxva2_device.cpp
- api/mfx_dispatch/windows/src/mfx_function_table.cpp
- api/mfx_dispatch/windows/src/mfx_library_iterator.cpp
- api/mfx_dispatch/windows/src/mfx_load_dll.cpp
- api/mfx_dispatch/windows/src/mfx_load_plugin.cpp
- api/mfx_dispatch/windows/src/mfx_plugin_hive.cpp
- api/mfx_dispatch/windows/src/mfx_win_reg_key.cpp
Uploading OpenSource version of MediaSDK Dispatcher for Windows.
> MediaSDK Dispatcher for Windows

- samples/sample_common/src/sample_utils.cpp
- samples/sample_common/src/vaapi_allocator.cpp
This commit also includes support of the different shifts for Y216 format.
> [Samples] Small refactoring for sample common

- _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
- _studio/shared/src/cm_mem_copy.cpp
> [VPP, CM] Corrected RGBP format processing

- _studio/mfx_lib/vpp/include/mfx_vpp_hw.h
- samples/sample_camera/include/pipeline_camera.h
- samples/sample_camera/src/pipeline_camera.cpp
- samples/sample_hevc_fei/include/fei_utils.h
- samples/sample_hevc_fei/include/hevc_fei_encode.h
- samples/sample_hevc_fei/include/hevc_fei_preenc.h
- samples/sample_hevc_fei/include/pipeline_hevc_fei.h
- samples/sample_hevc_fei/src/pipeline_hevc_fei.cpp
- samples/sample_plugins/rotate_opencl/include/opencl_filter_dx9.h
> Replace auto_ptr with unique_ptr

- _studio/shared/src/libmfx_core_vaapi.cpp
Aligned with https://github.com/intel/media-driver/commit/6a62c979e907905ac6d44ec6ec435ecfc81856cd
> Add CML device IDs

- _studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils.cpp
- _studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h
- _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
Parameters for BRC: repack, hrd params
Affects external BRC, La
Repacking feature is available for VA only
> [H264E]  API 1.29 functionality was added

- _studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils.cpp
- _studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h
- _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
Parameters for BRC: repack, hrd params
Affects external BRC, La
Repacking feature is available for VA only
(cherry picked from commit 757892660df252b50f8d2f283e2d4f3fcffcf57b)
> sw brc (1.29)

- _studio/mfx_lib/shared/src/libmfxsw_encode.cpp
change MFX_WRN_PARTIAL_ACCELERATION to MFX_ERR_UNSUPPORTED in Encode Init function if no SW fallback exist
> encode: convert status if no SW fallback

- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
- _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
- samples/sample_decode/src/pipeline_decode.cpp
> Fix build on Android O (MSDK API 1.26/VAAPI 1.2.0)

- _studio/mfx_lib/shared/include/mfx_h264_enc_common_hw.h
- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
> Fix dynamic num slice issue

- _studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
Deleted unnecessary function call
> [H264][BRC] Hot fix

- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
(cherry picked from commit 972b9d65dbb1324ea574f5c1277d55d547f1558c)
> [H264E] fix for last frame

- _studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp
> [jpegd] Fix rotation of unaligned jpegs during decode

- _studio/mfx_lib/shared/include/mfx_h264_encode_struct_vaapi.h
- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
- _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
> [h264e] Report/check VBR and CBR support via caps

- samples/sample_multi_transcode/src/pipeline_transcode.cpp
This is significant when bitness is changed by vpp.
Issue: MDP-54801
Fixes: #1353
> [samples] Correct vpp output bit depth according to FourCC

- api/include/mfxdefs.h
> Bump API version to 1.30

- _studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils.cpp
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils_new.cpp
- _studio/mfx_lib/fei/h264_enc/mfx_h264_enc.h
- _studio/mfx_lib/fei/h264_la/mfx_h264_la.cpp
- _studio/mfx_lib/fei/h264_pak/mfx_h264_fei_pak.cpp
- _studio/mfx_lib/fei/h264_pak/mfx_h264_fei_pak.h
- _studio/mfx_lib/fei/h264_preenc/mfx_h264_preenc.cpp
- _studio/mfx_lib/fei/h264_preenc/mfx_h264_preenc.h
- _studio/mfx_lib/shared/include/mfx_h264_enc_common_hw.h
- _studio/mfx_lib/shared/include/mfx_h264_encode_interface.h
- _studio/mfx_lib/shared/include/mfx_h264_encode_struct_vaapi.h
- _studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h
- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
- _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
- _studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp
We can not modify ENCODE_CAPS struct, but need to add new BRC
checks in caps. This commit contains new struct (with encode_caps
inside) and code refactor to work with it
Issue: MDP-54861
> [h264e] Report/check VBR/CQP/CBR via caps

- samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp
This commit is a preparation for a later bug fix change
which will address PMU metrics reporting issue.
The issue is once i915 starts using HW semaphores for inter engine synchronization,
the metrics monitor needs to care not only about I915_SAMPLE_BUSY
but also take into account I915_SAMPLE_WAIT/I915_SAMPLE_SEMA.
The current commmit will simplify it by keeping BUSY/WAIT/SAME metrics
for one engine in the same structure.
> Metrics monitor refactoring

- samples/sample_decode/src/pipeline_decode.cpp
> [sample_decode]P010 shift value is corrected

- _studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp
> [VP9D] Refactoring of errors handling

- _studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp
> [HEVCD] Refactoring of errors handling

- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
correct IntraInsertionLocation and IntraInsertionSize by hardcoded IntraRefreshBlockUnitSize
> hevce: correct IntraInsertionLocation and IntraInsertionSize

- _studio/shared/include/libmfx_allocator_vaapi.h
- _studio/shared/src/libmfx_allocator_vaapi.cpp
Removed heap allocation
Simplified code
Increased consistency of operations with internal state
> Refactoring of internal VAAPI allocator

- samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp
> [metrics_monitor] Fixed uninitialized variable

- _studio/shared/umc/codec/color_space_converter/src/umc_color_space_conversion.cpp
> [jpeg] Use IppStatus instead of int, because IppStatus is only used

- _studio/mfx_lib/decode/mjpeg/include/mfx_mjpeg_dec_decode.h
- _studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp
- _studio/mfx_lib/vpp/include/mfx_vpp_jpeg_d3d9.h
- _studio/shared/include/mfx_umc_alloc_wrapper.h
- _studio/shared/src/mfx_umc_mjpeg_vpp.cpp
> [jpegd] fix rotation when output in system memory

- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
Issue: MDP-53548
Change-Id: I9fcc877b9e31b9e51c94d59de76ffc645616032d
I333a72d61b212df04fc27f9038114a048233c255
> [hevce] Fix RoI/DirtyRect behavior

- api/include/mfxastructures.h
- api/include/mfxbrc.h
- api/include/mfxcamera.h
- api/include/mfxcommon.h
- api/include/mfxdefs.h
- api/include/mfxenc.h
- api/include/mfxfei.h
- api/include/mfxfeihevc.h
- api/include/mfxjpeg.h
- api/include/mfxla.h
- api/include/mfxmvc.h
- api/include/mfxpak.h
- api/include/mfxpcp.h
- api/include/mfxplugin.h
- api/include/mfxsc.h
- api/include/mfxscd.h
- api/include/mfxstructures.h
- api/include/mfxvideo.h
- api/include/mfxvp8.h
- api/include/mfxvp9.h
Fixed structures binary layout with compiler's pack pragma
> API: Fix binary api layout

- _studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_ddi.h
- _studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_par.h
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw.cpp
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_ddi.cpp
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_par.cpp
- fixed sending of VP9MfxVideoParam by value to GetGuid function
- corrected SetDefaultsForProfileAndFrameInfo function
> vp9e: fix static analysis issues in GetGuid function

- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_vaapi.h
- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_fei_encode_vaapi.h
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_fei_encode_vaapi.cpp
> [HEVC FEI] Fixed broken HEVC FEI

- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw_bs.h
- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_bs.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp
- _studio/shared/include/mfx_config.h
mfxExtMasteringDisplayColourVolume and mfxExtContentLightLevelInfo
> [HEVCe] Added HDR SEI

- doc/samples/readme-decode_linux.md
- doc/samples/readme-decode_linux.pdf
- doc/samples/readme-encode_linux.md
- doc/samples/readme-encode_linux.pdf
- doc/samples/readme-multi-transcode_linux.md
- doc/samples/readme-multi-transcode_linux.pdf
- doc/samples/readme-vpp_linux.md
- doc/samples/readme-vpp_linux.pdf
Deleted samples readme pdfs. Converted xml dita for each sample to markdown. Updated samples command line options with up to date -? output from samples.
> [samples][docs] Converted xml dita for samples docs to markdown

- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
- _studio/shared/include/mfx_ext_buffers.h
Change-Id: I984d8b83d7890dd1721c36e91dc19d141475def1
> [AVCe] Added interface to disable 8x8TransformMode

- samples/sample_multi_transcode/src/sample_multi_transcode.cpp
> [smt] Enable per session FPS report

- samples/sample_decode/src/pipeline_decode.cpp
> sample_decode build fix

- samples/sample_common/include/sample_utils.h
- samples/sample_common/src/sample_utils.cpp
- samples/sample_encode/include/pipeline_encode.h
- samples/sample_encode/src/pipeline_encode.cpp
- samples/sample_encode/src/pipeline_region_encode.cpp
- samples/sample_encode/src/pipeline_user.cpp
> [sample_encode] Replaced mfxBitstream with mfxBitstreamWrapper

- samples/sample_multi_transcode/include/pipeline_transcode.h
- samples/sample_multi_transcode/src/pipeline_transcode.cpp
> [sample_multi_tramscode] Replaced mfxBitstream with mfxBitstreamWrapper

- samples/sample_fei/include/auxiliary_interfaces.h
- samples/sample_fei/include/fei_encode.h
- samples/sample_fei/include/fei_encpak.h
- samples/sample_fei/src/auxiliary_interfaces.cpp
- samples/sample_fei/src/fei_encode.cpp
- samples/sample_fei/src/fei_encpak.cpp
> [sample_fei] Replaced mfxBitstream with mfxBitstreamWrapper

- samples/sample_hevc_fei/include/fei_utils.h
- samples/sample_hevc_fei/include/hevc_fei_encode.h
- samples/sample_hevc_fei/src/fei_utils.cpp
- samples/sample_hevc_fei/src/hevc_fei_encode.cpp
- samples/sample_hevc_fei_abr/include/fei_utils.h
- samples/sample_hevc_fei_abr/include/hevc_fei_encode.h
- samples/sample_hevc_fei_abr/src/fei_utils.cpp
- samples/sample_hevc_fei_abr/src/hevc_fei_encode.cpp
> [sample_hevc_fei/abr] Replaced mfxBitstream with mfxBitstreamWrapper

- samples/sample_common/include/sample_utils.h
- samples/sample_common/src/sample_utils.cpp
> [sample_common] Replaced mfxBitstream with mfxBitstreamWrapper

- _studio/shared/include/mfx_utils.h
- _studio/shared/include/mfxaudio++int.h
Use explicit per-field comparison instead of whole struct memcmp
> utils: modify comparison operator

- doc/mediasdk-man.pdf
> Typo fix in mediasdk-man.pdf

- _studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_utils.h
Removed memcmp for comparison for mfxVP9SegmentParam struct
> vp9e: added operator == for mfxVP9SegmentParam

- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils_new.cpp
- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_ddi.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
implemented the conversion ROI_Priority => ROI_Delta QP without
external changes in library behavior.
Change-Id: If4c658142769329f00a19e3554a94bfeb956062d
I9a46dd302e2d3a40a61a51d4150de6fd9112ab8a
I3dcaf9ae439676bb165429d2450ab67d40637708
> [h264][h265]implemented ROI_Priority => ROI_DeltaQP conversion

- samples/sample_decode/src/pipeline_decode.cpp
> sample_decode: add checking if a device is a null-pointer

- samples/sample_common/src/d3d_device.cpp
1. m_D3DPP.Windowed is always equal to 1.
Checking this value is not making sense.
Now checking m_D3DPP.hDeviceWindow instead, because it may be
null or not null depending on state of render (enabled or disabled).
2. Added check of hr after GetClientRect() call.
3. Making ResetEx() call is valid only if render is enabled.
Moved this part of code inside m_D3DPP.hDeviceWindow check.
Issue: MDP-56738
> sample_decode: fix incorrect behavior of device Reset

- _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
> vpp: Set unsupported sts when offset between Y/UV not aligned to pitch

- samples/sample_multi_transcode/src/pipeline_transcode.cpp
The removed code block seems to be unnecessary
and may cause stalls in case of MFE
> [smt] Removed unnecessary stall

- samples/sample_common/include/sample_utils.h
- samples/sample_common/src/sample_utils.cpp
- samples/sample_decode/include/pipeline_decode.h
- samples/sample_decode/src/pipeline_decode.cpp
> Moved sample_decode to ExtBufHolder usage

- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
Actually this commit is the same as pull/886
but it was accidentally removed by pull/1377
> Fix for Paff SingleFieldMode

- _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_decoder.cpp
> [mpeg2d] Frame doubling/tripling cases handling

- _studio/mfx_lib/decode/mpeg2/src/mfx_mpeg2_decode.cpp
> [mpeg2d] Payload type has to contain full start code

- _studio/shared/umc/codec/vp9_dec/src/umc_vp9_utils.cpp
Refer to libvpx code
https://github.com/webmproject/libvpx/blob/e46820c693d0dc01685841cfc704c16dbac48e80/vp9/common/vp9_quant_common.c#L196-L206
> vp9dec: fix vp9 qindex

- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_cm.cpp
- _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
- _studio/shared/include/mfxstructures-int.h
- _studio/shared/src/cm_mem_copy.cpp
- _studio/shared/src/libmfx_core.cpp
- _studio/shared/src/libmfx_core_vaapi.cpp
- _studio/shared/umc/codec/h264_dec/src/umc_h264_mfx_supplier.cpp
- api/include/mfxcommon.h
> [core] Add device id for EHL

- _studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils.cpp
- _studio/mfx_lib/shared/include/mfx_h264_enc_common_hw.h
- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
Added necessary checks if caps.SliceLevelRateCtrl is 0
> Fix for MaxSliceSize

- _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h
Sometimes the DPB size returned from CalculateDPBSize is less than max_num_ref_frames, which will result in corrupted output. In this fix, we use 696320 to calculate DPB size again when level_idc reaches the supported maximium level however dpbSize is still less than num_ref_frames
> h264dec: update the calculation for DPB size

- _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_decoder.cpp
> [mpeg2d] fix for 'invalid temporal_reference count' commit

- README.md
> docs: add few more docs and name manual a manual

- samples/sample_common/include/sample_utils.h
> Enabled paired extBuffers support in ExtBufHolder

- samples/sample_common/include/sample_utils.h
- samples/sample_encode/include/pipeline_encode.h
- samples/sample_encode/src/pipeline_encode.cpp
- samples/sample_encode/src/pipeline_region_encode.cpp
- samples/sample_encode/src/pipeline_user.cpp
> [sample_encode] Replaced mfxEncodeCtrl with mfxEncodeCtrlWrap

- samples/sample_common/include/sample_utils.h
Let's allow copy of OPAQUE_SURFACE_ALLOCATION.
> [samples] Fixed regression caused by recent smt refactoring

- samples/sample_common/include/sample_utils.h
- samples/sample_multi_transcode/include/pipeline_transcode.h
- samples/sample_multi_transcode/src/pipeline_transcode.cpp
> [smt] Replaced mfxFrameSurface1 with smart wrappers in SMT

- samples/sample_common/include/brc_routines.h
- samples/sample_common/src/brc_routines.cpp
- samples/sample_encode/sample_encode.vcxproj
- samples/sample_multi_transcode/sample_multi_transcode.vcxproj
> sample_common, brc: Removed IPP_MIN/MAX macro

- NOTICE
Signed-off-by: Li, Yingjie <yingjie.li@intel.com>
> add NOTICE and MODULE_LICENSE_MIT for license check

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
MaxFrameSize is supported for VBR and SWBRC
> Fix MaxFrameSize Query

- samples/sample_vpp/include/sample_vpp_utils.h
- samples/sample_vpp/src/sample_vpp_utils.cpp
Missed part of code which must removed in #1649.
> [sample_vpp] Fully remove unused code

- _studio/shared/umc/codec/mpeg2_dec/include/umc_mpeg2_decoder.h
- _studio/shared/umc/codec/mpeg2_dec/include/umc_mpeg2_defs.h
- _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_bitstream.cpp
- _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_decoder.cpp
1) Handling case when vertical_position of slice is out of range
2) Recalculating numberMBsInSlice of prev slice if two
slices are located at the same row
> [mpeg2d] Invalid slices handling

- samples/sample_common/src/sample_utils.cpp
- samples/sample_decode/src/pipeline_decode.cpp
- Encapsulates logic of EOS flag handling to helper bitstream reader classes
- Fixes problem with possible forever loop in sample_decode
> sample_decode: improve EOS flag handling

- _studio/shared/src/libmfx_core.cpp
- _studio/shared/src/mfx_static_assert_structs.cpp
- api/include/mfxadapter.h
- api/include/mfxcommon.h
- api/include/mfxstructures.h
- api/mfx_dispatch/windows/include/mfx_vector.h
- api/mfx_dispatch/windows/src/mfx_dispatcher.cpp
- doc/mediasdk-man.md
- samples/sample_decode/include/pipeline_decode.h
- samples/sample_decode/src/pipeline_decode.cpp
- samples/sample_decode/src/sample_decode.cpp
- samples/sample_encode/include/pipeline_encode.h
- samples/sample_encode/src/pipeline_encode.cpp
- samples/sample_encode/src/sample_encode.cpp
- samples/sample_vpp/include/sample_vpp_utils.h
- samples/sample_vpp/src/sample_vpp_parser.cpp
- samples/sample_vpp/src/sample_vpp_utils.cpp
- Added new API to dispatcher
- Added information about adapter type to mfxPlatformInfo
- Added support of new API to sample_encode, sample_decode, sample_vpp
> Added support of multiadapters

- _studio/shared/umc/codec/brc/src/umc_h264_brc.cpp
> AVCe BRC: remove MFX_MIN/MAX macro

- _studio/shared/src/libmfx_allocator_vaapi.cpp
- samples/sample_common/src/vaapi_allocator.cpp
due driver changes in intel/media-driver@6b74dac
> Change allocators for correct choose fourcc

- _studio/mfx_lib/fei/h264_la/mfx_h264_la.cpp
> AVCe LA: remove MFX_MIN/MAX macro

- samples/sample_common/include/time_statistics.h
- samples/sample_common/src/sample_utils.cpp
- samples/sample_common/src/sysmem_allocator.cpp
- samples/sample_decode/src/pipeline_decode.cpp
- samples/sample_encode/src/pipeline_encode.cpp
- samples/sample_multi_transcode/include/transcode_utils.h
- samples/sample_plugins/rotate_cpu/src/plugin_rotate.cpp
> clang8 warnings fix: unknown pragmas

- _studio/mfx_lib/scheduler/include/mfx_scheduler_core.h
- _studio/mfx_lib/scheduler/src/mfx_scheduler_core.cpp
- _studio/mfx_lib/scheduler/src/mfx_scheduler_core_ischeduler.cpp
- _studio/mfx_lib/scheduler/src/mfx_scheduler_core_task_management.cpp
- _studio/mfx_lib/shared/include/mfx_interface_scheduler.h
- _studio/mfx_lib/shared/include/mfx_session.h
- _studio/mfx_lib/shared/src/libmfxsw_decode.cpp
- _studio/mfx_lib/shared/src/libmfxsw_enc.cpp
- _studio/mfx_lib/shared/src/libmfxsw_encode.cpp
- _studio/mfx_lib/shared/src/libmfxsw_ext.cpp
- _studio/mfx_lib/shared/src/libmfxsw_pak.cpp
- _studio/mfx_lib/shared/src/libmfxsw_plugin.cpp
- _studio/mfx_lib/shared/src/libmfxsw_session.cpp
- _studio/mfx_lib/shared/src/libmfxsw_vpp.cpp
- _studio/mfx_lib/shared/src/mfx_session.cpp
> [scheduler] Reduced code duplication

- samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp
External issue: https://bugs.freedesktop.org/show_bug.cgi?id=111788
> [metrics_monitor] Clamp sema counter to busy

- _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
Move enabling/disabling BRC reset flag to separate function from SetRateControl.
Enable this flag at Reset and disable at the end of the execute function to call hw reset while rendering.
> Fix BRC reset

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_brc.cpp
> HEVCe BRC: remove MFX_MIN/MAX macro

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw.cpp
Fix resorce pool which was inaccurate copy-pasted
from above lines.
> [HEVCE] fix typo in ReleaseResource

- tutorials/simple_1_session/CMakeLists.txt
- tutorials/simple_2_decode/CMakeLists.txt
- tutorials/simple_2_decode_vmem/CMakeLists.txt
- tutorials/simple_3_encode/CMakeLists.txt
- tutorials/simple_3_encode_vmem/CMakeLists.txt
- tutorials/simple_3_encode_vmem_async/CMakeLists.txt
- tutorials/simple_4_vpp_resize_denoise/CMakeLists.txt
- tutorials/simple_4_vpp_resize_denoise_vmem/CMakeLists.txt
- tutorials/simple_5_transcode/CMakeLists.txt
- tutorials/simple_5_transcode_opaque/CMakeLists.txt
- tutorials/simple_5_transcode_opaque_async/CMakeLists.txt
- tutorials/simple_5_transcode_opaque_async_vppresize/CMakeLists.txt
- tutorials/simple_5_transcode_vmem/CMakeLists.txt
- tutorials/simple_6_decode_vpp_postproc/CMakeLists.txt
- tutorials/simple_6_encode_vmem_lowlatency/CMakeLists.txt
- tutorials/simple_6_encode_vmem_vpp_preproc/CMakeLists.txt
- tutorials/simple_6_transcode_opaque_lowlatency/CMakeLists.txt
> [tutorials] Added pthread dependency

- _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_splitter.cpp
We need to handle start code chopping in case of a _cached_ unit
the same way as we already do for the case when we didn't cache bistream.
> [mpeg2d] Improved handling of start code chopping

- tutorials/common/common_vaapi.cpp
> [tutorials] Switched to render node initialization by default

- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_bs.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp
> HEVCe: remove MFX_MIN/MAX/Min/Max macro

- samples/sample_vpp/src/sample_vpp.cpp
> [sample_vpp] Small refactoring

- README.md
- doc/tutorials/mediasdk-tutorials-readme.md
> [tutorials] Cleaned up documentation

- _studio/shared/umc/codec/jpeg_common/src/membuffin.cpp
- _studio/shared/umc/codec/jpeg_common/src/membuffout.cpp
- _studio/shared/umc/codec/jpeg_dec/src/jpegdec.cpp
- _studio/shared/umc/codec/jpeg_dec/src/jpegdec_base.cpp
- _studio/shared/umc/codec/jpeg_dec/src/umc_jpeg_frame_constructor.cpp
- _studio/shared/umc/codec/jpeg_enc/src/jpegenc.cpp
- _studio/shared/umc/codec/jpeg_enc/src/jpegencrst.cpp
> jpeg: remove MFX_MIN/MAX macro

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
Alignment value depend on platform
> [HEVCe] Fix resolution alignment

- samples/sample_fei/src/auxiliary_interfaces.cpp
Some changes must not applicable in #1697 and need to revert.
> [sample_fei] Fix regression after recent refactoring

- _studio/mfx_lib/vpp/include/mfx_vpp_hw.h
- _studio/mfx_lib/vpp/src/mfx_detail_enhancement_vpp.cpp
- _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
- _studio/mfx_lib/vpp/src/mfx_vpp_sw_core.cpp
- _studio/mfx_lib/vpp/src/mfx_vpp_sw_internal.cpp
- _studio/mfx_lib/vpp/src/mfx_vpp_utils.cpp
> VPP: remove MFX_MIN/MAX macro

- _studio/mfx_lib/scheduler/src/mfx_scheduler_core.cpp
- _studio/mfx_lib/scheduler/src/mfx_scheduler_core_ischeduler.cpp
- _studio/shared/umc/core/umc/include/umc_structures.h
> UMC remove get_min/max functions

- samples/sample_camera/sample_camera.vcxproj
- samples/sample_camera/src/pipeline_camera.cpp
- samples/sample_camera/src/sample_camera_utils.cpp
- samples/sample_common/include/sample_defs.h
- samples/sample_common/src/avc_bitstream.cpp
- samples/sample_common/src/avc_nal_spl.cpp
- samples/sample_common/src/avc_spl.cpp
- samples/sample_common/src/sample_utils.cpp
- samples/sample_encode/src/pipeline_encode.cpp
- samples/sample_encode/src/pipeline_user.cpp
> samples: replace MSDK_MIN/MSDK_MAX macro with std::min/max

- README.md
> Fixed required cmake version in readme

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
Fix calculating number of macroblocks per slice
> [HEVCe] Fix calculating number of macroblocks per slice

- samples/sample_common/include/vaapi_utils_x11.h
- samples/sample_common/src/vaapi_utils_x11.cpp
> samples/decode: fix crash if X server can't be initialized

- _studio/mfx_lib/plugin/src/mfx_hevc_enc_plugin.cpp
- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
- _studio/shared/umc/codec/jpeg_common/src/bitstreamout.cpp
- samples/sample_common/include/avc_headers.h
[https://github.com/Intel-Media-SDK/MediaSDK/issues/3](https://github.com/Intel-Media-SDK/MediaSDK/issues/3)
[https://github.com/Intel-Media-SDK/MediaSDK/issues/5](https://github.com/Intel-Media-SDK/MediaSDK/issues/5)
> Remove unnecessary checks

- samples/sample_common/src/sample_utils.cpp
> Fix UV output height of P010 when CropH is odd.

- _studio/shared/umc/codec/jpeg_enc/src/jpegenc.cpp
Added access index check to prevent possible access violation
> Added access index check

- api/mfx_dispatch/windows/libmfx_vs2015.vcxproj
Issue: MDP-60078
Test: Manual test with Binskim
> Common: Enable spectre mitigation for libmfx_vs2015

- tutorials/common/common_utils.cpp
- tutorials/common/common_utils.h
- tutorials/simple_2_decode/src/simple_decode.cpp
- tutorials/simple_2_decode_vmem/src/simple_decode_vmem.cpp
- tutorials/simple_3_encode/src/simple_encode.cpp
- tutorials/simple_3_encode_vmem/src/simple_encode_vmem.cpp
- tutorials/simple_3_encode_vmem_async/src/simple_encode_vmem_async.cpp
- tutorials/simple_4_vpp_resize_denoise/src/simple_vpp.cpp
- tutorials/simple_4_vpp_resize_denoise_vmem/src/simple_vpp_vmem.cpp
- tutorials/simple_5_transcode/src/simple_transcode.cpp
- tutorials/simple_5_transcode_opaque/src/simple_transcode_opaque.cpp
- tutorials/simple_5_transcode_opaque_async/src/simple_transcode_opaque_async.cpp
- tutorials/simple_5_transcode_opaque_async_vppresize/src/simple_transcode_opaque_async_vppresize.cpp
- tutorials/simple_5_transcode_vmem/src/simple_transcode_vmem.cpp
- tutorials/simple_6_decode_vpp_postproc/src/simple_decode_vpp_pp.cpp
- tutorials/simple_6_encode_vmem_lowlatency/src/simple_encode_vmem_lowlat.cpp
- tutorials/simple_6_encode_vmem_vpp_preproc/src/simple_encode_vmem_preproc.cpp
- tutorials/simple_6_transcode_opaque_lowlatency/src/simple_transcode_opaque_lowlat.cpp
Prevent few possible memleaks & nullptr dereferences
> [Tutorials] Fix few issues

- samples/sample_common/include/sample_utils.h
- samples/sample_common/sample_common.vcxproj
- samples/sample_common/src/sample_utils.cpp
- samples/sample_encode/include/pipeline_encode.h
- samples/sample_encode/src/pipeline_encode.cpp
- samples/sample_encode/src/sample_encode.cpp
- samples/sample_plugins/rotate_cpu/sample_rotate_plugin.vcxproj
- samples/sample_plugins/rotate_opencl/sample_plugin_opencl.vcxproj
- samples/sample_plugins/vpp_plugin/vpp_plugin.vcxproj
- samples/sample_vpp/sample_vpp.vcxproj
sample_encode reads file with information for each frame (display order, QP,
frame type) and encodes stream in encoded order using this readed information.
> sample_encode: Added encoding in qpfile mode

- samples/sample_common/src/sysmem_allocator.cpp
When it is 16K resolution and 444 Chroma subsampling
we need value more then 16 bit variable allows
So need to use PitchLow and PitchHigh instead of just Pitch
Issue: MDP-58640
> [sample] Pitch calculating refactoring

- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
LA TGL kernel already enabled, but query wasnt update.
> [h264e] Fix LA support on TGL

- samples/sample_encode/src/pipeline_encode.cpp
Added initialization of m_bQPFileMode in constructor to prevent possible uninitialized use.
> Added initialization of m_bQPFileMode in constructor.

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
- _studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_ddi.h
- _studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_vaapi.h
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw.cpp
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_ddi.cpp
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_par.cpp
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_utils.cpp
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp
- _studio/shared/src/libmfx_allocator.cpp
Fixes: 444ecb48 ("Add 12-bit format support")
> Add missed lines in 12-bit formats support.

- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_par.cpp
[vp9e] Removed Pitch size check
Removing pitch size check
Issue: MDP-58640
Test: manual runs
> Vp9e remove pitch check

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
> Fix low-power HEVC encode

- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_utils.cpp
Added missing initialization of m_platform in constructor.
> Added initialization of m_platform in constructor

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw.cpp
- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
- _studio/shared/include/mfxstructures-int.h
- _studio/shared/src/cm_mem_copy.cpp
- _studio/shared/src/libmfx_core.cpp
- _studio/shared/src/libmfx_core_vaapi.cpp
- _studio/shared/umc/codec/h264_dec/src/umc_h264_mfx_supplier.cpp
- api/include/mfxcommon.h
> API 1.31 - JSL

- _studio/shared/src/libmfx_core_vaapi.cpp
> [core] Return error in case of unrecognized platform

- _studio/shared/src/libmfx_core_vaapi.cpp
> [core] Removed wrong JSL device ID

- _studio/mfx_lib/encode_hw/hevc/agnostic/hevcehw_extbuf.h
> Fix build w/ GCC5

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
Updated GetMaxNumRef() according to the latest information from driver
> [hevce] fix GetMaxNumRef()

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp
Only 3 and 0 are supported values
> [HEVCe]: Set cu_qp_delta_depth depending on LCUSize

- _studio/mfx_lib/encode/CMakeLists.txt
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_ddi.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp
- _studio/mfx_lib/shared/include/mediasdk_version.h
- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
- _studio/shared/src/cm_mem_copy.cpp
- _studio/shared/src/libmfx_core_vaapi.cpp
- _studio/shared/src/mfx_vpp_vaapi.cpp
- doc/mediasdk-man.md
- doc/samples/Media_Samples_Guide_Linux.md
- doc/samples/readme-decode_linux.md
- doc/samples/readme-encode_linux.md
- doc/samples/readme-multi-transcode_linux.md
- doc/samples/readme-vpp_linux.md
- samples/sample_common/include/version.h
- samples/sample_common/src/vaapi_allocator.cpp
> 19 4 0 scope

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
If qpi is not set default qps are used
> [HEVCe] add check for qp parameters

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp
Implemented balancing of IR stripes width (they can have now different
width based on caps.IntraRefreshBlockUnitSize) to meet target CycleSize
more accurately. Stripes remainder is in the tail frames.
> [HEVCe] Update IR stripes width calculation

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_ddi.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
Set SliceIPonly for VDEnc depending on platform and TU
> [HEVCe] disable RAB if no B slices

- _studio/shared/src/libmfx_core_hw.cpp
- _studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_utils.cpp
- _studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp
- _studio/shared/umc/codec/h265_dec/src/umc_h265_va_packer.cpp
- _studio/shared/umc/core/umc/include/umc_va_base.h
- _studio/shared/umc/io/umc_va/src/umc_va_linux.cpp
- api/include/mfxstructures.h
> Enable HEVC SCC decoding.

- doc/samples/Media_Samples_Guide_Linux.md
- doc/samples/readme-cpu-rotate-plugin_linux.md
- doc/samples/readme-cpu-rotate-plugin_linux.pdf
- doc/samples/readme-decode_linux.md
- doc/samples/readme-encode_linux.md
- doc/samples/readme-multi-transcode_linux.md
- doc/samples/readme-opencl-rotate-plugin_linux.md
- doc/samples/readme-opencl-rotate-plugin_linux.pdf
- doc/samples/readme-vpp_linux.md
- doc/samples/readme-vppplugin_linux.md
- doc/samples/readme-vppplugin_linux.pdf
Replace remaining pdfs with markdown.
Correct product name (cherry-pick from release branch).
Add cross-link to Samples Guide page.
> Update samples documentation

- doc/samples/readme-encode_linux.md
- doc/samples/readme-multi-transcode_linux.md
- samples/sample_encode/src/sample_encode.cpp
- samples/sample_multi_transcode/src/transcode_utils.cpp
> Add more sensible option for enable lowpower mode in se/smt

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
- _studio/mfx_lib/encode_hw/hevc/linux/g9/hevcehw_g9_va_lin.cpp
Remove some checks and add unmerged changes to refactored code.
> [HEVCe][HEVCe-r] Correct check of resolution and caps initialization

- doc/samples/readme-metrics_monitor_linux.md
- samples/metrics_monitor/include/cttmetrics.h
- samples/metrics_monitor/sample/cttmetrics_sample.cpp
- samples/metrics_monitor/src/cttmetrics.cpp
- samples/metrics_monitor/src/cttmetrics_i915_custom.cpp
- samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp
- samples/metrics_monitor/test/cttmetrics_gtest.cpp
> metrics_monitor: Let user specify a path to gfx device

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
- _studio/mfx_lib/encode_hw/hevc/agnostic/g9/hevcehw_g9_legacy_defaults.cpp
Add checks for sliding window HW BRC
> [HEVCe] Sliding window allowed for HW BRC

- _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
Return of the lost functionality from commit 7db64fc
Fix: #1929
> Fix mirroring for Linux with d3d->d3d

- api/mfx_dispatch/windows/include/mfx_dispatcher_log.h
Initialize m_hdl FILE pointer with nullptr.
Closes #1304
> Fix missing field initialization in mfx_dispatcher_log

- _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
We should avoid caps hardcoding
> [avce] Query driver possibility to accept RGB 

- _studio/mfx_lib/encode_hw/hevc/agnostic/g12/hevcehw_g12_rext.cpp
- _studio/mfx_lib/encode_hw/hevc/agnostic/g9/hevcehw_g9_data.h
- _studio/mfx_lib/encode_hw/hevc/agnostic/g9/hevcehw_g9_legacy.cpp
Fixed convert to native shift for MFX_FOURCC_P016 & MFX_FOURCC_Y216 formats
> [hevce][refactored] Fixed native shift converting for P016&Y216

- samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp
> metrics monitor: added zero ptr check

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
- _studio/mfx_lib/encode_hw/hevc/linux/g9/hevcehw_g9_va_packer_lin.cpp
Pass sliding window parameters to driver
> [hevce] Enable sliding window

- _studio/shared/src/libmfx_core_hw.cpp
- _studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_utils.cpp
- _studio/shared/umc/core/umc/include/umc_va_base.h
- _studio/shared/umc/io/umc_va/src/umc_va_linux.cpp
- api/include/mfxdefs.h
- api/include/mfxstructures.h
- doc/header-template.md
- doc/mediasdk-man.md
> Bump API to 1.32

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp
- _studio/mfx_lib/encode_hw/hevc/agnostic/g9/hevcehw_g9_legacy_defaults.cpp
if MaxKbps==0 it should be set in Targetkbps
> [hevce] Fix sliding window parameters issue

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp
Fix a regression, caused by 2f27753
> [hevce] Fix deblocking filter override flag

- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
This reverts commit 1f8456f10bdb204b0ea3067df7f5a3e8a1de407f.
> Revert "[AVCe] Changed ImplementationAvc Init and Reset behavior ..."

- samples/sample_vpp/src/sample_vpp_parser.cpp
- samples/sample_vpp/src/sample_vpp_utils.cpp
Issue #1995
Signed-off-by: egorovdanil <danil.egorov@intel.com>
> [sample_vpp] Add conversion support for Y210 and Y410 formats

- tutorials/common/common_vaapi.cpp
Fixes #1984
Signed-off-by: egorovdanil <danil.egorov@intel.com>
> [tutorials_common] Add Encode and VPP response handling in _simple_free

- _studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp
- _studio/shared/umc/codec/h265_dec/src/umc_h265_bitstream_headers.cpp
- _studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp
- _studio/shared/umc/codec/h265_dec/src/umc_h265_va_supplier.cpp
cherry-pick from internal branch
> Fix HEVCd SCC

- _studio/shared/umc/codec/h265_dec/include/platform/umc_h265_va_packer_vaapi_g12.hpp
- _studio/shared/umc/codec/h265_dec/src/umc_h265_bitstream_headers.cpp
- _studio/shared/umc/codec/h265_dec/src/umc_h265_slice_decoding.cpp
cherry pick from close source repo.
> Fix HEVCd SCC IntraBlockCopy/Palatte/MvControl Issues

- _studio/mfx_lib/vpp/src/mfx_vpp_sw_core.cpp
- _studio/mfx_lib/vpp/src/mfx_vpp_utils.cpp
- _studio/shared/src/mfx_vpp_vaapi.cpp
Issue: MDP-61179 MDP-61181
Tests: Manual
> [VPP] Add YV12 format output support according to driver's caps

- samples/sample_decode/src/pipeline_decode.cpp
> [sample_decode] Pass device to session right after session is created

- samples/sample_hevc_fei_abr/include/dso/bs_reader2.h
- tools/bs_parser_hevc/include/bs_reader2.h
> bs parser: avoid possible issues while passing bit fields to tracing macro

- _studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp
- _studio/mfx_lib/shared/src/mfx_common_int.cpp
- _studio/shared/umc/codec/h265_dec/include/umc_h265_va_packer_vaapi.h
- _studio/shared/umc/codec/h265_dec/src/umc_h265_va_packer_vaapi.cpp
> Enable Hevc vd+sfc resize

- _studio/mfx_lib/encode_hw/hevc/agnostic/g9/hevcehw_g9_legacy.cpp
Legacy code has same behavior.
> [hevce r] Fix tiles check

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp
- _studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h
- _studio/mfx_lib/shared/src/mfx_vc1_dec_common.cpp
- _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
- _studio/mfx_lib/vpp/src/mfx_vpp_jpeg_d3d9.cpp
- _studio/shared/include/mfx_vpp_interface.h
> Fix clang-11 warnings

- _studio/shared/src/libmfx_core_vaapi.cpp
Code synced with drm-tip rev 24b6efcf9
> Add missed TGL device IDs

- _studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h
- _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
> [h264e] Enable MaxSliceSize feature for Linux LowPower encoder

- _studio/mfx_lib/encode_hw/hevc/linux/g9/hevcehw_g9_va_packer_lin.cpp
Corresponding functionality in legacy code https://github.com/Intel-Media-SDK/MediaSDK/blob/master/_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp#L131
> [HEVCe r] Enable IntraRefresh feature

- _studio/shared/asc/CMakeLists.txt
- _studio/shared/asc/include/asc_avx2_impl.h
- _studio/shared/asc/include/asc_common_impl.h
- _studio/shared/asc/include/cpu_detect.h
- _studio/shared/asc/src/asc.cpp
- _studio/shared/asc/src/asc_sse4_impl.cpp
> asc: enable avx2 code path

- _studio/mfx_lib/encode_hw/hevc/agnostic/g9/hevcehw_g9_legacy_defaults.cpp
> [hevce r] Fix lowdelay brc parameters check

- samples/sample_encode/src/pipeline_encode.cpp
> [samples] Fixed uninitialized values in CEncodingPipeline constructor

- _studio/mfx_lib/encode/mjpeg/src/mfx_mjpeg_encode.cpp
> [jpege] Fix SW fallback initialization

- _studio/shared/umc/codec/h265_dec/include/umc_h265_slice_decoding.h
- _studio/shared/umc/codec/h265_dec/include/umc_h265_task_supplier.h
- _studio/shared/umc/codec/h265_dec/src/umc_h265_slice_decoding.cpp
- _studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp
Modify random access code logic
> [HEVCd] Fix display order corruption

- _studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp
- _studio/mfx_lib/encode/mjpeg/src/mfx_mjpeg_encode.cpp
- contrib/ipp/CMakeLists.txt
- contrib/ipp/include/ippcore.h
- contrib/ipp/src/ippinit.c
ippinit to be build without -msee4.2
other source files to be build for -msee4.2
Signed-off-by: egorovdanil <egorovdanil2905@gmail.com>
> Break ipp build into 2 parts

- _studio/shared/umc/codec/h265_dec/include/umc_h265_bitstream_headers.h
- _studio/shared/umc/codec/h265_dec/include/umc_h265_dec_defs.h
- _studio/shared/umc/codec/h265_dec/include/umc_h265_slice_decoding.h
- _studio/shared/umc/codec/h265_dec/src/umc_h265_bitstream_headers.cpp
- _studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_utils.cpp
- _studio/shared/umc/codec/h265_dec/src/umc_h265_slice_decoding.cpp
- _studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp
Fix HEVCd EntryPoint/disp_win_offset/PredWeightTable parsing issues.
> Fix HEVCd EntryPoint/disp_win_offset/PredWeightTable parsing issues

- android/include/mfx_android_config.h
- android/mfx_defs.mk
- samples/sample_vpp/src/sample_vpp_parser.cpp
- next Android dessert support is added
- compile error with c++17 standard is fixed
> update for Android platform

- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
- _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
- doc/samples/readme-encode_linux.md
- doc/samples/readme-multi-transcode_linux.md
- samples/sample_encode/src/sample_encode.cpp
- samples/sample_multi_transcode/src/transcode_utils.cpp
Added VCM mode support.
Added -vcm key to sample_encode and smt.
> [h264][sample_encode][smt] Add VCM mode

- samples/sample_encode/src/pipeline_encode.cpp
Shift should be set only for P010/P210/Y210 formats.
> [sample_encode] Fixed Shift setting

- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy.cpp
In RPS construction, change of RPS code length
in all slices was not considered.
Possible gain is about bit per slice.
> [hevce] Optimize RPS selection

- _studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_max_frame_size_lin.cpp
- _studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_max_frame_size_lin.h
- _studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_va_packer_lin.cpp
- _studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_va_packer_lin.h
> [hevce r] Add call chain for sequence parameters on Linux

- samples/sample_encode/include/pipeline_user.h
This commit for testing a new tool
> Small changes for Bridge tool testing

- _studio/shared/umc/codec/h264_dec/src/umc_h264_mfx_supplier.cpp
- _studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_utils.cpp
> Copy MaxDecFrameBuffering when querying

- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy.cpp
Real encoding codsiders I frame as RAP, but
RPS construction didn't. Number of refs differed
and some RPS from sps were unused but coded in
every slice.
Much affects encoding with short GOPs.
> [hevce] Fix RAP case in RPS creation

- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy.cpp
- _studio/mfx_lib/encode_hw/hevc/agnostic/g12/hevcehw_g12_rext.cpp
It would be changed to Variant format on driver side
> [hevce] Recon allocation should be transparrent for app

- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp
Use default ref list order with SCC
> [hevce] Fix SCC corruption issue

- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp
Fixed resulting RPL size computation.
> [hevce] Fix RefPicList control

- tools/tracer/loggers/timer.h
> [tracer] Fixed possible dereferencing of nullptr value

- tests/unit/suites/tracer/linux/mfx_tracer_test_cases_libs.cpp
Added initialization of statuses to prevent uninitialized use
> [tests] Fixed unitialized values

- doc/Coding_guidelines.md
Some minor improvements to our coding guide
> Update coding guide

- api/include/mfxadapter.h
> api: fix cdecl for adapters API

- _studio/mfx_lib/shared/src/mfx_vpx_dec_common.cpp
Issue: MDP-63072
Related to #2042
> [vp9d] Set correct max width and height for all platforms

- README.md
> docs: actualize list of projects which use mediasdk

- tools/tracer/dumps/dump.h
> [tracer] Fix build with libc++

- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
- _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
> [h264e] Return UNSUPPORTED, if sliding window is not supported by caps

- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp
According to
https://github.com/intel/media-driver/#decodingencoding-features, 444
encoding supports Low Power mode only. So we should turn the LowPower
flag on if user doesn't specify the encoding mode.
> hevce: use Low Power mode for 444 encoding by default

- _studio/mfx_lib/shared/src/mfx_vpx_dec_common.cpp
> [vp8d/vp9d] Fix PicStruct in Query

- _studio/mfx_lib/encode_hw/CMakeLists.txt
- _studio/mfx_lib/encode_hw/h265/include/mfx_h265_encode_hw_set.h
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp
- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp
- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_data.h
- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp
- _studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_va_packer_lin.cpp
- _studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_va_packer_lin.h
- _studio/mfx_lib/encode_hw/hevc/linux/g12/hevcehw_g12_lin.cpp
- _studio/mfx_lib/encode_hw/hevc/linux/g12/hevcehw_g12_qp_modulation_lin.cpp
- _studio/mfx_lib/encode_hw/hevc/linux/g12/hevcehw_g12_qp_modulation_lin.h
Pass QP mod parameters to driver
> [hevce] Enable QP modulation

- _studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_dirty_rect_lin.cpp
Because vaRectangle contains width and height
fields, inclusive or inclusive borders have
no meaning. And block alignment is not needed.
> [hevce] Fix DirtyRect borders on Linux

- _studio/mfx_lib/decode/av1/src/mfx_av1_dec_decode.cpp
- _studio/shared/umc/codec/av1_dec/src/umc_av1_decoder.cpp
- api/include/mfxstructures.h
> Add AV1 codec level checking for decoding

- samples/sample_plugins/rotate_opencl/CMakeLists.txt
- samples/sample_plugins/rotate_opencl/include/opencl_filter.h
- samples/sample_plugins/rotate_opencl/include/opencl_filter_dx11.h
- samples/sample_plugins/rotate_opencl/include/opencl_filter_dx9.h
- samples/sample_plugins/rotate_opencl/include/opencl_filter_va.h
- samples/sample_plugins/rotate_opencl/include/sample_opencl_plugin.h
- samples/sample_plugins/rotate_opencl/src/opencl_filter.cpp
- samples/sample_plugins/rotate_opencl/src/opencl_filter_dx11.cpp
- samples/sample_plugins/rotate_opencl/src/opencl_filter_dx9.cpp
- samples/sample_plugins/rotate_opencl/src/opencl_filter_va.cpp
Remove outdated include and defines. Amendment for #2190.
> Fixup b76c44afe("Use CL/cl2.hpp for rotate_opencl_plugin")

- README.md
* Removed the links to previous media sdk products, now the information
available here: https://github.com/Intel-Media-SDK/MediaSDK/wiki/Previous-Media-SDK-products
* Added the information about OpenVINO Toolkit and Open Visual Cloud
> Updated README.md with actual information about MediaSDK usage:

- _studio/mfx_lib/decode/av1/include/mfx_av1_dec_decode.h
- _studio/mfx_lib/decode/av1/src/mfx_av1_dec_decode.cpp
- _studio/shared/umc/codec/av1_dec/include/umc_av1_decoder.h
- _studio/shared/umc/codec/av1_dec/include/umc_av1_frame.h
- _studio/shared/umc/codec/av1_dec/src/umc_av1_decoder.cpp
- _studio/shared/umc/codec/av1_dec/src/umc_av1_frame.cpp
- _studio/shared/umc/codec/av1_dec/src/umc_av1_va_packer_vaapi.cpp
> Complete av1d output surface information.

- doc/mediasdk-man.md
> Update AV1 decoding related content into the document

- samples/sample_multi_transcode/src/pipeline_transcode.cpp
https://github.com/Intel-Media-SDK/MediaSDK/pull/2261#discussion_r465004055
> [smt] Update for possible memory leak fix in raw input case

- _studio/mfx_lib/decode/av1/src/mfx_av1_dec_decode.cpp
- api/include/mfxstructures.h
- doc/mediasdk-man.md
> Refine the member name of film grain flags

- tests/README.md
- tests/ted.py
- tests/ted/configuration.py
- tests/ted/test.py
- tests/tests/mpeg2d_conf.json
- print test log to stdout if test is failed
- add `mpeg2d_conf.json` test
- remove function for creating reports
- update README
- change path to samples folder
- add necessary environment variables: `LIBVA_DRIVER_NAME` and `LIBVA_DRIVERS_PATH`
> [ted] Move patches from infrastructure repo, update instructions

- samples/sample_multi_transcode/src/pipeline_transcode.cpp
Fixes: 90a079d ("[sample_multi_transcode] Add support for encoding I420 and NV12 streams")
> smt: fix fps overriding

- _studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_utils.cpp
It's a  temoral solution to unblock validations.
Signed-off-by: Li Shawn <shawn,li@intel.com>
> [HEVCd] Report CropW/CropH using conformance crops, not display crops

- _studio/mfx_lib/shared/include/mfx_brc_common.h
- _studio/mfx_lib/shared/src/mfx_brc_common.cpp
Port from Closed Source, New Delta QP 4,4,6 for Layer 1,2,3
respectively.
Overall 5-6% improvement in BDRate.
Issue: VSMGWL-28203
Tests: Manual
> [HEVCe] Add better 8GOP Fixed Pyramid QPs (FPQ) for HEVC ExtBRC

- _studio/mfx_lib/decode/h264/src/mfx_h264_dec_decode.cpp
- _studio/shared/src/mfx_static_assert_structs.cpp
- _studio/shared/umc/codec/h264_dec/include/umc_h264_bitstream_headers.h
- _studio/shared/umc/codec/h264_dec/include/umc_h264_dec.h
- _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h
- _studio/shared/umc/codec/h264_dec/src/umc_h264_dec_bitstream_headers.cpp
- _studio/shared/umc/codec/h264_dec/src/umc_h264_mfx_supplier.cpp
- _studio/shared/umc/codec/h264_dec/src/umc_h264_task_supplier.cpp
- api/include/mfxstructures.h
- doc/mediasdk-man.md
- tools/tracer/dumps/dump_mfxstructures.cpp
Support Decode AVC Level 6/6.1/6.2
Issue: MDP-47088
Change-Id: I42aa5f67b7480a264f86822d5e5e3cd750d8d090
> Support AVC Level 6/6.1/6.2

- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw.cpp
After https://github.com/intel/media-driver/pull/915/commits
> [VP9e] Removed recon surface alignment for Linux

- CODEOWNERS
> Updated code owners

- doc/mediasdk-man.md
> Complete AV1 film grain reference document

- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
Fixed CodecLevel initialization from other params,
particularly for VBR. Separated and fixed MVC params
initialization. Also some formattings aligned with cs.
Built and tested.
> [avce] Fix CodecLevel defaults

- _studio/shared/umc/codec/av1_dec/src/umc_av1_decoder_va.cpp
> Remove UMC_VA_LINUX macro for av1d

- doc/samples/readme-multi-transcode_linux.md
- samples/sample_multi_transcode/src/transcode_utils.cpp
> smt: add missing codecs to help/readme

- _studio/shared/umc/core/vm/src/vm_event_linux32.c
- _studio/shared/umc/core/vm/src/vm_semaphore_linux32.c
Historically time_t has been encoded on Linux as 32-bits signed
integer and with Linux 32 bits <5.6 it is still encoded as a 32-bits
signed integer. As a consequence beyond January 2038 gettimeofday()
will start returning a negative timestamp and this negative timestamp
will be supplied to pthread_cond_timedwait() by MediaSDK. The Linux
kernel will detects the invalid timestamp and return -EINVAL making
MediaSDK unusable.
This patch makes use of the 'clock_gettime(CLOCK_MONOTONIC, ...)' to
get current time since boot and configure the condition variable to
use the same clock.
Since this patch only impact the timestamped used for the
pthread_cond_timedwait() calls it has no impact in the other
components.
Signed-off-by: Jeremy Compostella <jeremy.compostella@intel.com>
> Fix Linux 32-bits encoded timestamp limitation - 2038K Bug

- _studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_common.cpp
> [vp8d] Fix always unknown picture structure

- _studio/mfx_lib/mctf_package/mctf/src/mctf_common.cpp
Klocwork analysis indicated two possible
issues with couple of pointers that are checked
for null.
Issue: VSMGWL-31602
Tests: Manual testing
> [MCTF] Fix for suspicious dereferencing

- doc/samples/readme-encode_linux.md
- samples/sample_common/src/sample_utils.cpp
- samples/sample_encode/src/pipeline_encode.cpp
- samples/sample_encode/src/sample_encode.cpp
Test:
./sample_encode h265 -i p016.yuv -p016 -w 176 -h 144 -o p016.h265 -msb10
./sample_encode h265 -i y216.yuv -y216 -w 176 -h 144 -o y216.h265 -msb10
> sample_encode: add p016/y216 FourCC support

- api/mfx_dispatch/windows/src/main.cpp
Added logic to handle combination of base impl and external_threading enum value passed to init.
> [Disp] Change single thread implementation to allow adapter selection

- samples/sample_common/src/sample_utils.cpp
> [samples] Support NV16 output

- _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp
- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_data.h
- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_interlace.cpp
- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy.cpp
- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy.h
- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp
> [hevce] Initialize frame_only_constraint_flag based on PicStruct

- samples/sample_decode/include/pipeline_decode.h
- samples/sample_decode/src/pipeline_decode.cpp
- samples/sample_decode/src/sample_decode.cpp
Support Decode AVC Level 6/6.1/6.2
Issue: MDP-47088
Test: sample_decode.exe h264 -i src_AVC_4K.mp4.h264 -o out.yuv -hw
> Sample_decode support AVC decode level 6+

- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
> clang-11: fix build

- samples/sample_decode/include/pipeline_decode.h
- samples/sample_decode/src/pipeline_decode.cpp
- samples/sample_decode/src/sample_decode.cpp
> sample_decode: ignore level constrain available in api 1.34

- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
- _studio/mfx_lib/vpp/include/mfx_vpp_hw.h
> Fix floating point exception in case of incorrect input streams

- _studio/mfx_lib/encode_hw/hevc/agnostic/g12/hevcehw_g12_caps.cpp
- _studio/mfx_lib/encode_hw/hevc/agnostic/g12/hevcehw_g12_rext.cpp
- _studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_va_packer_lin.cpp
- _studio/mfx_lib/encode_hw/hevc/linux/g12/hevcehw_g12_caps_lin.h
Correct some caps report values with LowPower on
> [HEVCe] Correct caps report values

- _studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_va_packer_lin.cpp
HRD parameters cause switching to CBR in media driver for HEVCe FEI
> [hevce] prevent HRD parameters submitting for CQP cases

- samples/sample_multi_transcode/src/sample_multi_transcode.cpp
> [samples] Support machines without adapters

- samples/sample_vpp/src/sample_vpp.cpp
> [sample_vpp] Enable runtime HSBC

- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils.cpp
598d021779d8952e823fc6b2537a34565bb1c53b
* [h264e] Add EncTools support in AVC Encoder
The changes to be submitted as a separate PR.
> [h264e] Revert LA changes brought in by EncTools commit:

- _studio/shared/src/mfx_vpp_vaapi.cpp
Issue: HSD1508270838
Test: manual
> [VPP] Fix ADI with ref output wrong field issue

- tutorials/common/common_utils.cpp
> Fixed wrong UV order

- tools/tracer/README.md
> Minor update of tracer readme file

- samples/sample_encode/include/pipeline_encode.h
- samples/sample_encode/src/pipeline_encode.cpp
- samples/sample_encode/src/pipeline_region_encode.cpp
Since a2f2115c mfxExtMVCSeqDesc in m_mfxVppParams is empty.
Issue: MDP-65303
> [sample_encode] Init mfxExtMVCSeqDesc for vpp

- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_data.h
- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp
- _studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_va_lin.cpp
- _studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_va_lin.h
- _studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_va_packer_lin.cpp
> [hevce] Get SliceStructure caps from driver

- _studio/shared/umc/codec/h264_dec/src/umc_h264_task_supplier.cpp
Fix the issue about some h264 streams which have a wrong way to calculate frame_num.
Issue: MDP-64211, MDP-48207
> [h264d] Modify the strategy about unmark the duplicated frame_num in DPB

- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
> [AVCe] Added tracing in the query part

- .github/workflows/ubuntu.yml
> ci: add api-latest and fastboot build configs

- samples/sample_multi_transcode/src/transcode_utils.cpp
Default memory type changed from opaq to video
Added option to set opaq
Perf val was launched, no difference on default mode found
> smt: new video memory default

- _studio/mfx_lib/mctf_package/mctf/src/mctf_common.cpp
It didn't work in joined sessions.
> [AVCe] Fixed broken opaque memory support in MCTF

- .github/workflows/ubuntu.yml
> ci: update cache before attempting to install packages

- _studio/mfx_lib/encode_hw/shared/ehw_device_vaapi.cpp
https://github.com/Intel-Media-SDK/MediaSDK/issues/2392
> Disable vaSyncBuffer usage

- _studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_common.cpp
> Chnage the max height of VP8 decoding

- doc/samples/readme-multi-transcode_linux.md
- samples/sample_multi_transcode/src/pipeline_transcode.cpp
- samples/sample_multi_transcode/src/transcode_utils.cpp
Added formats: p010, y210, y410
Issue: MDP-65302
Test: manually
./sample_multi_transcode -i::h265 in.h265 -o::h265 out.h265 -dc::nv12 -ec::y210
./sample_multi_transcode -i::h265 in.h265 -o::h265 out.h265 -dc::y210 -ec::p010
and others
> [smt] Add support for 10 bit formats

- samples/sample_encode/src/sample_encode.cpp
> [sample_encode] Support encoding of NV16 and P210

- _studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp
- _studio/shared/umc/codec/h265_dec/include/umc_h265_mfx_supplier.h
- _studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_supplier.cpp
> [h265d] VPS extraction support in DecodeHeader

- CMakeLists.txt
Auto version bump up
[Internal]
Commit_Type: RepoMaintenance
Platforms: N/A
OS: N/A
Feature impact: N/A
Resolves: N/A
Related-to: N/A
Klocwork: N/A
TP_Passed: N/A
IP Scan: PASS
> [Media Common] Bump up version to 21.1.2

- _studio/shared/src/mfx_vpp_vaapi.cpp
> Replace MFX_CHECK_WITH_ASSERT with MFX_CHECK in VPP Init and Query functions

- samples/sample_decode/include/pipeline_decode.h
- samples/sample_decode/src/pipeline_decode.cpp
> Default memtype is system for file dumping

- samples/sample_encode/src/sample_encode.cpp
> Fixed -yuy2 -ec::nv12 combination

- doc/samples/readme-decode_linux.md
- doc/samples/readme-encode_linux.md
- samples/sample_common/include/sample_utils.h
- samples/sample_decode/include/pipeline_decode.h
- samples/sample_decode/src/pipeline_decode.cpp
- samples/sample_decode/src/sample_decode.cpp
- samples/sample_encode/include/pipeline_encode.h
- samples/sample_encode/src/pipeline_encode.cpp
- samples/sample_encode/src/sample_encode.cpp
> FPS limiter in sample_decode and sample_encode

- _studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp
- _studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_utils.cpp
- _studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp
Issue:N/A
Test:sample_decode with mfxExtDecodeErrorReport
Signed-off-by: Ung, Teng En <teng.en.ung@intel.com>
> [hevcd] Enable the SPS/PPS error reporting

- _studio/enctools/include/mfx_enctools_brc.h
- _studio/enctools/src/mfx_enctools_brc.cpp
- _studio/enctools/src/mfx_enctools_common.cpp
- _studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
> [avc] HRD params from EncTools

- _studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
Issue: VSMGWL-31306
Test: manually
> [avce] adaptive P-pyramid fix

- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy.cpp
Reverts Intel-Media-SDK/MediaSDK#2601
> Revert "[HEVCe] Fix temporal layers reset issue"

- CMakeLists.txt
> [Media Common] Bump up version to 21.1.3

- _studio/mfx_lib/shared/include/mfx_mpeg2_encode_vaapi.h
- _studio/mfx_lib/shared/src/mfx_mpeg2_encode_vaapi.cpp
Now bitrate in VBR mode is close to target, but not to maximum.
> [MPEGe][Linux] pass target bitrate to driver for VBR

- _studio/mfx_lib/shared/src/mfx_mpeg2_encode_vaapi.cpp
Fixes recent commit #2621
Fixes #2622 issue
> [MPEGe][Linux] pass target bitrate to driver only for VBR

- _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
Set VA_RT_FORMAT depending on mfx FourCC
> [AVC] Fixed RT Format setting to vaCreateConfig func

- doc/samples/readme-encode_linux.md
- samples/sample_common/include/sample_utils.h
- samples/sample_common/src/sample_utils.cpp
- samples/sample_encode/include/pipeline_encode.h
- samples/sample_encode/src/pipeline_encode.cpp
- samples/sample_encode/src/sample_encode.cpp
> [sample_encode] parameter for TCBRC test was added

- samples/sample_decode/src/pipeline_decode.cpp
- samples/sample_multi_transcode/src/pipeline_transcode.cpp
> Add error message for trying to run av1d with d3d9

- doc/samples/readme-decode_linux.md
- doc/samples/readme-multi-transcode_linux.md
- samples/sample_decode/include/pipeline_decode.h
- samples/sample_decode/src/pipeline_decode.cpp
- samples/sample_decode/src/sample_decode.cpp
- samples/sample_multi_transcode/include/pipeline_transcode.h
- samples/sample_multi_transcode/src/pipeline_transcode.cpp
- samples/sample_multi_transcode/src/transcode_utils.cpp
> scaling_mode command line for samples

- CMakeLists.txt
> [Media Common] Bump up version to 21.2.0

- _studio/shared/umc/codec/h265_dec/src/umc_h265_va_packer_vaapi.cpp
line 116 is being mistakenly deleted
> [hevcd] Fix VD-SFC corruption issue

- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy.cpp
- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp
Intra refresh isn't supported with B-frames.
Fixes #2571
> [hevce] Add check for intra refresh with B-frames

- CMakeLists.txt
> [Media Common] Bump up version to 21.2.1

- samples/metrics_monitor/CMakeLists.txt
> cmake build fix on Windows

- _studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_va_packer_lin.cpp
Pass ICQQuality to media driver for ICQ with LowPower ON.
> [HEVCe] Pass ICQQuality with LowPower ON

- samples/sample_common/include/sample_utils.h
- samples/sample_common/src/sample_utils.cpp
- samples/sample_multi_transcode/include/pipeline_transcode.h
- samples/sample_multi_transcode/src/pipeline_transcode.cpp
This reverts commit 4068d111b87840ae9e3fe1003219308c8d350d3f.
> Revert "Set frame rate from IVF to decoder's params"

- _studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp
- _studio/shared/src/libmfx_allocator_vaapi.cpp
Modify JPEG RGB444 from partial acceleration to hardware
acceleration decode
Cmd:./sample_decode jpeg -i /home/gta/IMG_0425.bmp_RGB_444_100.jpg -o test.yuv -hw
Issue: MDP-66601
Test: manually
> [Jpegd]JPEG RGB444 support HW decode on Linux

- _studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_va_packer_lin.cpp
Moved settings for Intra Refresh and Rate Control VA misc parameters
from TaskSummit() to Init(). Otherwise pushing lambda’s to the CallChain
caused app memory growth.
Fixes #2681
> [hevce] Fix memory growth

- CMakeLists.txt
> [Media Common] Bump up version to 21.2.2

- _studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_weighted_prediction_lin.cpp
Enable GPU weighted prediction by passing size and offset of weighted table
and the flag.
> [HEVCE] enable GPU weighted prediction

- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_interlace.cpp
> [hevce/swbrc] Fix the skipping of second fields (update)

- CMakeLists.txt
> [Media Common] Bump up version to 21.2.3

- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
> [h264e] Removed unused code

- _studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_par.cpp
- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_utils.cpp
[VP9e] Fix input sysmem surface for vpl memory
[VP9e] Copy ScenarioInfo in case of Reset
[VP9e] Add WebRTC mode
> [vp9e] Vpl branch sync 

- samples/sample_multi_transcode/include/pipeline_transcode.h
- samples/sample_multi_transcode/src/pipeline_transcode.cpp
- samples/sample_multi_transcode/src/transcode_utils.cpp
[samples] Added "VuiTC" option to set VUI TransferCharacteristics in sample_multi_transcode.
Signed-off-by: Zhong, Xiaoxia <xiaoxia.zhong@intel.com>
> [samples] Added "VuiTC" option to set VUI TransferCharacteristics in sample_multi_transcode.

- samples/sample_common/src/sysmem_allocator.cpp
> [samples]: Fixed RGBP R/B channel swap issue

- CMakeLists.txt
> [Media Common] Bump up version to 21.3.0

- CMakeLists.txt
> [Media Common] Bump up version to 21.3.1

- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
> [AVCe] Separate max and default active refs

- CMakeLists.txt
> [Media Common] Bump up version to 21.3.2

- samples/sample_encode/src/pipeline_encode.cpp
Fix #2740
Issue: None
Test: manual
> [sample_encode] Validate input param vefore use it in Init

- CMakeLists.txt
> [Media Common] Bump up version to 21.3.3

- _studio/mfx_lib/encode_hw/mjpeg/src/mfx_mjpeg_encode_vaapi.cpp
> Removed multiple calls vaGetConfigAttributes

- _studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp
- _studio/shared/src/libmfx_allocator_vaapi.cpp
Modify JPEG RGB444 from partial acceleration to hardware
acceleration decode
Cmd:./sample_decode jpeg -i /home/gta/IMG_0425.bmp_RGB_444_100.jpg -o test.yuv -hw
Issue: MDP-66601
Test: manually
> [Jpegd] Enable HW to decode JPEG RGB444 on Linux

- CMakeLists.txt
> [Media Common] Bump up version to 21.3.4

- _studio/mfx_lib/decode/h264/src/mfx_h264_dec_decode.cpp
> [Decode]Enable AVC CSC via sfc pipeline

- _studio/shared/umc/codec/jpeg_dec/src/jpegdec.cpp
scan number should not exceed max value
Test: manually
> [Jpegd] check the scan component number of jpeg

- samples/sample_common/include/sample_types.h
- samples/sample_encode/src/pipeline_encode.cpp
> Fixed wstring into string conversion warning

- _studio/shared/umc/codec/jpeg_dec/src/jpegdec.cpp
Issue: MDP-66758
Test: manually
> [Jpegd]Check Quantization table destination selector

- CMakeLists.txt
> [Media Common] Bump up version to 21.4.2

- CMakeLists.txt
> [Media Common] Bump up version to 21.4.3

- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
> Fixed unnecessary warning from mfe internal defaults

- api/mfx_dispatch/windows/src/mfx_dispatcher_uwp.cpp
Added fallback for using intel_gfx_api*.dll from System folder
Fixed an exception in case no MediaSDK found on a system
(oneVPL-only platforms)
> [UWP] Updated Dispatcher for oneVPL-only platforms

- _studio/shared/umc/codec/vc1_dec/src/umc_vc1_video_decoder.cpp
To fix vc1d small bitstream issue mentioned at https://github.com/Intel-Media-SDK/MediaSDK/issues/2618
> [Decode] Fix VC1d small bitstream issue

- CMakeLists.txt
> [Media Common] Bump up version to 21.4.4

- _studio/shared/umc/codec/h264_dec/src/umc_h264_mfx_supplier.cpp
> Remove the avc profile that is not supported by the hw

- CMakeLists.txt
> [Media Common] Bump up version to 22.1.0

- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_alloc.cpp
- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_impl.cpp
- _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_impl.h
1.Defer unique pointer reset after the argument be used
2.Change variable Initialization from constructor to declaration
> [HEVCe/lib] Fix kw issue for unique pointer reset and initialization

- CMakeLists.txt
> [Media Common] Bump up version to 22.2.0

- _studio/shared/umc/codec/jpeg_dec/src/umc_mjpeg_mfx_decode_hw.cpp
> [Decode] check whether the buffer is out of bounds

- _studio/shared/umc/codec/jpeg_dec/src/jpegdec.cpp
> [Decode] check the value of numxMCU

- _studio/shared/umc/codec/jpeg_dec/include/jpegdec.h
- _studio/shared/umc/codec/jpeg_dec/src/jpegdec.cpp
> [Decode] Check whether the buffer exceeds the specified size

- _studio/shared/umc/codec/jpeg_dec/src/jpegdec.cpp
> [Decode] check the value of scan component

- _studio/shared/umc/codec/jpeg_dec/src/jpegdec.cpp
> [Decode] check whether dctbl pointer is null

- _studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils.cpp
> Fix setting recovery_frame_cnt for open GOP

- api/mfx_dispatch/linux/device_ids.h
In certain configurations, notably in containers it is possible to have /sys/class/drm/renderD128 and 
/sys/class/drm/renderD129 but no /dev/dri/renderD128. This fix enumerate all renderD128+(0..63) instead of stopping
at first failure.
> Scan all render nodes in dispatcher

- _studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils.cpp
- _studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
> Fix mfxExtPictureTimingSEI for interlaced

- CMakeLists.txt
> [Media Common] Bump up version to 22.2.1

- .github/workflows/ubuntu.yml
> build: fix build with gcc-11

- _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_decoder.cpp
> [Decode] Handling the abnormal state

- builder/profiles/readme.md
> Document build profiles

- CMakeLists.txt
> [Media Common] Bump up version to 22.2.2

- _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_decoder.cpp
Reverts Intel-Media-SDK/MediaSDK#2888
> Revert "[Decode] Handling the abnormal state"

- _studio/shared/umc/codec/h264_dec/include/umc_h264_dec_defs_dec.h
- _studio/shared/umc/codec/h264_dec/src/umc_h264_dec_bitstream_headers.cpp
> [Decode] Check whether the vui_ext_num_entries exceeds the specified value

- _studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp
- _studio/shared/umc/codec/jpeg_dec/src/jpegdec.cpp
> [Decode] scan component check code refactor

- _studio/shared/umc/codec/jpeg_dec/src/umc_mjpeg_mfx_decode_hw.cpp
> [Decode] array index check code refactor

- _studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw.cpp
> [Decode] Check if first_partition_size exceeds the length of the bitstream

- _studio/shared/umc/codec/jpeg_dec/src/jpegdec.cpp
- _studio/shared/umc/codec/jpeg_dec/src/jpegdec_base.cpp
> [Decode] sampling factor check code refactor

- _studio/shared/umc/codec/jpeg_dec/src/jpegdec.cpp
> [Decode] dctbl pointer check code refactor

- CMakeLists.txt
> [Media Common] Bump up version to 22.3.0

- _studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw_vaapi.cpp
> [Decode] check if the buffer size is valid

- _studio/shared/umc/codec/mpeg2_dec/include/umc_mpeg2_frame.h
- _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_decoder.cpp
> [Decode] Reasonably assign the first frame slice

- _studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_common.cpp
> [Decode] Check if the bitstream length is valid

- _studio/shared/umc/codec/mpeg2_dec/include/umc_mpeg2_frame.h
- _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_decoder.cpp
Reverts Intel-Media-SDK/MediaSDK#2893
> Revert "[Decode] Reasonably assign the first frame slice"

- CMakeLists.txt
> [Media Common] Bump up version to 22.4.0

- _studio/shared/umc/codec/color_space_converter/src/umc_video_processing.cpp
- _studio/shared/umc/codec/h264_dec/src/umc_h264_dec_bitstream_headers.cpp
array index has risk out of bound.
> [dec] fix some kw issues

- CMakeLists.txt
> [Media Common] Bump up version to 22.4.1

- _studio/enctools/src/mfx_enctools_common.cpp
- _studio/shared/umc/codec/brc/src/umc_h264_brc.cpp
array index has risk out of bound.
> [encode] fix some kw issues

- _studio/shared/umc/codec/color_space_converter/src/umc_video_processing.cpp
Array 'bFiltering' of size 8 may use index value(s) 8..24
> fix array out of bound risk

- _studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_decoder.cpp
add null check to fix segmentation fault
> Check NULL pointer to fix segmen fault

- CMakeLists.txt
> [Media Common] Bump up version to 22.4.3

- CMakeLists.txt
> [Media Common] Bump up version to 22.4.4

- android/include/mfx_android_config.h
- contrib/ipp/src/ippversion.h
- tools/tracer/dumps/dump_mfxfei.cpp
- tools/tracer/gui/ConfigManager.cs
- tools/tracer/gui/EtlDataCollector.cs
- tools/tracer/gui/EtlToTextConverter.cs
- tools/tracer/gui/Import.cs
- tools/tracer/gui/MsdkAnalyzerCpp.cs
- tools/tracer/gui/Program.cs
- tools/tracer/gui/Properties/AssemblyInfo.cs
- tools/tracer/gui/SdkAnalyzerForm.Designer.cs
- tools/tracer/gui/SdkAnalyzerForm.cs
- tools/tracer/gui/WinApi.cs
> Removed proprietary mentions from file headers

- CODEOWNERS
tech leader approval is good enough, no need additional mediasdk-admin approval.
> Codeowners update to get tech leader review

- CMakeLists.txt
> [Media Common] Bump up version to 22.5.0

- CMakeLists.txt
> [Media Common] Bump up version to 22.5.1

- _studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw.cpp
With this patch, the ivf strem play smoothness.
> [VP9e] correct ivf header fps.

- CMakeLists.txt
> [Media Common] Bump up version to 22.5.2

- CMakeLists.txt
> [Media Common] Bump up version to 22.5.3

- .github/workflows/ubuntu.yml
> ci: switch to ubuntu 22.04 from ubuntu 21.10 for gcc-11

- _studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp
This PR is to support HEVC upscale needs
> [Decode] Support HEVC upscale

- CMakeLists.txt
> [Media Common] Bump up version to 22.5.4

- CMakeLists.txt
> [Media Common] Bump up version to 22.6.0

- CMakeLists.txt
> [Media Common] Bump up version to 22.6.1

- CMakeLists.txt
> [Media Common] Bump up version to 22.6.2

- CMakeLists.txt
> [Media Common] Bump up version to 22.6.3

- CMakeLists.txt
> [Media Common] Bump up version to 22.6.4

- CMakeLists.txt
> [Media Common] Bump up version to 22.6.5

- CMakeLists.txt
> [Media Common] Bump up version to 23.1.0

- CMakeLists.txt
> [Media Common] Bump up version to 23.1.1

- CMakeLists.txt
> [Media Common] Bump up version to 23.1.2

- CMakeLists.txt
> [Media Common] Bump up version to 23.1.3

- CMakeLists.txt
> [Media Common] Bump up version to 23.1.4

- CMakeLists.txt
> [Media Common] Bump up version to 23.1.5

- _studio/mfx_lib/decode/vp8/include/mfx_vp8_dec_decode_hw.h
- _studio/mfx_lib/decode/vp8/include/mfx_vp8_dec_decode_vp8_defs.h
- _studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_common.cpp
- _studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw.cpp
The data length exeding the max length of data.
Add checking of remaininga bitstream data size.
Add checking of n_bytes_offset size.
Add checking of dataSize size.
> [Decode] Fix memory out-of-bounds issue for VP8

- CMakeLists.txt
> [Media Common] Bump up version to 23.2.0

- CMakeLists.txt
> [Media Common] Bump up version to 23.2.1
